import type { IndustryPack } from "./define";

// E-commerce and retail. Product claims stay specific and supported; no
// invented reviews, reference prices or environmental claims.

const CLAIMS = "Only make claims supported by the product details I give. No fake reviews, no invented statistics, and no 'eco-friendly', 'natural' or 'made in USA' claims unless I state they are true and can be backed up.";

export const ECOMMERCE: IndustryPack = {
  id: "ecommerce",
  label: "E-commerce and retail",
  prompts: [
    // ── Product Listings & Descriptions ──
    {
      c: "Product Listings & Descriptions",
      t: "Listing: Product Description That Sells",
      u: "You have product specs and need a description that converts.",
      p: `Act as a senior e-commerce copywriter. Write a product description for [PRODUCT] sold by [BRAND] to [TARGET CUSTOMER]. Specs and facts: [SPECS]. Structure: a one-line hook focused on the main benefit, a short paragraph on how it fits the customer's life, 5 benefit-led bullet points (feature then why it matters), a 'what's included' list, and care or sizing notes [NOTES]. 150 to 220 words, brand voice [VOICE]. ${CLAIMS}`,
      tip: "Write for one specific customer. 'For runners training for their first marathon' converts better than 'for everyone'.",
    },
    {
      c: "Product Listings & Descriptions",
      t: "Listing: Amazon Title and Bullets",
      u: "You are listing on Amazon and need a compliant title and bullets.",
      p: `Write an Amazon listing for [PRODUCT] by [BRAND]. Title under 200 characters following the pattern Brand + Product + key attribute + size/quantity [DETAILS]. Five bullet points, each starting with a benefit in capitals followed by the supporting feature, under 250 characters each. Backend search terms (under 250 bytes, no repetition of title words, no brand names of others). ${CLAIMS} Follow Amazon's style guide: no promotional phrases like 'best seller'.`,
      tip: "Put the most-searched attribute early in the title; mobile shoppers see only the first 70 or so characters.",
    },
    {
      c: "Product Listings & Descriptions",
      t: "Listing: Rewrite Supplier Copy Into Brand Voice",
      u: "You are using the manufacturer's description and it reads like everyone else's.",
      p: `Rewrite this supplier product description in [BRAND]'s voice [VOICE DESCRIPTION]: [PASTE SUPPLIER COPY]. Keep every factual spec accurate, remove filler, lead with the customer benefit, and make it unique so it does not duplicate other sites. Under 180 words. List any claims in the supplier copy that need verification before we use them.`,
      tip: "Duplicate supplier copy hurts search rankings. Unique descriptions on your best sellers are worth the effort.",
    },
    {
      c: "Product Listings & Descriptions",
      t: "SEO: Collection Page Copy",
      u: "Your category pages have no text and do not rank.",
      p: `Write collection page copy for [COLLECTION, e.g. women's trail running shoes] on [STORE NAME]. Include: a 60-word intro above the products that helps shoppers choose, and a 250-word section below the grid covering how to choose [KEY CHOICE FACTORS], who the range suits, and 3 short FAQs. Use the phrases customers search [KEYWORDS] naturally. ${CLAIMS}`,
      tip: "Buying guidance ranks better than keyword stuffing, and it lifts conversion too.",
    },
    {
      c: "Product Listings & Descriptions",
      t: "Guide: Size and Fit Guide",
      u: "Returns for size are high and customers ask the same fit questions.",
      p: `Create a size and fit guide for [PRODUCT TYPE] from [BRAND]. Measurements: [SIZE CHART DATA]. Include: how to measure yourself (step by step), how our sizing compares to typical sizing [FIT NOTES, e.g. runs small], what to do between sizes, and fit notes by body type if we have them [NOTES]. Clear table plus short paragraphs.`,
      tip: "Add 'our model is 5 ft 8 and wears size M' to product pages. It reduces size returns noticeably.",
    },
    {
      c: "Product Listings & Descriptions",
      t: "Listing: Bundle or Gift Set Description",
      u: "You are creating a bundle and need copy that explains the value.",
      p: `Write a product description for a bundle called [BUNDLE NAME] containing [ITEMS]. Explain who it is for, why these items belong together, the price and what it would cost separately only if true [PRICES], and gift messaging options [IF OFFERED]. Under 150 words, plus 3 bullet points. ${CLAIMS}`,
      tip: "Name the occasion ('the new-parent kit') rather than the contents; bundles sell on the moment, not the parts.",
    },
    {
      c: "Product Listings & Descriptions",
      t: "Alt Text and Image Captions for Product Photos",
      u: "Your product images lack alt text, which hurts accessibility and search.",
      p: `Write alt text for these product images of [PRODUCT]: [DESCRIBE EACH IMAGE, e.g. front view, detail of zip, worn by model]. Each under 125 characters, describing what is shown for someone who cannot see it, including color and key detail. Then write short captions for a lifestyle image and a detail image.`,
      tip: "Good alt text is written for a person using a screen reader, not for search engines.",
    },

    // ── Email & SMS Marketing ──
    {
      c: "Email & SMS Marketing",
      t: "Flow: Welcome Email Series",
      u: "New subscribers join your list and you want them to buy.",
      p: `Write a 4-email welcome series for [STORE NAME], which sells [PRODUCTS] to [CUSTOMER]. Email 1 (immediately): welcome and the signup offer [OFFER IF ANY]. Email 2 (day 2): the brand story and what makes us different [FACTS]. Email 3 (day 4): best sellers and why people love them (no invented reviews). Email 4 (day 7): reminder of the offer or a useful guide. Each: subject line, preview text, and body under 150 words. Include unsubscribe and address.`,
      tip: "The welcome flow often earns more per email than any campaign. Get it right before sending newsletters.",
    },
    {
      c: "Email & SMS Marketing",
      t: "Flow: Abandoned Cart Sequence",
      u: "Shoppers leave items in the cart and you want to recover them.",
      p: `Write a 3-message abandoned cart sequence for [STORE NAME]. Message 1 (1 hour, email): friendly reminder with the item [ITEM PLACEHOLDER] and one reason to buy. Message 2 (24 hours, email): answer a common objection [SHIPPING, RETURNS, SIZING]. Message 3 (48 hours, SMS if consented): short nudge, optional incentive [IF ANY]. Subject lines included. No fake urgency or false low-stock claims.`,
      tip: "Answering the likely objection (returns, shipping cost) recovers more carts than a discount.",
    },
    {
      c: "Email & SMS Marketing",
      t: "Campaign: Product Launch Email",
      u: "You are launching a new product and want a strong launch email.",
      p: `Write a launch email for [PRODUCT] from [STORE NAME]. Include: 3 subject line options, preview text, a headline, the problem it solves, 3 benefits [FACTS], launch offer or early access [IF ANY, WITH END DATE], and one clear call to action. Under 220 words, brand voice [VOICE]. ${CLAIMS}`,
      tip: "Send a 'coming soon' teaser to your best customers first. Early buyers create the first reviews.",
    },
    {
      c: "Email & SMS Marketing",
      t: "SMS: Campaign Text Messages",
      u: "You want SMS promotions that do not annoy people into unsubscribing.",
      p: `Write 5 SMS messages for [STORE NAME] for [OCCASION OR PROMOTION]. Each under 160 characters, with the brand name at the start, a clear offer or reason to click [LINK], and 'Reply STOP to opt out'. Send only to people who opted in to SMS. Vary the angle: new arrival, restock, offer, reminder, thank you.`,
      tip: "Fewer, better texts keep opt-outs low. Two a month is plenty for most brands.",
    },
    {
      c: "Email & SMS Marketing",
      t: "Flow: Post-Purchase Emails",
      u: "You want customers to love the product and buy again.",
      p: `Write a post-purchase flow for [STORE NAME]: order confirmation extras (what happens next), shipping update, delivery day (how to get the best from the product [TIPS]), a check-in at day 7, a review request at day 14 [LINK], and a cross-sell at day 30 for [COMPLEMENTARY PRODUCT]. Subject lines and bodies under 120 words each.`,
      tip: "The 'how to get the best from it' email reduces returns and lifts reviews at the same time.",
    },
    {
      c: "Email & SMS Marketing",
      t: "Flow: Win-Back Emails for Lapsed Customers",
      u: "Customers bought once and never came back.",
      p: `Write a 3-email win-back sequence for customers who have not purchased from [STORE NAME] in [DAYS] days. Email 1: what is new since they last visited [NEW ITEMS]. Email 2: a reason to return [OFFER IF ANY, WITH END DATE]. Email 3: a friendly 'should we stay in touch?' with a preference link. Subject lines and bodies under 120 words each.`,
      tip: "The 'should we stay in touch?' email cleans your list and often gets the best response of the three.",
    },
    {
      c: "Email & SMS Marketing",
      t: "Campaign: Holiday and Sale Calendar",
      u: "You want a plan for the year's key sales moments.",
      p: `Create a 12-month email and SMS promotion calendar for [STORE NAME] selling [PRODUCTS] to [CUSTOMER] in [COUNTRY]. Include key retail dates, product-relevant moments [SEASONALITY], how many sends per month, which offers to run and which months to protect margin, and one non-promotional content email per month. Table format.`,
      tip: "Plan the months you will not discount as carefully as the ones you will; constant sales train customers to wait.",
    },

    // ── Customer Service ──
    {
      c: "Customer Service",
      t: "Reply: Where Is My Order",
      u: "Customers ask about delayed orders and you want quick, consistent replies.",
      p: `Write customer service replies for [STORE NAME] for: an order in transit [TRACKING PLACEHOLDER], an order delayed at the carrier, an order showing delivered but not received, and a backordered item [NEW DATE]. Each under 110 words, empathetic, specific about next steps and our policy [POLICY].`,
      tip: "Proactive delay emails cut 'where is my order' tickets sharply. Send them before customers ask.",
    },
    {
      c: "Customer Service",
      t: "Reply: Return and Refund Requests",
      u: "You handle returns and want replies that are clear and kind.",
      p: `Write reply templates for [STORE NAME] for: an eligible return (how to return [PROCESS]), a return outside the window [POLICY], a damaged item on arrival, and a refund status question [TIMEFRAME]. Each under 120 words, warm, clear and consistent with our policy [PASTE RETURNS POLICY].`,
      tip: "A generous, clear returns policy increases conversion. Make the reply as easy as the policy.",
    },
    {
      c: "Customer Service",
      t: "Policy: Clear Returns Policy Page",
      u: "Your returns policy is confusing and customers keep asking.",
      p: `Rewrite our returns policy for [STORE NAME] in plain language: [PASTE CURRENT POLICY OR KEY TERMS]. Sections: returns window, condition required, how to start a return, who pays shipping, refund timing and method, exchanges, non-returnable items, and damaged or wrong items. Under 400 words, friendly headings, and keep the terms exactly as they are.`,
      tip: "Link the policy from every product page. Customers check it before buying more than you think.",
    },
    {
      c: "Customer Service",
      t: "Reply: Handling an Angry Customer",
      u: "A customer is furious and you want to calm things down.",
      p: `Write a reply to this angry customer message: [PASTE MESSAGE]. Order facts: [FACTS]. What we can offer [OPTIONS]. Acknowledge their frustration without over-apologising, take ownership of what went wrong, give a clear fix with a timeline, and end with a personal sign-off [NAME]. Under 150 words.`,
      tip: "A fast, human fix turns angry customers into loyal ones more often than any discount.",
    },
    {
      c: "Customer Service",
      t: "Macros: Help Desk Saved Replies",
      u: "Your team answers the same questions and needs a library of saved replies.",
      p: `Create 10 saved replies for [STORE NAME]'s help desk covering our most common questions [LIST QUESTIONS, e.g. shipping times, international orders, discount code not working, change address]. Each under 90 words with placeholders for order details, consistent brand voice [VOICE], and a clear next step.`,
      tip: "Review the top 10 macros monthly; the questions change as products and policies change.",
    },
    {
      c: "Customer Service",
      t: "Chatbot: FAQ Knowledge Base for a Chat Assistant",
      u: "You want a chat assistant that answers accurately from your policies.",
      p: `Turn our store information into a structured knowledge base for a chat assistant: [PASTE SHIPPING, RETURNS, SIZING, PAYMENT, CONTACT INFO]. Format as question and answer pairs (at least 20), each answer under 60 words, accurate to the source. Add a list of questions the assistant should hand to a human (for example, damaged items, chargebacks, complaints).`,
      tip: "Tell the assistant when to hand over. Customers hate bots that will not let them reach a person.",
    },
    {
      c: "Customer Service",
      t: "Reply: Out-of-Stock Item Request",
      u: "A customer wants an item that is sold out.",
      p: `Write a reply to a customer asking about sold-out [PRODUCT]. Include expected restock timing if known [DATE OR UNKNOWN], an option to join the back-in-stock list [HOW], and 2 alternatives we have in stock [ALTERNATIVES]. Under 100 words, helpful.`,
      tip: "Back-in-stock lists often convert very well. Make joining one click.",
    },

    // ── Social Media & Content ──
    {
      c: "Social Media & Content",
      t: "Social: Month of Instagram Content",
      u: "You need a steady stream of posts without running out of ideas.",
      p: `Create a 4-week Instagram plan for [STORE NAME] selling [PRODUCTS] to [CUSTOMER]. 4 posts per week mixing: product in use, behind the scenes, customer content (with permission), education or how-to, and one promotional post per week. For each: format (reel, carousel, photo), caption under 100 words, and 5 relevant hashtags. ${CLAIMS}`,
      tip: "Behind-the-scenes and how-to posts build trust; product posts sell. Keep promotion to about one in four.",
    },
    {
      c: "Social Media & Content",
      t: "Video: Short-Form Product Video Scripts",
      u: "You want TikTok or Reels scripts that show products in action.",
      p: `Write 5 short video scripts (15 to 30 seconds) for [PRODUCT] from [BRAND]. Angles: problem and solution, unboxing, 3 ways to use it, a common mistake, and a before and after [IF APPLICABLE]. Each with a hook in the first 2 seconds, shot list, on-screen text, and a call to action. ${CLAIMS}`,
      tip: "Film vertically, with captions on screen; most people watch without sound.",
    },
    {
      c: "Social Media & Content",
      t: "Blog: Buying Guide Article",
      u: "You want content that brings shoppers from search and helps them choose.",
      p: `Write a 900-word buying guide: 'How to choose [PRODUCT TYPE]' for [CUSTOMER]. Include the key factors to consider [FACTORS], common mistakes, a simple comparison table of our options [PRODUCTS AND DIFFERENCES], and FAQs. Genuinely helpful, not a sales pitch, with links to our products where relevant. ${CLAIMS}`,
      tip: "Honest guides that sometimes say 'this is not for you' build trust and get linked to.",
    },
    {
      c: "Social Media & Content",
      t: "Influencer: Outreach Message to a Creator",
      u: "You want to work with creators who fit your brand.",
      p: `Write an outreach message from [BRAND] to [CREATOR TYPE] with an audience of [AUDIENCE]. Mention a specific post we liked [POST], why our product fits their audience [REASON], what we propose (gifted product, paid post, affiliate [TERMS]), and that sponsored content must be clearly disclosed (for example #ad). Under 150 words, genuine.`,
      tip: "Micro-creators with engaged niche audiences usually outperform large accounts for small brands.",
    },
    {
      c: "Social Media & Content",
      t: "Content: User-Generated Content Request",
      u: "You want customers to share photos you can use.",
      p: `Write a message asking customers of [STORE NAME] to share photos using [PRODUCT] with [HASHTAG]. Explain how we may feature them, that we will always ask permission before reposting, and any thank-you [IF ANY, NOT CONDITIONAL ON A POSITIVE REVIEW]. Under 100 words for email, under 60 for a package insert card.`,
      tip: "Ask permission in the comments before reposting, and save the reply; it is your record of consent.",
    },
    {
      c: "Social Media & Content",
      t: "Story: Brand Story for the About Page",
      u: "Your About page is bland and does not explain why you exist.",
      p: `Write an About page for [BRAND]. Facts: founder story [STORY], why we started [REASON], what we make and how [PROCESS], values [VALUES], and who we serve [CUSTOMER]. 300 to 450 words, personal and specific, with a closing line that links to our best sellers. ${CLAIMS}`,
      tip: "Specific details (the kitchen table, the first order) make brand stories believable. Avoid mission-statement language.",
    },
    {
      c: "Social Media & Content",
      t: "Social: Replies to Common Comments and DMs",
      u: "You get the same comments and messages on social and want good replies.",
      p: `Write reply templates for [BRAND]'s social accounts for: 'How much?', 'Do you ship to [COUNTRY]?', 'Is this in stock?', a compliment, a complaint in public comments, and a question about sizing. Each under 50 words, friendly brand voice [VOICE], moving private matters to DMs.`,
      tip: "Reply to every question comment within a day; each answer is visible to everyone else considering buying.",
    },

    // ── Ads & Promotions ──
    {
      c: "Ads & Promotions",
      t: "Ads: Meta Ad Copy Variations",
      u: "You want several ad angles to test on Facebook and Instagram.",
      p: `Write 6 Meta ad variations for [PRODUCT] targeting [AUDIENCE]. Angles: problem and solution, social proof (only real numbers I give [REAL NUMBERS]), benefit-led, founder story, offer [IF ANY], and objection-handling. Each: primary text under 125 characters, headline under 40 characters, and a description. ${CLAIMS}`,
      tip: "Test angles, not word tweaks. The angle usually changes results far more than the wording.",
    },
    {
      c: "Ads & Promotions",
      t: "Ads: Google Shopping and Search Copy",
      u: "You want search ads and better product titles for Shopping.",
      p: `Write Google Ads copy for [STORE NAME] selling [PRODUCT CATEGORY]: 3 responsive search ads (15 headlines under 30 characters, 4 descriptions under 90 characters), plus optimised Shopping product titles for these products [PRODUCT LIST WITH ATTRIBUTES]. Include key attributes (brand, type, color, size) near the start. ${CLAIMS}`,
      tip: "Shopping titles matter more than ads for product searches; put the attribute people search first.",
    },
    {
      c: "Ads & Promotions",
      t: "Promo: Sale Announcement With Clear Terms",
      u: "You are running a sale and want it clear and compliant.",
      p: `Write a sale announcement for [STORE NAME]: [OFFER, e.g. 20% off sitewide] from [START] to [END]. Include clear terms (exclusions, one code per order, how discount applies) [TERMS], an email version, a banner line under 60 characters, and a social caption. Show 'was' prices only if we genuinely sold at them recently. No fake countdowns.`,
      tip: "Clear exclusions in the announcement prevent a wave of 'code not working' tickets.",
    },
    {
      c: "Ads & Promotions",
      t: "Landing Page: Campaign Landing Page Copy",
      u: "Ad traffic lands on a generic page and does not convert.",
      p: `Write landing page copy for [CAMPAIGN OR PRODUCT] aimed at [AUDIENCE] arriving from [AD ANGLE]. Sections: headline matching the ad promise, subheadline, 3 benefits with icons ideas, how it works, real reviews placeholder [INSERT REAL REVIEWS], FAQ (4 questions), guarantee or returns reassurance [POLICY], and a call to action repeated twice. ${CLAIMS}`,
      tip: "Match the headline to the ad people clicked; mismatched promises are the biggest conversion leak.",
    },
    {
      c: "Ads & Promotions",
      t: "Offer: Designing a Promotion That Protects Margin",
      u: "You want to run a promotion without destroying profit.",
      p: `Act as an e-commerce growth consultant. My product economics: price [PRICE], cost of goods [COGS], shipping cost [SHIPPING], average order value [AOV], and typical conversion rate [RATE]. Compare 4 promotion types (percentage off, free shipping threshold, gift with purchase, bundle discount) and show the margin effect of each with calculations. Recommend one with reasoning.`,
      tip: "Free shipping thresholds set just above your average order value often lift revenue without hurting margin.",
    },
    {
      c: "Ads & Promotions",
      t: "Retargeting: Ad Copy for Site Visitors",
      u: "You want ads for people who visited but did not buy.",
      p: `Write 4 retargeting ads for [STORE NAME] aimed at visitors who viewed [PRODUCT OR CATEGORY] but did not buy. Angles: remind, answer an objection [OBJECTION], social proof [REAL DATA ONLY], and a time-limited offer [IF ANY, WITH REAL END DATE]. Short primary text and headline each.`,
      tip: "Cap retargeting frequency. Seeing the same ad twenty times a week puts people off the brand.",
    },
    {
      c: "Ads & Promotions",
      t: "Affiliate: Affiliate Program Terms Summary",
      u: "You are launching an affiliate program and need clear terms.",
      p: `Write a plain-language affiliate program summary for [STORE NAME]: commission rate [RATE], cookie window [DAYS], payment terms [TERMS], what affiliates may and may not do (no fake reviews, no bidding on our brand name, clear #ad or affiliate disclosure as the FTC requires), and how to apply. Under 400 words.`,
      tip: "Put the disclosure rule in the terms. You can be responsible for misleading affiliate claims.",
    },

    // ── Reviews & Trust ──
    {
      c: "Reviews & Trust",
      t: "Request: Review Request Email",
      u: "You want more product reviews from real buyers.",
      p: `Write a review request email for [STORE NAME] sent [DAYS] days after delivery of [PRODUCT]. Ask every buyer, make it one click [LINK], suggest what might help other shoppers (fit, quality, how they use it) without telling them what to say, and offer no incentive tied to a positive review. Subject line plus body under 110 words.`,
      tip: "Timing matters: ask after they have used the product, not the day it arrives.",
    },
    {
      c: "Reviews & Trust",
      t: "Reply: Responding to a Negative Product Review",
      u: "A customer posted a bad review on a product page.",
      p: `Write a public reply to this product review: [PASTE REVIEW]. Thank them, acknowledge the issue, explain any helpful information (sizing, usage [INFO]) without arguing, and offer to make it right via [CONTACT]. Under 80 words. Never ask them to remove the review.`,
      tip: "Leave negative reviews up. A mix of reviews with thoughtful replies is more believable than all five stars.",
    },
    {
      c: "Reviews & Trust",
      t: "Analysis: Insights From Customer Reviews",
      u: "You have hundreds of reviews and want to know what they say.",
      p: `Analyse these customer reviews for [PRODUCT]: [PASTE REVIEWS]. Identify: top 5 things customers love (with example quotes), top 5 complaints, words customers use to describe the product (useful for copy), common questions implied by reviews, and 3 product or listing improvements. Quote exactly; do not invent reviews.`,
      tip: "Use the exact words customers use in your product copy; it is language that already convinced someone.",
    },
    {
      c: "Reviews & Trust",
      t: "Page: Trust and Shipping Information Page",
      u: "New visitors hesitate to buy from a store they do not know.",
      p: `Write a 'Why shop with us' section for [STORE NAME] covering: shipping times and costs [DETAILS], returns [POLICY SUMMARY], secure payment options [OPTIONS], customer service hours and contact [DETAILS], where we are based [LOCATION], and real review count and rating only if accurate [DATA]. Under 250 words, reassuring and factual.`,
      tip: "A visible physical location and real contact details are strong trust signals for new stores.",
    },
    {
      c: "Reviews & Trust",
      t: "Checklist: Product Claims Compliance Review",
      u: "You want to check product copy before publishing.",
      p: `Review this product copy for risky claims: [PASTE COPY]. Flag: health or medical claims, environmental claims (FTC Green Guides), 'made in' claims (FTC Made in USA rule), reference prices, superlatives without support, and implied endorsements. For each, explain the risk and suggest a safer version. List what evidence we would need to keep each claim.`,
      tip: "Keep a claims file with the evidence behind every claim you make; regulators and platforms may ask.",
    },
    {
      c: "Reviews & Trust",
      t: "FAQ: Product FAQs From Real Questions",
      u: "Shoppers ask pre-purchase questions and you want answers on the page.",
      p: `Write 8 product FAQs for [PRODUCT] based on real customer questions [PASTE QUESTIONS FROM EMAILS, CHAT OR REVIEWS]. Answer each in 2 to 3 sentences using only the product facts [FACTS]. Mark any question we cannot answer from the facts as [NEED ANSWER].`,
      tip: "Every question a shopper has to email about is a sale at risk. Answer them on the page.",
    },
    {
      c: "Reviews & Trust",
      t: "Email: Handling a Product Recall or Safety Issue",
      u: "A product has a safety issue and customers must be told.",
      p: `Write a clear customer notice from [STORE NAME] about [ISSUE] affecting [PRODUCT, BATCH OR DATES]. Include: what the issue is and the risk in plain words, what customers should do now (stop using, how to identify affected items), the remedy [REFUND, REPLACEMENT, REPAIR], how to contact us, and an apology. Direct, calm, under 250 words. Follow any regulator requirements [CPSC OR OTHER].`,
      tip: "Speed and clarity protect customers and your reputation. Put the action in the first two sentences.",
    },

    // ── In-Store Retail & Merchandising ──
    {
      c: "In-Store Retail & Merchandising",
      t: "Signage: In-Store Signs and Shelf Talkers",
      u: "You want shelf signs that help customers choose and buy.",
      p: `Write 6 shelf talkers for [STORE NAME] for these products: [PRODUCTS AND KEY FACTS]. Each under 20 words: a benefit headline plus one supporting detail, and a staff-pick style for two of them [STAFF NAME IF ANY]. Plus 3 window or entrance signs for [PROMOTION OR SEASON] under 10 words each. ${CLAIMS}`,
      tip: "Staff-pick cards with a real name and one sentence on why consistently lift sales of that item.",
    },
    {
      c: "In-Store Retail & Merchandising",
      t: "Training: Sales Floor Conversation Guide",
      u: "Staff need to help customers without being pushy.",
      p: `Write a sales floor guide for staff at [STORE NAME], which sells [PRODUCTS]. Include: greeting within the first minute, 6 open questions to understand what the customer needs, how to recommend 2 or 3 options, suggesting a complementary item naturally [EXAMPLES], handling 'just looking', and closing politely. Short, practical, friendly.`,
      tip: "Teach questions, not scripts. Customers buy from staff who seem curious about them.",
    },
    {
      c: "In-Store Retail & Merchandising",
      t: "Plan: Seasonal Window and Display Plan",
      u: "You want displays that change with the season and drive traffic.",
      p: `Create a 12-month window and display plan for [STORE NAME] selling [PRODUCTS] in [LOCATION]. For each month: theme, hero products [OPTIONS], display idea, simple props, and a sign line. Note which months matter most for sales [PEAK MONTHS]. Table format.`,
      tip: "Change the window at least monthly; regulars stop seeing a window that never changes.",
    },
    {
      c: "In-Store Retail & Merchandising",
      t: "Event: In-Store Event Plan",
      u: "You want to host an event that brings people in and builds loyalty.",
      p: `Plan an in-store event for [STORE NAME]: [EVENT IDEA, e.g. product demo, workshop, late opening]. Include goal, date and timing, run of show, staffing, promotion plan (email, social, window, partners), offer or giveaway [IF ANY], how to capture contact details with consent, and follow-up afterwards. Budget: [BUDGET].`,
      tip: "Capture emails at the event with a reason to give them (a workshop recap, a guide). It turns one visit into a relationship.",
    },
    {
      c: "In-Store Retail & Merchandising",
      t: "SOP: Opening and Closing Procedures",
      u: "You want consistent opening and closing routines.",
      p: `Write opening and closing checklists for [STORE NAME]: cash and till procedures [POLICY], security, stock and shelves, cleanliness, displays, staff briefing, end-of-day reports, and alarm. Include who is responsible [ROLES] and checkboxes.`,
      tip: "A 5-minute staff briefing at opening (today's promotions, targets, deliveries) makes the whole day run better.",
    },
    {
      c: "In-Store Retail & Merchandising",
      t: "Loyalty: Designing a Simple Loyalty Program",
      u: "You want repeat customers and a reason to capture their details.",
      p: `Act as a retail consultant. Design a simple loyalty program for [STORE NAME] (in-store and online if both [CHANNELS]). Include: how customers earn and redeem [OUR GROSS MARGIN %], sign-up process with consent for marketing, costs and margin impact (show calculations), how staff introduce it at checkout, and how to measure success. Then write the customer description in under 100 words.`,
      tip: "Keep it simple enough to explain at the till in one sentence, or staff will not offer it.",
    },
    {
      c: "In-Store Retail & Merchandising",
      t: "Local: Partnership With Nearby Businesses",
      u: "You want to cross-promote with other local businesses.",
      p: `Write an outreach message from [STORE NAME] to [NEARBY BUSINESS TYPE] proposing a cross-promotion: [IDEA, e.g. shared discount, joint event, referral cards]. Explain the benefit to their customers and ours, what each side does, and suggest a short meeting. Under 150 words, friendly and local. Add 3 more partnership ideas.`,
      tip: "Pick partners whose customers overlap with yours but who do not compete, such as a cafe next to a bookshop.",
    },
    // ── Operations & Growth ──
    {
      c: "Operations & Growth",
      t: "Email: Supplier Negotiation",
      u: "You want better terms from a supplier.",
      p: `Write an email to [SUPPLIER] requesting better terms. Our history: [ORDER VOLUME, YEARS]. Request: [LOWER UNIT PRICE / BETTER PAYMENT TERMS / LOWER MOQ]. What we can offer: [LARGER ORDERS, COMMITMENT, FASTER PAYMENT]. Professional, collaborative, under 200 words, with a proposed call.`,
      tip: "Offer something in return. Suppliers move on price when you give them predictability.",
    },
    {
      c: "Operations & Growth",
      t: "Analysis: Monthly Store Performance Review",
      u: "You want to understand what drove this month's results.",
      p: `Analyse these monthly figures for [STORE NAME]: [SESSIONS, CONVERSION RATE, AOV, REVENUE, REPEAT PURCHASE RATE, AD SPEND, ROAS, RETURNS RATE, TOP PRODUCTS]. Compare with last month [FIGURES]. Explain the main drivers, flag concerns, and recommend 3 actions with expected impact. Show calculations and do not invent numbers.`,
      tip: "Break revenue into traffic x conversion x order value; it tells you which lever actually moved.",
    },
    {
      c: "Operations & Growth",
      t: "Plan: Inventory Reorder Plan",
      u: "You keep running out of best sellers and overstocking slow ones.",
      p: `Help me build a reorder plan. For each product: [SKU, MONTHLY SALES, LEAD TIME IN WEEKS, CURRENT STOCK, SAFETY STOCK WEEKS]. Calculate reorder points and suggested order quantities, flag products at risk of stockout and overstock, and explain the method so I can repeat it monthly. Show calculations in a table.`,
      tip: "Revisit lead times each quarter; supplier delays are what break most reorder plans.",
    },
    {
      c: "Operations & Growth",
      t: "SOP: Order Fulfilment Process",
      u: "Packing errors and delays are causing complaints.",
      p: `Write a fulfilment SOP for [STORE NAME]: order review, picking, quality check, packing standards (materials, inserts, branding [DETAILS]), labelling, carrier handoff times, exceptions (out of stock, address issues), and daily metrics. Numbered steps, with common errors to avoid.`,
      tip: "A final quality-check step before sealing the box eliminates most wrong-item complaints.",
    },
    {
      c: "Operations & Growth",
      t: "Strategy: Expanding to a New Marketplace",
      u: "You are thinking about selling on Amazon, Etsy, eBay or TikTok Shop.",
      p: `Act as an e-commerce strategist. My store: [PRODUCTS, PRICE RANGE, MARGINS, CURRENT CHANNELS, MONTHLY REVENUE]. Evaluate expanding to [MARKETPLACE]: fees and margin impact (show calculations with the fee rates I give or ask me to confirm current fees), fit for my products, operational needs, risks (channel conflict, dependency), and a 60-day test plan with success criteria.`,
      tip: "Test with your top 10 products first. Marketplaces reward focus, and fees change what is profitable.",
    },
    {
      c: "Operations & Growth",
      t: "Research: Competitor Analysis",
      u: "You want to understand how competitors position and price.",
      p: `Help me analyse competitors for [PRODUCT CATEGORY]. Here is information I collected from their sites: [PASTE PUBLIC INFO: PRICES, CLAIMS, SHIPPING, RETURNS, REVIEWS]. Build a comparison table, identify gaps and opportunities for [MY STORE], and suggest 3 ways to differentiate. Do not invent facts about competitors.`,
      tip: "Read competitors' 3-star reviews. They reveal what customers wish existed.",
    },
    {
      c: "Operations & Growth",
      t: "Power Prompt: 90-Day Growth Plan for an Online Store",
      u: "You want a focused plan to grow revenue this quarter.",
      p: `Act as an e-commerce growth consultant. My store: [PRODUCTS, CUSTOMER, MONTHLY REVENUE, TRAFFIC SOURCES, CONVERSION RATE, AOV, REPEAT RATE, EMAIL LIST SIZE]. Identify the biggest growth lever, then build a 90-day plan across conversion, average order value, retention (email and SMS flows) and acquisition. Weekly actions, owners, and the 5 metrics to track. Prioritise by impact and effort.`,
      tip: "Fix conversion and retention before buying more traffic; paid growth on a leaky store is expensive.",
    },
  ],
};
