import type { IndustryPack } from "./define";

// Home services and trades: plumbers, electricians, HVAC, roofers, cleaners,
// landscapers, painters, general contractors. Licences, warranties and price
// promises appear only when the user supplies them.

const FACTS = "Only mention licences, insurance, warranties or price guarantees I have given you.";

export const HOME_SERVICES: IndustryPack = {
  id: "home-services",
  label: "Home services and trades",
  prompts: [
    // ── Quotes & Estimates ──
    {
      c: "Quotes & Estimates",
      t: "Estimate: Clear Written Quote From Job Notes",
      u: "You measured up a job and need a professional written quote the customer understands.",
      p: `Act as an experienced [TRADE] business owner. Turn my job notes into a written quote for a homeowner. Notes: [SCOPE, MATERIALS, LABOR, PRICE]. Sections: summary of the job in plain words, what is included, what is not included [EXCLUSIONS], price broken down [BREAKDOWN], timeline [START AND DURATION], payment terms [DEPOSIT AND SCHEDULE], how long the quote is valid [DAYS], and how to accept. ${FACTS} Clear, professional, under 400 words.`,
      tip: "A written 'not included' list prevents most disputes at the end of a job.",
    },
    {
      c: "Quotes & Estimates",
      t: "Options: Good, Better, Best Quote",
      u: "You want to offer choices so customers compare options, not competitors.",
      p: `Create a good, better, best quote for [JOB] for a homeowner. Good: [BASIC OPTION AND PRICE]. Better: [MID OPTION AND PRICE]. Best: [PREMIUM OPTION AND PRICE]. For each, explain in plain words what they get, how long it should last or what it improves [FACTS], and who it suits. Add a one-line recommendation for the most common choice. ${FACTS} Present as a simple table plus 3 sentences.`,
      tip: "Most customers pick the middle option. Make sure your 'better' option is the one you want to sell.",
    },
    {
      c: "Quotes & Estimates",
      t: "Follow-Up: Chasing an Unanswered Quote",
      u: "You sent a quote and heard nothing back.",
      p: `Write 3 follow-up messages for a quote sent on [DATE] for [JOB]. Message 1 (day 3, text): friendly check it arrived and offer to answer questions. Message 2 (day 7, email): one useful point that helps them decide [POINT, e.g. scheduling availability, material price changes]. Message 3 (day 14, text): a polite final check. Each under 90 words, no pressure. ${FACTS}`,
      tip: "Offer a specific start date in message 2. 'We can start the week of the 12th' moves people more than discounts.",
    },
    {
      c: "Quotes & Estimates",
      t: "Script: Explaining Why Your Price Is Higher",
      u: "A customer says a competitor is cheaper and you want to explain your value without trashing anyone.",
      p: `Write a short, respectful script for explaining our price for [JOB] compared with a lower quote. Our facts: [WHAT WE INCLUDE, MATERIALS, CREW, WARRANTY IF ANY, PERMITS, CLEANUP]. Include 4 questions the customer can ask any contractor to compare quotes fairly. No criticism of competitors. ${FACTS}`,
      tip: "Give customers the comparison questions in writing. It shows confidence and often wins the job.",
    },
    {
      c: "Quotes & Estimates",
      t: "Change Order: Written Change Order for Extra Work",
      u: "The customer wants something extra mid-job, or you found an unexpected problem.",
      p: `Write a change order for [JOB]. Change: [WHAT CHANGED AND WHY]. Added cost: [COST] or credit: [CREDIT]. Effect on timeline: [DAYS]. Include a line for customer approval and date, and a note that work on the change starts after approval. Plain words, under 180 words. Add a short text message to send with it.`,
      tip: "Never start extra work on a verbal yes. A signed change order is the difference between getting paid and arguing.",
    },
    {
      c: "Quotes & Estimates",
      t: "Pricing: Calculate a Profitable Job Price",
      u: "You want to check a job is priced to make money, not just cover costs.",
      p: `Act as a trades business coach. Help me price [JOB]. Costs: materials [COST], labor hours [HOURS] at [HOURLY COST INCLUDING TAXES AND BENEFITS], subcontractors [COST], equipment and disposal [COST], travel [COST]. My overhead is [MONTHLY OVERHEAD] and I bill about [BILLABLE HOURS PER MONTH]. Target net profit: [PERCENT]. Show the calculation step by step: direct costs, overhead per job, profit, final price, and the difference between markup and margin.`,
      tip: "Confusing markup with margin is the most common reason trades businesses stay busy and broke.",
    },
    {
      c: "Quotes & Estimates",
      t: "Checklist: Site Visit Questions Before Quoting",
      u: "You want to gather everything on the first visit so quotes are accurate.",
      p: `Create a site visit checklist for quoting [TYPE OF JOB]. Include: what to measure and photograph, access and parking, condition of existing systems or surfaces, permits and HOA rules [IF APPLICABLE], customer's priorities and budget range, timing constraints, pets and occupants, and questions that uncover hidden problems. One page, checkbox format.`,
      tip: "Photograph everything, even what you are not quoting. It settles 'that was already damaged' disputes.",
    },

    // ── Customer Communication & Scheduling ──
    {
      c: "Customer Communication & Scheduling",
      t: "Text: Appointment Confirmation and Arrival Window",
      u: "You want fewer no-access visits and calls asking when you will arrive.",
      p: `Write a text sequence for [BUSINESS NAME]: booking confirmation with date and arrival window [WINDOW], a reminder the day before with what the customer needs to do [PREP, e.g. clear access, pets secured], and an on-the-way text with the technician's name [NAME] and ETA. Each under 160 characters. Friendly and clear.`,
      tip: "The on-the-way text with the technician's name is what customers mention most in positive reviews.",
    },
    {
      c: "Customer Communication & Scheduling",
      t: "Text: Running Late Message",
      u: "A job overran and the next customer needs to know.",
      p: `Write two short texts for when a technician from [BUSINESS NAME] is running late: one for a delay under an hour [NEW ETA] and one when we need to reschedule [OPTIONS]. Apologise once, give a real time, and offer a choice. Under 160 characters each.`,
      tip: "Text before the window starts. Customers forgive late technicians; they do not forgive silence.",
    },
    {
      c: "Customer Communication & Scheduling",
      t: "Email: Job Completion Summary",
      u: "You finished a job and want to leave a professional record for the customer.",
      p: `Write a job completion email from [BUSINESS NAME]. Work completed: [WORK]. Parts or materials used: [MATERIALS]. Anything we noticed that needs attention later [OBSERVATIONS]. Care instructions [INSTRUCTIONS]. Warranty details [ONLY IF WE OFFER ONE]. Invoice and payment [DETAILS]. Include a thank you and a review request [LINK]. Under 250 words. ${FACTS}`,
      tip: "Mentioning future issues you spotted, without pressure, builds trust and brings repeat work.",
    },
    {
      c: "Customer Communication & Scheduling",
      t: "Guide: What to Expect During the Project",
      u: "A bigger job starts soon and the homeowner is nervous about disruption.",
      p: `Write a 'what to expect' guide for a [PROJECT TYPE] by [BUSINESS NAME]. Include: start date and working hours [HOURS], daily routine (arrival, breaks, cleanup), noise, dust and utilities shutoffs [DETAILS], what the homeowner needs to do, who the point of contact is [NAME, PHONE], how changes are handled (change orders), and what happens at the end (walkthrough, final payment). Friendly, under 500 words.`,
      tip: "Send this with the deposit receipt. It reduces anxious calls during the first week.",
    },
    {
      c: "Customer Communication & Scheduling",
      t: "Script: Phone Booking Script for the Office",
      u: "Calls are handled differently by everyone and bookings get missed.",
      p: `Write a phone script for the office at [BUSINESS NAME], a [TRADE] company. Include greeting, questions to understand the problem [KEY QUESTIONS], how to judge urgency [EMERGENCY CRITERIA], booking the visit and arrival window, service call fee explanation [FEE], and a friendly close. Add responses for 'How much will it cost?' and 'Can you come today?'.`,
      tip: "Train staff to explain the service call fee before booking. Surprises at the door create bad reviews.",
    },
    {
      c: "Customer Communication & Scheduling",
      t: "Message: Weather Delay Notice",
      u: "Weather is delaying outdoor work and several customers need updates.",
      p: `Write a message to customers of [BUSINESS NAME] whose [OUTDOOR WORK, e.g. roofing, landscaping] is delayed by weather on [DATES]. Explain briefly why we do not work in these conditions (quality and safety), the new plan [NEW DATES OR HOW WE WILL RESCHEDULE], and how to reach us. Under 120 words, calm and professional.`,
      tip: "Explain the quality reason. Customers accept delays that protect their property.",
    },
    {
      c: "Customer Communication & Scheduling",
      t: "Email: Seasonal Maintenance Reminder",
      u: "You want past customers to book seasonal maintenance.",
      p: `Write a seasonal reminder email from [BUSINESS NAME] for [SERVICE, e.g. furnace tune-up, gutter cleaning, AC check] before [SEASON]. Include 3 reasons it matters in plain words, what the visit includes [CHECKLIST], price [PRICE], booking link [LINK], and limited scheduling windows if true [WINDOWS]. Under 180 words. Include unsubscribe and business address.`,
      tip: "Send it 4 to 6 weeks before the season; that fills your calendar before the rush.",
    },

    // ── Reviews & Reputation ──
    {
      c: "Reviews & Reputation",
      t: "Request: Review Request That Gets Results",
      u: "Happy customers rarely leave reviews unless asked well.",
      p: `Write a review request text and email for [BUSINESS NAME] after [JOB TYPE]. Mention the technician by name [NAME], keep it personal and short, include the link [LINK], and suggest they mention what they valued (without telling them what to write). Ask every customer, no incentives. Text under 160 characters, email under 90 words.`,
      tip: "Ask on the day the job is finished, ideally while the technician is still there.",
    },
    {
      c: "Reviews & Reputation",
      t: "Reply: Responding to a Negative Review",
      u: "A customer left a bad review and you want to respond professionally.",
      p: `Write a public reply from the owner of [BUSINESS NAME] to this review: [PASTE REVIEW]. Our side of the facts, for context only: [FACTS]. Thank them, acknowledge the frustration, state briefly what we do to fix things, and invite them to call [NAME, NUMBER]. No arguing, no customer personal details, under 90 words.`,
      tip: "Future customers read your reply more than the review. Calm and helpful wins them over.",
    },
    {
      c: "Reviews & Reputation",
      t: "Reply: Thanking Positive Reviews",
      u: "You want to reply to good reviews without sounding copy-pasted.",
      p: `Write 6 varied replies to positive reviews for [BUSINESS NAME], a [TRADE] company. Each should thank the customer, mention something specific I can fill in [DETAIL FROM THE REVIEW], and invite them back or mention a related service naturally. Under 50 words each, warm and human.`,
      tip: "Mentioning the service in the reply (for example 'water heater replacement') also helps local search.",
    },
    {
      c: "Reviews & Reputation",
      t: "Showcase: Before-and-After Project Post",
      u: "You finished a project and want to show it off on social media and your website.",
      p: `Write a before-and-after project post for [BUSINESS NAME]. Project: [PROJECT] in [NEIGHBORHOOD OR CITY]. The problem: [PROBLEM]. What we did: [WORK]. Result: [RESULT]. Customer permission to share photos: [CONFIRMED]. Write a social caption under 100 words, a website project description under 200 words, and alt text for the photos. No customer names or addresses.`,
      tip: "Real local projects are your best marketing. Ask permission to photograph at the start of the job.",
    },
    {
      c: "Reviews & Reputation",
      t: "Script: Handling a Customer Complaint on Site",
      u: "A customer is unhappy with the work and the technician is on site.",
      p: `Write a guide for technicians at [BUSINESS NAME] when a customer is unhappy on site. Steps: listen without interrupting, repeat back the concern, check the work together, what the technician can fix on the spot, when to call the office [ROLE], and how to leave things (clear next step and time). Add 6 phrases to use and 4 to avoid.`,
      tip: "Give technicians authority to fix small issues on the spot. It turns complaints into five-star reviews.",
    },
    {
      c: "Reviews & Reputation",
      t: "Plan: Monthly Reputation Routine",
      u: "You want a simple routine to keep reviews coming and respond to all of them.",
      p: `Create a monthly reputation routine for [BUSINESS NAME]: who sends review requests and when, how to respond to reviews within 48 hours, monthly review count and rating targets [TARGETS], how to share reviews with the team, and how to use reviews on the website and quotes. One page.`,
      tip: "Celebrate named reviews with the crew. Technicians who see praise for good work repeat it.",
    },
    {
      c: "Reviews & Reputation",
      t: "Case Study: Customer Story for the Website",
      u: "You want a detailed customer story to show how you work.",
      p: `Write a customer story for [BUSINESS NAME]'s website from these facts: customer type [e.g. family, landlord] in [AREA], the problem [PROBLEM], why they chose us [REASON], the work [WORK], challenges [CHALLENGES], and the result [RESULT]. 300 to 400 words, factual, with a short customer quote only if they approved it [QUOTE]. No invented numbers.`,
      tip: "Stories about solving a tricky problem persuade more than stories about easy jobs.",
    },

    // ── Marketing & Local Search ──
    {
      c: "Marketing & Local Search",
      t: "Profile: Google Business Profile Description",
      u: "Your Google Business Profile description is empty or weak.",
      p: `Write a Google Business Profile description for [BUSINESS NAME], a [TRADE] company serving [AREAS]. Include services [SERVICES], what makes us different (facts: [YEARS, LICENSED IF TRUE, SAME-DAY SERVICE, WARRANTY IF ANY]), and how to book. Under 750 characters, natural language with the key services and town names. ${FACTS}`,
      tip: "Use the words customers search ('emergency plumber in Mesa'), not trade jargon.",
    },
    {
      c: "Marketing & Local Search",
      t: "Website: Service Area Page for a Town",
      u: "You want to rank in nearby towns without copy-pasting the same page.",
      p: `Write a website page for [SERVICE] in [TOWN]. Include local details that are genuinely true [LOCAL FACTS, e.g. common housing age, local water hardness, HOA rules], jobs we have done there [PROJECTS IF ANY], response time to that area [TIME], and how to book. 400 to 500 words, unique, no invented local facts. ${FACTS}`,
      tip: "Pages with real local projects outrank generic 'city' pages. Add a project photo from that town.",
    },
    {
      c: "Marketing & Local Search",
      t: "Social: Month of Posts for a Trades Business",
      u: "You want to post regularly but have no time to think of ideas.",
      p: `Create 12 social media posts for [BUSINESS NAME], a [TRADE] company in [CITY]: 4 tips homeowners can use, 3 project showcases [PROJECTS], 2 team introductions [TEAM], 2 seasonal reminders, and 1 myth vs fact. Each caption under 70 words with a photo idea and a call to action. Friendly and practical.`,
      tip: "Tips that save homeowners money get shared; showcases get calls. Mix both.",
    },
    {
      c: "Marketing & Local Search",
      t: "Flyer: Door Hanger for Neighbours of a Job",
      u: "You are working on a street and want to reach the neighbours.",
      p: `Write a door hanger for [BUSINESS NAME] to leave on neighbouring homes while we work on [JOB TYPE] nearby. Include a friendly note that we are working in the neighbourhood, one relevant tip or check [TIP], an offer if we have one [OFFER], and contact details. Under 80 words, not pushy.`,
      tip: "Neighbours often have the same age of house and the same problems. This is some of the cheapest marketing there is.",
    },
    {
      c: "Marketing & Local Search",
      t: "Ad: Local Service Ads Copy",
      u: "You are running Google or Facebook ads for your service area.",
      p: `Write 5 ad variations for [BUSINESS NAME] offering [SERVICE] in [AREA]. Each with a headline under 30 characters, a description under 90 characters, and a call to action. Use real differentiators [FACTS]. No 'lowest prices guaranteed' or unsupported claims. Add 10 keyword ideas including emergency and 'near me' variations. ${FACTS}`,
      tip: "Emergency keywords cost more and convert far better. Only bid on them if you really answer at night.",
    },
    {
      c: "Marketing & Local Search",
      t: "Email: Referral Program Launch",
      u: "You want past customers to refer friends and family.",
      p: `Write an email launching a referral program for [BUSINESS NAME]. How it works: [REWARD, e.g. a $50 credit for both]. How to refer [HOW]. Terms in plain words [TERMS]. Friendly, under 150 words, with a thank-you to past customers. Include unsubscribe and address lines.`,
      tip: "Rewarding both people works better than rewarding only the referrer; nobody feels awkward recommending.",
    },
    {
      c: "Marketing & Local Search",
      t: "Partnership: Pitch to Property Managers or Realtors",
      u: "You want steady work from property managers or realtors.",
      p: `Write an email from [BUSINESS NAME] to [PROPERTY MANAGERS / REALTORS] in [AREA]. Offer: [SERVICES], response time [TIME], how we handle tenant or buyer access, invoicing and photos for their records, and [COI AVAILABLE IF TRUE]. Suggest a short call. Under 170 words, professional and specific. ${FACTS}`,
      tip: "Property managers value reliability and photos over price. Lead with how easy you make their job.",
    },

    // ── Crew & Job Site Management ──
    {
      c: "Crew & Job Site Management",
      t: "Checklist: Daily Job Site Checklist",
      u: "You want every crew to start and finish the day the same way.",
      p: `Create a daily job site checklist for [TRADE] crews at [BUSINESS NAME]: arrival (introduce to customer, protect floors and surfaces), safety checks [SAFETY ITEMS], work photos, customer update midday, end-of-day cleanup, securing the site, and what to report to the office. Checkbox format, one page.`,
      tip: "Before, during and after photos protect you in disputes and feed your marketing.",
    },
    {
      c: "Crew & Job Site Management",
      t: "Training: Customer Etiquette Guide for Technicians",
      u: "Your technicians are skilled but customer experience varies.",
      p: `Write a customer etiquette guide for technicians at [BUSINESS NAME]. Cover: arriving and introducing yourself, shoe covers and protecting the home, explaining the problem in plain words, getting approval before extra work, phone use, cleanliness, and leaving (walk the customer through the work). Include 5 do and don't examples. Practical, respectful tone.`,
      tip: "Role-play the 'explain the problem' step. Customers trust technicians who explain without jargon.",
    },
    {
      c: "Crew & Job Site Management",
      t: "Safety: Toolbox Talk Script",
      u: "You hold short safety talks and need fresh topics.",
      p: `Write a 5-minute toolbox talk for a [TRADE] crew on [TOPIC, e.g. ladder safety, heat illness, electrical lockout]. Include why it matters, 4 key practices, a quick real-world example (no names), 2 questions to ask the crew, and a sign-off line for the attendance log. Plain, direct language. Check against OSHA guidance for [TOPIC].`,
      tip: "Rotate who leads the talk. Crews listen more to each other than to the office.",
    },
    {
      c: "Crew & Job Site Management",
      t: "Hiring: Job Post for a Technician",
      u: "You need to hire a skilled technician or apprentice.",
      p: `Write a job post for a [ROLE, e.g. HVAC technician, apprentice electrician] at [BUSINESS NAME] in [AREA]. Include: what the work involves, required skills and licences [REQUIREMENTS], tools or vehicle provided [DETAILS], schedule and on-call [DETAILS], pay range [RANGE] and benefits [BENEFITS], training and growth, and how to apply. Inclusive wording, under 350 words.`,
      tip: "Mention training and a clear path to higher pay. Good technicians leave for growth more than money.",
    },
    {
      c: "Crew & Job Site Management",
      t: "Onboarding: First Week Plan for a New Hire",
      u: "A new technician starts Monday.",
      p: `Create a first-week plan for a new [ROLE] at [BUSINESS NAME]: paperwork and safety training, tools and vehicle, shadowing a senior tech, company standards (customer etiquette, photos, paperwork), first supervised jobs, and a Friday check-in with questions. Include a 30-day skills checklist.`,
      tip: "Pair new hires with your best technician, not your least busy one.",
    },
    {
      c: "Crew & Job Site Management",
      t: "Script: Performance Conversation With a Crew Member",
      u: "A crew member keeps making the same mistake and you need to address it.",
      p: `Write a guide for a performance conversation with a crew member about [ISSUE, e.g. lateness, callbacks, cleanup]. Include: how to open, specific examples [EXAMPLES], asking for their side, agreeing clear expectations and support, a follow-up date, and how to document it. Direct and respectful, no threats.`,
      tip: "Talk about one issue at a time with specific examples. General complaints change nothing.",
    },
    {
      c: "Crew & Job Site Management",
      t: "SOP: Callback and Warranty Visit Process",
      u: "Callbacks cost money and you want to handle and reduce them.",
      p: `Write a callback process for [BUSINESS NAME]: how callbacks are logged, how quickly we respond [TIME], who goes (ideally the original tech), how to decide if it is covered [OUR POLICY], how the result is recorded, and a monthly review of callback causes. Include a simple callback log template.`,
      tip: "Review callback causes monthly. A pattern usually points to one process or one part.",
    },

    // ── Difficult Customers & Disputes ──
    {
      c: "Difficult Customers & Disputes",
      t: "Email: Customer Refusing to Pay Final Invoice",
      u: "The job is done and the customer is withholding payment.",
      p: `Write a firm, professional email to a customer who has not paid the final invoice of [AMOUNT] for [JOB], completed on [DATE]. Their stated concern [CONCERN]. Summarise what was agreed [QUOTE OR CONTRACT], what was delivered, our offer to resolve the concern [OFFER], and the payment deadline [DATE]. Mention next steps under the contract [NEXT STEPS] without threats. Under 220 words.`,
      tip: "Separate the concern from the payment: fix what is fair, then ask for payment on what is undisputed.",
    },
    {
      c: "Difficult Customers & Disputes",
      t: "Script: Saying No to Unreasonable Requests",
      u: "A customer keeps asking for extras at no charge.",
      p: `Write short, friendly scripts for saying no to a customer who asks for [REQUEST, e.g. extra work thrown in, a discount after agreeing the price]. Include 3 options: offer a paid change order, offer a smaller goodwill gesture [IF WE CHOOSE], or explain what is included. Warm and firm, under 60 words each.`,
      tip: "Say what you can do before what you cannot. It keeps the relationship intact.",
    },
    {
      c: "Difficult Customers & Disputes",
      t: "Letter: Documenting a Dispute",
      u: "A disagreement may escalate and you want a clear written record.",
      p: `Write a factual letter from [BUSINESS NAME] to a customer documenting a dispute about [JOB]. Include: dates, what was agreed (quote, change orders), what was done, the customer's concern, what we offered, and our proposed resolution [RESOLUTION]. Neutral, factual, no emotion, under 300 words.`,
      tip: "Write it as if a judge will read it. Calm documentation wins disputes.",
    },
    {
      c: "Difficult Customers & Disputes",
      t: "Script: Delivering Bad News About Hidden Damage",
      u: "You opened a wall or roof and found a bigger problem.",
      p: `Write a script and a follow-up text for telling a homeowner we found [HIDDEN PROBLEM] during [JOB]. Include: showing them (photos), explaining what it means in plain words, options with prices [OPTIONS], what happens if they wait, and that we will not proceed without approval. Calm and honest, no pressure.`,
      tip: "Show the photo before the price. People accept costs for problems they can see.",
    },
    {
      c: "Difficult Customers & Disputes",
      t: "Guide: Firing a Customer Politely",
      u: "A customer is abusive or impossible and you want to end the relationship.",
      p: `Write a polite message ending our work with a customer of [BUSINESS NAME]. Reason in neutral terms [REASON]. Include how we will finish or hand over current work [PLAN], final invoice [DETAILS], and a courteous close. Under 150 words, no blame, no emotion.`,
      tip: "Keep it short and neutral. Explaining at length invites argument.",
    },
    {
      c: "Difficult Customers & Disputes",
      t: "Terms: Plain-Language Terms and Conditions",
      u: "You want written terms that prevent common disputes.",
      p: `Draft plain-language terms and conditions for [BUSINESS NAME], a [TRADE] company, covering: quotes and validity, deposits and payment, change orders, access and customer responsibilities, delays outside our control, cleanup, warranty [OUR POLICY], cancellation, and disputes. Under 700 words. For review by a local attorney before use.`,
      tip: "Clear terms signed at the start prevent most arguments at the end.",
    },
    {
      c: "Difficult Customers & Disputes",
      t: "Email: Responding to a Chargeback or Payment Dispute",
      u: "A customer disputed a card payment with their bank.",
      p: `Write a response for a card payment dispute from [BUSINESS NAME] about [JOB] for [AMOUNT]. Include: summary of the agreement, dates of work, evidence available (signed quote, photos, completion confirmation, communications) [EVIDENCE], and a clear, factual statement that the service was delivered. Professional, under 250 words.`,
      tip: "Chargebacks are won with documents. Signed quotes and dated photos matter most.",
    },

    // ── Permits, Compliance & Paperwork ──
    {
      c: "Permits, Compliance & Paperwork",
      t: "Explainer: Why This Job Needs a Permit",
      u: "A customer wants to skip the permit to save money and you need to explain why it matters.",
      p: `Write a short, friendly explanation for a homeowner about why [JOB] in [CITY/COUNTY] needs a permit. Cover in plain words: safety, inspections, insurance claims, and selling the home later. Include the permit cost and timeline if I know it [COST, TIMELINE], and what we handle for them. Under 170 words. Do not state specific code requirements unless I provide them [CODE NOTES].`,
      tip: "Mention home sale inspections. Unpermitted work often surfaces exactly when the owner wants to sell.",
    },
    {
      c: "Permits, Compliance & Paperwork",
      t: "Checklist: Permit Application Prep",
      u: "You want permit applications right the first time.",
      p: `Create a permit application prep checklist for [JOB TYPE] in [JURISDICTION]: documents and drawings needed [KNOWN REQUIREMENTS], homeowner authorisations, contractor licence and insurance documents, fees, inspection scheduling, and who in the office owns each step. Mark anything that varies locally as [CHECK WITH BUILDING DEPARTMENT].`,
      tip: "Keep a folder per jurisdiction with past approved applications; reuse beats starting fresh.",
    },
    {
      c: "Permits, Compliance & Paperwork",
      t: "Template: Lien Waiver and Payment Paperwork Explainer",
      u: "Customers or general contractors ask about lien waivers and you want to explain clearly.",
      p: `Write a plain-language explainer for [CUSTOMERS / GENERAL CONTRACTORS] about lien waivers on our jobs in [STATE]: what a lien waiver is, conditional versus unconditional, when we provide them in our payment process [OUR PROCESS], and what we need from them. Under 250 words. Add a note that state lien laws vary and they can ask their attorney.`,
      tip: "Offer conditional waivers with each invoice. It speeds payment from GCs and lenders.",
    },
    {
      c: "Permits, Compliance & Paperwork",
      t: "Checklist: Subcontractor Onboarding Documents",
      u: "You use subcontractors and want the right paperwork before they start.",
      p: `Create a subcontractor onboarding checklist for [BUSINESS NAME]: signed agreement, certificate of insurance with required limits [LIMITS] and additional insured status, licence verification, W-9, safety expectations, payment terms, and job site standards. Include a short email template requesting these documents.`,
      tip: "Uninsured subcontractors are a big risk in insurance audits and in claims. Collect certificates before day one.",
    },
    {
      c: "Permits, Compliance & Paperwork",
      t: "Guide: Lead-Safe Work Practices Notice",
      u: "You work on older homes and must follow lead-safe rules.",
      p: `Write a customer-facing notice for renovation work on a home built before 1978, explaining in plain words that we follow lead-safe work practices under the EPA Renovation, Repair and Painting (RRP) Rule: what that means on site (containment, cleanup, verification), what the homeowner should do (keep children and pets away), and that they will receive the 'Renovate Right' pamphlet. Under 250 words. Our certification details: [FIRM CERTIFICATION NUMBER].`,
      tip: "Keep signed pamphlet receipts on file for every pre-1978 job; they are required records under the RRP Rule.",
    },
    {
      c: "Permits, Compliance & Paperwork",
      t: "Template: Job Completion and Sign-Off Form",
      u: "You want a clean sign-off at the end of each job.",
      p: `Create a job completion sign-off form for [BUSINESS NAME]: job details, work completed, materials used, photos taken (yes/no), customer walkthrough done, outstanding items [IF ANY], warranty information [OUR POLICY], and signature lines for customer and technician with date. One page, simple language.`,
      tip: "A signed completion form is your strongest evidence if a payment is disputed later.",
    },
    {
      c: "Permits, Compliance & Paperwork",
      t: "Policy: Photo and Documentation Standards",
      u: "Documentation is inconsistent and you want every job recorded properly.",
      p: `Write a documentation standard for technicians at [BUSINESS NAME]: which photos to take (before, hidden conditions, during, after, serial numbers), how to name and upload them [SYSTEM], notes to write, customer signatures needed, and deadlines for completing paperwork. Include why it matters (disputes, warranty claims, marketing). One page.`,
      tip: "Photos of hidden conditions (inside walls, under floors) are gold in disputes and warranty claims.",
    },
    // ── Business Operations & Growth ──
    {
      c: "Business Operations & Growth",
      t: "Plan: Maintenance Membership Program",
      u: "You want recurring revenue and loyal customers through a maintenance plan.",
      p: `Act as a trades business consultant. Design a maintenance membership for [BUSINESS NAME], a [TRADE] company. Include: what members get [VISITS, PRIORITY, DISCOUNTS], a monthly and annual price with the reasoning [COSTS TO COVER], how to sell it on every call, renewal reminders, and how to measure it. Then write a one-paragraph customer description of the plan.`,
      tip: "Offer the membership at the end of every service call; technicians sell it best.",
    },
    {
      c: "Business Operations & Growth",
      t: "Analysis: Monthly Numbers Review",
      u: "You want to understand your month beyond the bank balance.",
      p: `Review these monthly numbers for [BUSINESS NAME]: [REVENUE, JOBS, AVERAGE TICKET, CLOSE RATE, CALLBACKS, MATERIALS, LABOR, OVERHEAD]. Calculate gross margin and net profit, compare with last month [LAST MONTH FIGURES], identify the 3 biggest issues or wins, and suggest 3 actions. Show the calculations; do not invent numbers.`,
      tip: "Average ticket and close rate usually move profit more than job count.",
    },
    {
      c: "Business Operations & Growth",
      t: "SOP: Standard Process for a Common Job",
      u: "You want every crew to do a common job the same, high-quality way.",
      p: `Write a standard operating procedure for [COMMON JOB] at [BUSINESS NAME]. Include: tools and materials list, prep steps, step-by-step work process, quality checks, cleanup, photos to take, and what to tell the customer at the end. Numbered, clear enough for a new technician.`,
      tip: "Write SOPs with your best technician. Their shortcuts are often the quality standard.",
    },
    {
      c: "Business Operations & Growth",
      t: "Plan: Hiring an Office Manager",
      u: "You are on the tools all day and the office is falling behind.",
      p: `Help me plan hiring an office manager for [BUSINESS NAME]. Current office tasks [TASKS] and hours they take [HOURS]. Produce: a role description, what to hand over first, tools needed [SOFTWARE], a job post draft, interview questions, and a 30-day handover plan.`,
      tip: "Track your office hours for two weeks first. It shows exactly what the role is worth.",
    },
    {
      c: "Business Operations & Growth",
      t: "Guide: Choosing Field Service Software",
      u: "You are drowning in paper and want scheduling and invoicing software.",
      p: `Act as an operations advisor for trades businesses. My business: [TRADE, CREW SIZE, JOBS PER WEEK]. Current tools: [TOOLS]. Must-haves: [NEEDS, e.g. scheduling, quotes, invoicing, payments, photos]. Create a comparison checklist and questions to ask vendors, what to test in a trial, a migration plan, and how to get the crew to use it. Do not recommend a specific product without the criteria.`,
      tip: "Trial with your least tech-savvy technician. If they can use it, everyone can.",
    },
    {
      c: "Business Operations & Growth",
      t: "Plan: Handling the Busy Season",
      u: "Your peak season is coming and last year was chaos.",
      p: `Create a busy-season plan for [BUSINESS NAME] for [SEASON]. Include: staffing and overtime plan, scheduling rules (emergencies vs routine), stocking common parts [PARTS], customer communication templates for longer waits, extra help (subcontractors, office), and a weekly review. Practical and specific.`,
      tip: "Stock the ten parts you ran out of last season before the rush starts.",
    },
    {
      c: "Business Operations & Growth",
      t: "Power Prompt: Build a 12-Month Growth Plan",
      u: "You want a clear plan to grow the business this year.",
      p: `Act as a business coach for trades companies. My business: [TRADE, AREA, REVENUE, CREW, SERVICES]. Goals: [GOALS]. Build a 12-month plan: pricing review, marketing (reviews, local search, referrals, partners), memberships or maintenance plans, hiring, systems, and cash flow. Give quarterly priorities, monthly actions, and 6 numbers to track.`,
      tip: "Pick one quarterly priority and finish it. Most trades plans fail from trying to fix everything at once.",
    },
  ],
};
