import type { IndustryPack } from "./define";

// Insurance agencies. Nothing here overstates coverage or guarantees price,
// approval or savings; explanations point back to the policy terms.

const POLICY = "Do not overstate coverage or guarantee price, approval or savings; say that coverage depends on the policy terms, conditions and exclusions.";

export const INSURANCE: IndustryPack = {
  id: "insurance",
  label: "Insurance agency",
  prompts: [
    // ── Prospecting & Lead Follow-Up ──
    {
      c: "Prospecting & Lead Follow-Up",
      t: "Email: First Reply to an Online Quote Request",
      u: "A new lead requested a quote online and you want to respond fast and personally.",
      p: `Act as a licensed [LINE, e.g. personal lines, commercial] insurance agent at [AGENCY NAME]. Write a first reply to a lead named [FIRST NAME] who requested a quote for [COVERAGE TYPE]. Thank them, list the 4 or 5 details I need to quote accurately [DETAILS NEEDED], explain what happens next and how long it takes [TIMEFRAME], and offer a 10-minute call [TIMES]. Under 170 words, warm and specific. ${POLICY}`,
      tip: "Reply within 5 minutes during business hours. Speed to lead is the biggest factor in who wins the quote.",
    },
    {
      c: "Prospecting & Lead Follow-Up",
      t: "Sequence: Follow-Up for a Quote Not Yet Accepted",
      u: "You sent a quote and the prospect went quiet.",
      p: `Write a 4-touch follow-up sequence for a prospect who received a [COVERAGE TYPE] quote on [DATE] and has not replied. Touch 1 (day 2): check they received it and offer to walk through it. Touch 2 (day 5): one useful point about the coverage they may have missed [POINT]. Touch 3 (day 10): ask if anything changed or if price or coverage is the concern. Touch 4 (day 20): a polite close-the-loop message. Each under 110 words. ${POLICY}`,
      tip: "The break-up message in touch 4 often gets the most replies. People answer when you stop chasing.",
    },
    {
      c: "Prospecting & Lead Follow-Up",
      t: "Script: Cold Call Opener for Commercial Prospects",
      u: "You are calling local businesses and need an opener that earns 30 seconds.",
      p: `Act as a commercial insurance agent. Write a cold call opener for [BUSINESS TYPE] owners in [AREA]. Include: a permission-based opening, one relevant risk or change for their industry [RISK OR CHANGE], a question that invites them to talk about their current coverage, and a low-pressure ask for a coverage review. Add responses to 'I already have an agent', 'Not interested' and 'Send me something'. Natural, not pushy. Comply with do-not-call rules.`,
      tip: "Ask about their business before insurance. Owners talk about their business; they avoid talking about policies.",
    },
    {
      c: "Prospecting & Lead Follow-Up",
      t: "Email: Referral Partner Introduction",
      u: "You want referrals from realtors, mortgage brokers, car dealers or accountants.",
      p: `Write an introduction email from [AGENT NAME] at [AGENCY] to a [PARTNER TYPE] in [AREA]. Explain how I help their clients [HOW, e.g. fast homeowner's binders for closings], my turnaround time [TIME], how referrals would work, and suggest coffee or a call. Under 160 words, collaborative. Do not offer payment for referrals unless permitted in [STATE].`,
      tip: "Reliability wins partners. Promise a turnaround time and beat it on the first referral.",
    },
    {
      c: "Prospecting & Lead Follow-Up",
      t: "Social Post: Life Event Coverage Reminder",
      u: "You want posts that remind people to review coverage after life events.",
      p: `Write 5 short social posts for [AGENCY NAME] about reviewing insurance after life events: new home, new baby, new driver in the family, starting a business, retirement. Each under 60 words with a question, a practical point, and a call to action [HOW TO CONTACT]. ${POLICY} No fear-based language.`,
      tip: "Life events are when people are actually ready to talk about insurance. Time your content to them.",
    },
    {
      c: "Prospecting & Lead Follow-Up",
      t: "Script: Quoting Call Discovery Questions",
      u: "You want to gather the right information on the first call and build trust.",
      p: `Act as an experienced [LINE] agent. Write a discovery question list for a first quoting call about [COVERAGE TYPE]. Group questions: current coverage and carrier, what they want to protect, recent changes, budget and deductible preferences, claims history, and concerns. Add 3 questions that uncover gaps they may not know about. Conversational wording.`,
      tip: "Ask 'What would worry you most if something happened?' The answer shapes the whole recommendation.",
    },
    {
      c: "Prospecting & Lead Follow-Up",
      t: "Email: Reviving Old Leads",
      u: "You have a list of old leads that never bought and want to reopen conversations.",
      p: `Write a short, low-pressure email to leads who requested a [COVERAGE TYPE] quote more than [MONTHS] months ago and did not buy. Reason to reconnect: [REASON, e.g. rates changed, new carrier options, renewal season]. Offer a quick review [HOW]. Under 110 words, friendly, with an easy reply option. Include an unsubscribe line.`,
      tip: "Send at renewal time for the line they asked about. That is when shopping actually happens.",
    },

    // ── Policy Explanations for Clients ──
    {
      c: "Policy Explanations for Clients",
      t: "Explainer: What a Policy Covers in Plain Language",
      u: "A client does not understand their policy and you want a clear summary.",
      p: `Act as a licensed agent. Write a plain-language summary of a [POLICY TYPE] based on these key terms from the declarations and policy: [PASTE COVERAGES, LIMITS, DEDUCTIBLES, KEY EXCLUSIONS]. Sections: what is covered, the limits, what you pay before coverage (deductibles), important exclusions, and when to call us. Under 400 words, 8th-grade reading level. Use only the terms I provide. ${POLICY}`,
      tip: "Clients remember exclusions best when you give one real-life example of each.",
    },
    {
      c: "Policy Explanations for Clients",
      t: "Explainer: Deductibles, Limits and Premiums",
      u: "Clients confuse deductibles, limits and premiums.",
      p: `Write a simple explainer for clients of [AGENCY NAME] on the difference between a premium, a deductible, and a coverage limit, using one everyday example for [POLICY TYPE, e.g. auto, homeowners]. Then explain how raising or lowering the deductible usually affects the premium and when each choice makes sense. Under 300 words.`,
      tip: "Use real numbers in the example; abstract explanations do not stick.",
    },
    {
      c: "Policy Explanations for Clients",
      t: "Comparison: Two Quotes Side by Side",
      u: "A client has two options and needs to compare coverage, not just price.",
      p: `Create a side-by-side comparison of two [COVERAGE TYPE] quotes for a client. Quote A: [DETAILS]. Quote B: [DETAILS]. Table rows: premium, deductibles, key limits, notable coverages, exclusions or endorsements that differ, carrier service notes [IF KNOWN]. Then write 4 sentences on the main trade-offs in plain language. Do not choose for them. ${POLICY}`,
      tip: "Put the biggest coverage difference in bold above the table; clients look at price first otherwise.",
    },
    {
      c: "Policy Explanations for Clients",
      t: "Explainer: Why Premiums Went Up at Renewal",
      u: "A client's premium increased and they want to know why.",
      p: `Write a clear, honest explanation to a client whose [POLICY TYPE] premium increased from [OLD] to [NEW] at renewal. Known reasons: [REASONS, e.g. rising repair costs in the market, claims, rating changes]. Include what they can do: [OPTIONS, e.g. raise deductible, bundle, shop other carriers]. Under 220 words, empathetic, no blaming. Do not promise that shopping will lower the price.`,
      tip: "Contact clients before the renewal bill arrives. A surprise increase loses more clients than the increase itself.",
    },
    {
      c: "Policy Explanations for Clients",
      t: "Explainer: Commercial Coverage for a Small Business",
      u: "A small business owner asks what insurance they need.",
      p: `Act as a commercial lines agent. Write a plain-language guide for a [BUSINESS TYPE] owner about common coverages: general liability, property, business interruption, professional liability, workers' compensation (state requirements [STATE]), commercial auto, and cyber. For each: what it generally covers, typical situations for a business like theirs, and questions to ask. Note that needs vary and a review is recommended. ${POLICY}`,
      tip: "Tie each coverage to one concrete story from their industry; owners buy protection from risks they can picture.",
    },
    {
      c: "Policy Explanations for Clients",
      t: "Explainer: Life Insurance Options",
      u: "A client is new to life insurance and wants to understand the options.",
      p: `Write a plain-language explainer on term versus permanent life insurance for a client aged about [AGE RANGE] with [SITUATION, e.g. young children, mortgage]. Cover how each works in general, typical uses, cost differences in general terms, and questions to consider (how much, how long). No product recommendation, no projected returns, and a note that a needs analysis comes next. ${POLICY}`,
      tip: "Start with the needs conversation (who depends on you, for how long). The product choice follows naturally.",
    },
    {
      c: "Policy Explanations for Clients",
      t: "FAQ: Common Coverage Questions",
      u: "You get the same coverage questions and want a clear FAQ for your website.",
      p: `Write 10 FAQs for [AGENCY NAME] on [LINE, e.g. homeowners insurance] in [STATE]. Use real questions clients ask [LIST IF KNOWN]. Answer each in 3 to 4 plain sentences with general information and when to talk to an agent. ${POLICY} Add a line that answers are general and the policy terms control.`,
      tip: "FAQs that match real search questions bring in local leads for years.",
    },

    // ── Renewals & Retention ──
    {
      c: "Renewals & Retention",
      t: "Email: Pre-Renewal Review Invitation",
      u: "A policy renews in 60 days and you want to review it with the client first.",
      p: `Write an email to a client whose [POLICY TYPE] renews on [DATE], inviting a short review. Mention what we will check (changes in their life or business, coverage gaps, deductible options, discounts [DISCOUNTS]), how long it takes [MINUTES], and booking [LINK]. Under 150 words, helpful rather than salesy. ${POLICY}`,
      tip: "Clients who have a review before renewal are far less likely to shop elsewhere.",
    },
    {
      c: "Renewals & Retention",
      t: "Script: Saving a Client Who Wants to Cancel",
      u: "A client calls to cancel and you want a respectful conversation.",
      p: `Write a call guide for when a client says they want to cancel their [POLICY TYPE] because [REASON, e.g. price, found cheaper, moving]. Include: questions to understand the real reason, how to check whether the other quote is comparable coverage, options we can offer [OPTIONS], how to respect their decision if they still leave, and what to confirm in writing. No pressure tactics. ${POLICY}`,
      tip: "Ask to see the competing quote. Lower prices often come with lower limits the client did not notice.",
    },
    {
      c: "Renewals & Retention",
      t: "Email: Annual Account Review Summary",
      u: "You completed an annual review and want to send a written summary.",
      p: `Write a follow-up email summarizing an annual insurance review with a client. Covered today: [POLICIES REVIEWED]. Changes made: [CHANGES]. Recommendations the client is considering: [RECOMMENDATIONS]. Items declined by the client: [DECLINED ITEMS]. Next steps: [NEXT STEPS]. Under 220 words, clear bullets. ${POLICY}`,
      tip: "Documenting coverage the client declined protects you if a claim arises later. Always include it.",
    },
    {
      c: "Renewals & Retention",
      t: "Message: Birthday or Policy Anniversary Note",
      u: "You want personal touches that keep clients loyal.",
      p: `Write 3 short, warm messages from [AGENT NAME] at [AGENCY]: a birthday note, a policy anniversary thank-you (years as a client [YEARS]), and a holiday note. Each under 60 words, genuine, no sales pitch, and a simple sign-off with contact details.`,
      tip: "Handwritten cards with these words outperform emails for long-term clients.",
    },
    {
      c: "Renewals & Retention",
      t: "Campaign: Account Rounding (Bundling) Outreach",
      u: "Clients have one policy with you and could benefit from reviewing others.",
      p: `Write a short email campaign (3 emails) to clients who have only [ONE LINE, e.g. auto] with [AGENCY NAME], inviting them to review [OTHER LINES]. Focus on convenience, a coverage review and potential multi-policy discounts where available [DISCOUNTS]. Each under 130 words, helpful not pushy. ${POLICY}`,
      tip: "Clients with multiple lines stay much longer. Rounding accounts is retention as much as revenue.",
    },
    {
      c: "Renewals & Retention",
      t: "Survey: Client Satisfaction Check",
      u: "You want feedback before clients quietly leave.",
      p: `Design a 6-question client satisfaction survey for [AGENCY NAME]: ease of reaching us, clarity of explanations, claims support (if used), value for money, likelihood to recommend, and one open question. Add an intro line and a thank-you. Suggest when to send it and how to follow up on low scores within 48 hours.`,
      tip: "Call every low score personally. A fixed problem often creates the most loyal clients.",
    },
    {
      c: "Renewals & Retention",
      t: "Script: Handling a Non-Renewal by the Carrier",
      u: "The carrier is non-renewing a client's policy and you must tell them.",
      p: `Write a calm, clear message to a client whose [POLICY TYPE] with [CARRIER] will not be renewed on [DATE]. Reason given: [REASON]. Explain what this means, that we are shopping options [TIMEFRAME], what we need from them [INFORMATION], and the deadline to avoid a gap in coverage. Under 200 words, reassuring but honest. ${POLICY}`,
      tip: "Start the search before you tell the client, so the message includes a plan, not just a problem.",
    },

    // ── Claims Support ──
    {
      c: "Claims Support",
      t: "Guide: What to Do After an Accident or Loss",
      u: "Clients need clear first steps when something happens.",
      p: `Write a one-page client guide from [AGENCY NAME] on what to do after [LOSS TYPE, e.g. a car accident, water damage, a break-in]. Steps: safety first, documenting (photos, notes), preventing further damage, who to call and when (police if needed, the carrier claims line [NUMBER], our agency [NUMBER]), what not to do (admitting fault, throwing away damaged items), and what happens next. Plain language, numbered steps.`,
      tip: "Put this guide in the welcome packet and on your website. Clients look for it in the worst moments.",
    },
    {
      c: "Claims Support",
      t: "Message: Claim Status Check-In",
      u: "A client has an open claim and you want to keep them informed.",
      p: `Write a short check-in message to a client with an open [CLAIM TYPE] claim filed on [DATE]. Share the current status [STATUS], the next step [NEXT STEP], what they can do to help it move [ACTIONS], and how to reach the adjuster [ADJUSTER CONTACT] or us. Under 140 words, supportive. Do not predict the claim decision.`,
      tip: "Clients judge their agent by the claim experience. A weekly check-in during an open claim builds loyalty.",
    },
    {
      c: "Claims Support",
      t: "Explainer: How the Claims Process Works",
      u: "A client is filing their first claim and does not know what to expect.",
      p: `Write a plain-language explainer of the [CLAIM TYPE] claims process: filing, the adjuster's role, inspection or documentation, estimates, deductible, how payment works, timelines in general, and what to do if they disagree with the decision [APPRAISAL OR APPEAL PROCESS]. Under 400 words. Note that the carrier makes the claim decision under the policy terms.`,
      tip: "Explaining the adjuster's role early prevents clients from feeling the agent has abandoned them.",
    },
    {
      c: "Claims Support",
      t: "Checklist: Home Inventory for Clients",
      u: "You want clients to be prepared before a loss happens.",
      p: `Create a room-by-room home inventory checklist for clients of [AGENCY NAME], plus a short guide on how to do it quickly (video walkthrough, photos of receipts, cloud storage) and how often to update it. Friendly, practical, one page for the checklist.`,
      tip: "Offer it at renewal. It is useful, it is personal, and it gives a natural reason to talk about contents limits.",
    },
    {
      c: "Claims Support",
      t: "Email: Advocating With a Carrier on a Client's Claim",
      u: "A claim is stalled and you want to escalate professionally on the client's behalf.",
      p: `Write a professional email from [AGENT NAME] to [CARRIER] claims management about claim [CLAIM NUMBER PLACEHOLDER] for [CLAIM TYPE]. Facts: filed on [DATE], documents submitted [LIST], last contact [DATE], issue [ISSUE]. Request: [REQUEST, e.g. status update, supervisor review, timeline]. Under 200 words, factual and courteous, with a requested response date.`,
      tip: "Keep a dated log of every contact; escalations with a clear timeline get answered faster.",
    },
    {
      c: "Claims Support",
      t: "Script: Supporting a Client After a Denied Claim",
      u: "A client's claim was denied and they are upset.",
      p: `Write a call guide for supporting a client whose [CLAIM TYPE] claim was denied because [REASON GIVEN]. Include: acknowledging their frustration, explaining the stated reason in plain words, their options [APPEAL, APPRAISAL, STATE DEPARTMENT OF INSURANCE COMPLAINT], what I can do to help, and next steps with dates. Honest, compassionate, no promises about the outcome.`,
      tip: "Clients rarely leave over a denied claim they understood; they leave over one they felt alone with.",
    },
    {
      c: "Claims Support",
      t: "Social Post: Seasonal Loss Prevention Tips",
      u: "You want useful posts that help clients avoid claims.",
      p: `Write 4 seasonal loss prevention posts for [AGENCY NAME] in [REGION]: one each for [SEASONAL RISKS, e.g. frozen pipes, hurricane prep, holiday travel, wildfire season]. Each under 70 words with 3 practical tips and a call to action to review coverage. ${POLICY}`,
      tip: "Post loss prevention tips a week before the risk hits, not during it.",
    },

    // ── Marketing & Content ──
    {
      c: "Marketing & Content",
      t: "Website: About the Agency Page",
      u: "Your About page is generic and you want it to build trust.",
      p: `Write an About page for [AGENCY NAME] in [CITY]. Facts: founded [YEAR], team [TEAM], lines of insurance [LINES], carriers represented [NUMBER OR NAMES], communities served [COMMUNITIES], languages [LANGUAGES], and what makes us different (facts only) [DIFFERENTIATORS]. 350 to 450 words, warm and local. No claims of 'lowest rates' or 'best coverage'.`,
      tip: "Being independent and able to shop several carriers is a real differentiator; say it plainly if it applies.",
    },
    {
      c: "Marketing & Content",
      t: "Blog: Local Insurance Guide",
      u: "You want content that ranks for local insurance searches.",
      p: `Write a 700-word blog post: '[TOPIC], a guide for [CITY/STATE] residents' (for example, what flood insurance covers in [AREA]). Include local context [LOCAL FACTORS], common misunderstandings, questions to ask an agent, and a call to action. Accurate and general; note that coverage depends on the policy. Do not invent statistics.`,
      tip: "Local specifics (state minimums, regional risks) are what make insurance content rank and convert.",
    },
    {
      c: "Marketing & Content",
      t: "Email: Monthly Client Newsletter",
      u: "You want a newsletter clients read, not delete.",
      p: `Write a monthly newsletter for [AGENCY NAME]: one seasonal tip [TOPIC], one coverage question answered [QUESTION], agency news [NEWS], and a reminder to update us on life changes. Under 400 words, friendly. Include unsubscribe and agency address lines. ${POLICY}`,
      tip: "One useful tip per issue keeps open rates high. Newsletters stuffed with offers get ignored.",
    },
    {
      c: "Marketing & Content",
      t: "Video: Short Video Scripts",
      u: "You want quick videos for social media that explain one thing each.",
      p: `Write 5 scripts for 45-second vertical videos by [AGENT NAME] explaining: [TOPIC LIST, e.g. what uninsured motorist coverage is, why renters need insurance]. Each: a hook in the first 3 seconds, one clear explanation, one example, and a call to action. Conversational, no jargon. ${POLICY}`,
      tip: "Answer questions you hear every week. Those videos keep getting views because people keep asking.",
    },
    {
      c: "Marketing & Content",
      t: "Review: Asking for Reviews",
      u: "You want more online reviews in a compliant way.",
      p: `Write a short message asking clients of [AGENCY NAME] to leave an online review [LINK]. Ask every client (not only happy ones), offer no incentive, and keep it under 90 words. Add a version to send after a claim is resolved and a version for a new policy.`,
      tip: "After a claim is handled well is the best moment to ask; gratitude is highest then.",
    },
    {
      c: "Marketing & Content",
      t: "Ad: Local Search Ads",
      u: "You want search ads that comply with insurance advertising rules.",
      p: `Write 5 search ad variations for [AGENCY NAME] offering [LINES] in [CITY]. Each: 3 headlines under 30 characters and 2 descriptions under 90 characters. Use facts (local, independent, carriers shopped, languages, response time). No 'guaranteed lowest rates', no unqualified savings claims, no 'free' inducements. Add 10 keyword ideas.`,
      tip: "Check whether your state requires the agency's licence number or name in ads.",
    },
    {
      c: "Marketing & Content",
      t: "Community: Sponsorship and Event Outreach",
      u: "You want to get involved locally in a way that builds the agency.",
      p: `Write an email from [AGENCY NAME] offering to support [LOCAL ORGANIZATION OR EVENT]. What we offer: [SPONSORSHIP, VOLUNTEERS, A SAFETY WORKSHOP]. What we would like: [RECOGNITION, A TABLE, A MENTION]. Under 160 words, community-first. Then list 3 ways to follow up with attendees that are useful rather than salesy.`,
      tip: "Offer a practical workshop (home safety, first car) rather than a banner; it creates real conversations.",
    },

    // ── Commercial & Specialty Lines ──
    {
      c: "Commercial & Specialty Lines",
      t: "Questionnaire: Commercial Risk Assessment",
      u: "You are starting a commercial account and need a thorough risk picture.",
      p: `Act as a commercial risk advisor. Create a risk assessment questionnaire for a [BUSINESS TYPE] with [NUMBER] employees. Sections: operations, property and equipment, vehicles, employees and subcontractors, contracts and certificates of insurance required, cyber and data, loss history, and growth plans. Plain questions, grouped, with notes on why each matters.`,
      tip: "Ask to see the contracts they sign; contract insurance requirements drive commercial coverage more than anything.",
    },
    {
      c: "Commercial & Specialty Lines",
      t: "Proposal: Commercial Insurance Proposal",
      u: "You need to present a commercial insurance program clearly.",
      p: `Write a proposal summary for [BUSINESS NAME PLACEHOLDER], a [BUSINESS TYPE]. Proposed program: [COVERAGES, CARRIERS, LIMITS, DEDUCTIBLES, PREMIUMS]. Sections: executive summary, coverage by line in plain language, key exclusions and gaps they should know [GAPS], options to consider, total cost and payment options, and next steps. Clear and honest. ${POLICY}`,
      tip: "Name the gaps they are choosing not to cover. It builds trust and protects you.",
    },
    {
      c: "Commercial & Specialty Lines",
      t: "Explainer: Certificate of Insurance Requests",
      u: "Business clients keep asking about certificates of insurance and additional insureds.",
      p: `Write a plain-language explainer for commercial clients on certificates of insurance (COIs): what a COI is and is not, additional insured status and why contracts require it, how to request one from us [PROCESS AND TURNAROUND], and what to check in a contract before signing. Under 350 words. Note that a certificate does not change the policy.`,
      tip: "Ask clients to send contracts before signing, not after. You can flag requirements the policy does not meet.",
    },
    {
      c: "Commercial & Specialty Lines",
      t: "Guide: Cyber Risk Basics for Small Businesses",
      u: "Small business clients underestimate cyber risk.",
      p: `Write a plain guide for [BUSINESS TYPE] owners with about [NUMBER] employees on cyber risk: common incidents (phishing, ransomware, invoice fraud), practical protections (multi-factor authentication, backups, training), what to do in the first hour of an incident, and how cyber insurance generally works. Under 450 words, no scare tactics. ${POLICY}`,
      tip: "Carriers increasingly require MFA and backups for cyber coverage; helping clients meet them helps them qualify.",
    },
    {
      c: "Commercial & Specialty Lines",
      t: "Email: Workers' Compensation Audit Preparation",
      u: "A client has a premium audit coming and is worried.",
      p: `Write an email to a commercial client explaining an upcoming workers' compensation premium audit for policy period [PERIOD]. Include what an audit is, why it happens, documents to prepare [PAYROLL RECORDS, SUBCONTRACTOR CERTIFICATES, CLASS CODES], common surprises (uninsured subcontractors), and that we can help review before the auditor arrives. Under 220 words.`,
      tip: "Collect subcontractor certificates all year; missing ones are the biggest audit surprise.",
    },
    {
      c: "Commercial & Specialty Lines",
      t: "Checklist: New Business Coverage Onboarding",
      u: "A new business client just signed and you want nothing missed.",
      p: `Create an onboarding checklist for a new commercial client at [AGENCY NAME]: policies bound and documents delivered, certificates issued, payment setup, key contacts on both sides, claims reporting instructions, risk management resources, review dates, and a 30-day check-in. Owner and date for each.`,
      tip: "A structured 30-day check-in catches the problems that would otherwise surface at the first claim.",
    },
    {
      c: "Commercial & Specialty Lines",
      t: "Power Prompt: Coverage Gap Review for a Business",
      u: "You want a thorough gap analysis for a commercial account.",
      p: `Act as a senior commercial insurance advisor. Business profile: [BUSINESS TYPE, SIZE, OPERATIONS, LOCATIONS, CONTRACTS]. Current coverages: [LIST WITH LIMITS]. Identify possible gaps or underinsured areas, explain each in plain language with a realistic scenario, and suggest what to review or quote. Rank by potential severity. Frame as items to discuss, not conclusions. ${POLICY}`,
      tip: "Present the top three gaps only in the meeting. A list of fifteen overwhelms owners and nothing gets decided.",
    },

    // ── Life, Health & Benefits ──
    {
      c: "Life, Health & Benefits",
      t: "Guide: Life Insurance Needs Conversation",
      u: "You want to help a client think through how much life insurance they need.",
      p: `Act as a licensed life insurance agent. Write a conversation guide for a needs discussion with a client who has [SITUATION, e.g. two children and a mortgage]. Cover: who depends on their income, debts and ongoing costs [DETAILS IF KNOWN], future goals (education, care for a relative), existing coverage [COVERAGE], and how long protection is needed. Explain a simple needs calculation in plain words and what to review next. No product recommendation or projected returns.`,
      tip: "Let the client do the talking in the first half. People buy the amount they understand, not the amount they are told.",
    },
    {
      c: "Life, Health & Benefits",
      t: "Explainer: Open Enrollment Guide for Employees",
      u: "An employer client wants a clear open enrollment explainer for staff.",
      p: `Write an open enrollment guide for employees of [EMPLOYER TYPE] for plan year [YEAR]. Plans offered: [PLAN OPTIONS WITH KEY FEATURES]. Explain premium, deductible, copay, coinsurance and out-of-pocket maximum in plain words with one example, how to choose between plans, important dates [DATES], how to enroll [PROCESS], and who to ask [CONTACT]. Under 600 words. Use only the plan details provided.`,
      tip: "A worked example ('if you had a $2,000 procedure...') helps employees choose better than any table.",
    },
    {
      c: "Life, Health & Benefits",
      t: "Explainer: Medicare Basics for Turning 65",
      u: "Clients approaching 65 are confused about Medicare.",
      p: `Write a plain-language explainer for people turning 65 about the parts of Medicare (A, B, C, D) and Medigap in general terms, the initial enrollment period, and common mistakes (missing deadlines, late enrollment penalties). Include questions to ask before choosing and how to book a review with [AGENCY NAME]. Under 500 words. Note that rules and costs change yearly; confirm details at medicare.gov. Follow CMS marketing rules for Medicare Advantage and Part D communications.`,
      tip: "Medicare marketing has strict federal rules (CMS). Keep educational content separate from plan-specific marketing.",
    },
    {
      c: "Life, Health & Benefits",
      t: "Email: Benefits Renewal Summary for an Employer",
      u: "An employer group's benefits are renewing and you need to summarize options.",
      p: `Write an email to [EMPLOYER CONTACT ROLE] summarizing the benefits renewal for plan year [YEAR]. Current cost [COST], renewal increase [INCREASE], drivers of the increase [DRIVERS], alternative options quoted [OPTIONS WITH COSTS AND KEY DIFFERENCES], and my recommendation with reasoning [RECOMMENDATION]. Include the decision deadline [DATE]. Clear, under 350 words.`,
      tip: "Show the employee impact of each option, not just employer cost; it is usually what decides it.",
    },
    {
      c: "Life, Health & Benefits",
      t: "Script: Disability Insurance Conversation",
      u: "You want to raise disability insurance with clients who have never considered it.",
      p: `Write a short, respectful conversation guide for introducing disability income insurance to a [OCCUPATION] client. Include an opening question about how they would pay bills if unable to work, how disability insurance works in general (benefit amount, waiting period, benefit period), what employer coverage may already exist [IF KNOWN], and next steps. No scare tactics, no guarantees.`,
      tip: "Ask 'What is your biggest asset?' Most people say their home; the real answer is their ability to earn.",
    },
    {
      c: "Life, Health & Benefits",
      t: "FAQ: Health Insurance Marketplace Questions",
      u: "Individuals ask the same questions about marketplace plans every enrollment season.",
      p: `Write 8 FAQs for [AGENCY NAME] about individual health insurance through the marketplace in [STATE]: enrollment periods, special enrollment events, subsidies in general terms, metal levels, networks, and how an agent helps at no extra cost [IF TRUE IN YOUR STATE]. Plain language, 3 to 4 sentences each, with a note to confirm current rules at healthcare.gov or the state exchange.`,
      tip: "Publish the FAQ a month before open enrollment so it is indexed when people start searching.",
    },
    {
      c: "Life, Health & Benefits",
      t: "Checklist: Beneficiary Review",
      u: "You want clients to keep beneficiaries up to date.",
      p: `Create a beneficiary review checklist and a short client email from [AGENCY NAME]. Checklist: primary and contingent beneficiaries, life events that should trigger a review (marriage, divorce, births, deaths), minors as beneficiaries, trusts, and where to update each policy. Email under 130 words inviting a review, warm and practical.`,
      tip: "Outdated beneficiaries (an ex-spouse is the classic) cause some of the most painful claim outcomes. Review yearly.",
    },

    // ── Agency Operations & Compliance ──
    {
      c: "Agency Operations & Compliance",
      t: "SOP: New Business Submission Process",
      u: "New business submissions are inconsistent and errors slow them down.",
      p: `Write an SOP for new business submissions at [AGENCY NAME] for [LINE]. Steps: information gathering, application review, carrier selection, submission, follow-up timelines, binding requirements, document delivery, and file notes. Include a quality check list and common errors to avoid. Numbered and clear enough for a new CSR.`,
      tip: "Error-free submissions get faster underwriting responses. The checklist pays for itself quickly.",
    },
    {
      c: "Agency Operations & Compliance",
      t: "Template: File Documentation Notes (E&O Protection)",
      u: "You want file notes that protect the agency from errors and omissions claims.",
      p: `Create templates for file notes at [AGENCY NAME], using [AGENCY MANAGEMENT SYSTEM], that protect against E&O claims: coverage offered and declined, client instructions, changes requested and completed, and client communications. For each, show a vague example and a strong example. Include a short guide on what to always document.`,
      tip: "Documented declinations of offered coverage are one of the strongest E&O defenses. Always get them in writing.",
    },
    {
      c: "Agency Operations & Compliance",
      t: "Hiring: Job Post for a Customer Service Representative",
      u: "You need to hire a CSR or account manager.",
      p: `Write a job post for a [ROLE] at [AGENCY NAME] in [CITY]. Include: agency overview, duties [DUTIES], licence requirements or willingness to get licensed [DETAILS], systems used [AMS], schedule, pay range [RANGE] and benefits, growth path, and how to apply. Inclusive language, no age or gender-coded wording, under 350 words.`,
      tip: "Offering to pay for licensing widens your pool to strong service people from other industries.",
    },
    {
      c: "Agency Operations & Compliance",
      t: "Training: Producer Onboarding Plan",
      u: "A new producer is joining and you want them selling within 90 days.",
      p: `Create a 90-day onboarding plan for a new producer at [AGENCY NAME] focused on [LINES]. Include: licensing and carrier appointments, product training by week, systems, shadowing, target markets, weekly activity goals, a pipeline tracking template, and review points at 30, 60 and 90 days.`,
      tip: "Track activity (calls, quotes) in the first 90 days, not just sales; results follow activity.",
    },
    {
      c: "Agency Operations & Compliance",
      t: "Checklist: Advertising Compliance Review",
      u: "You want to check marketing material before it goes out.",
      p: `Create an advertising compliance checklist for an insurance agency in [STATE]: agency name and licence number requirements, no misrepresentation of coverage, savings claims substantiated, no rebating or prohibited inducements, carrier name usage rules, testimonial rules, and do-not-call and email rules. Mark state-specific items [CHECK STATE DEPARTMENT OF INSURANCE].`,
      tip: "Have one person sign off every ad against this checklist; it keeps the agency's voice and compliance consistent.",
    },
    {
      c: "Agency Operations & Compliance",
      t: "Analysis: Agency Book of Business Review",
      u: "You want to understand your book and where growth or risk sits.",
      p: `Act as an agency management consultant. From these figures: [POLICIES BY LINE, PREMIUM, RETENTION RATE, NEW BUSINESS, CARRIER MIX, CLIENTS WITH ONE POLICY], analyze the book: concentration risks, retention by line, cross-sell opportunities, and carrier dependency. Recommend 5 priorities for the next year with measurable targets. Show calculations; do not invent figures.`,
      tip: "The share of clients with a single policy is often your biggest untapped growth and retention lever.",
    },
    {
      c: "Agency Operations & Compliance",
      t: "Power Prompt: Build a Client Communication Calendar",
      u: "You want a year-round plan for staying in touch with every client.",
      p: `Act as an insurance agency marketing strategist. My agency: [LINES, CLIENT COUNT, REGION]. Build a 12-month client communication calendar: monthly themes tied to seasons and renewals, one email and 2 social posts per month (topics only), review invitations timed to renewals, loss prevention reminders, and personal touches (birthdays, anniversaries). Include who owns each item and what to measure.`,
      tip: "Automate the calendar in your agency management system so it runs even in busy months.",
    },
  ],
};
