import type { IndustryPack } from "./define";

// Law firms. Drafting prompts produce first drafts for attorney review, and
// marketing prompts follow the lawyer advertising rules (no guarantees, no
// unqualified "specialist", disclaimers on past results).

const CONF = "Use only the details I give; do not include client names or confidential facts beyond what is needed, and keep any identifying detail as a [PLACEHOLDER].";

export const LEGAL: IndustryPack = {
  id: "legal",
  label: "Law firm",
  prompts: [
    // ── Client Intake & Onboarding ──
    {
      c: "Client Intake & Onboarding",
      t: "Intake: Questionnaire for a New Matter Type",
      u: "You want a consistent intake questionnaire so first consultations are productive.",
      p: `Act as an experienced [PRACTICE AREA] attorney. Create an intake questionnaire for new clients with a [MATTER TYPE] matter. Group questions by: contact and conflict-check information, the facts in their own words, key dates and deadlines, documents they have, other parties involved, what outcome they want, and budget or fee questions. Plain language, one question per line, and mark which answers are needed before the consultation. Add a short note that submitting the form does not create an attorney-client relationship.`,
      tip: "Get the other parties' names up front. It lets you run conflicts before the consultation, not after.",
    },
    {
      c: "Client Intake & Onboarding",
      t: "Email: Consultation Confirmation and Preparation",
      u: "A prospective client has booked a consultation and you want them to come prepared.",
      p: `Write a consultation confirmation email from [FIRM NAME]. Details: date and time [DATE AND TIME], format [IN PERSON ADDRESS / VIDEO LINK], who they will meet [ATTORNEY], fee for the consultation [FEE OR FREE], documents to bring [LIST], and how to reschedule. Include a sentence that no attorney-client relationship exists until an engagement letter is signed. Professional, warm, under 200 words.`,
      tip: "A document list in the confirmation email makes the first meeting twice as useful.",
    },
    {
      c: "Client Intake & Onboarding",
      t: "Letter: Engagement Letter First Draft",
      u: "You have been retained and need a clear engagement letter to review and finalise.",
      p: `Act as a [PRACTICE AREA] attorney. Draft an engagement letter for attorney review. Details: client [CLIENT PLACEHOLDER], scope of representation [SCOPE], what is excluded [EXCLUSIONS], fee arrangement [HOURLY RATES / FLAT FEE / CONTINGENCY TERMS], retainer [AMOUNT AND HANDLING], costs and expenses, billing frequency, communication expectations, client responsibilities, termination, and file retention. Plain-English style. Mark any clause that must conform to my state's rules as [CHECK STATE RULE].`,
      tip: "A precise scope and exclusions section prevents most fee disputes later.",
    },
    {
      c: "Client Intake & Onboarding",
      t: "Letter: Non-Engagement Letter",
      u: "You are declining a matter and want to protect the firm and the prospective client.",
      p: `Draft a non-engagement letter from [FIRM NAME] to a prospective client after a consultation about [GENERAL MATTER TYPE]. State clearly that the firm is not representing them, that deadlines may apply to their matter and they should consult another attorney promptly, and return any documents [IF APPLICABLE]. Do not give legal advice or opinions on the merits. Courteous, under 180 words.`,
      tip: "Always mention that deadlines may apply. It is the sentence that protects you most.",
    },
    {
      c: "Client Intake & Onboarding",
      t: "Guide: Welcome Packet for New Clients",
      u: "You want every new client to know how the representation will work.",
      p: `Write a client welcome guide for [FIRM NAME] in the [PRACTICE AREA] practice. Cover: who is on their team and roles [TEAM], how and when we will update them, response times, the best way to reach us, how billing works [BILLING SUMMARY], what they should and should not do during the matter (for example, social media and talking to the other side), and what happens next in the process. Plain language, under 600 words.`,
      tip: "The 'what not to do' section, especially about social media, saves more cases than people expect.",
    },
    {
      c: "Client Intake & Onboarding",
      t: "Checklist: Conflict Check and File Opening",
      u: "You want a reliable file-opening process so nothing is missed.",
      p: `Create a file-opening checklist for [FIRM NAME]: conflict check (parties, related entities, adverse parties), engagement letter signed, retainer received and deposited correctly [TRUST ACCOUNT RULES], key deadlines calendared with backup reminder, file naming, client portal access, and initial task assignments. Include who is responsible for each step [ROLES].`,
      tip: "Double-calendar every deadline with two different people responsible. Missed deadlines are the top malpractice claim.",
    },
    {
      c: "Client Intake & Onboarding",
      t: "Script: Handling Prospective Client Calls",
      u: "Staff take calls from people with legal problems and need to screen them properly.",
      p: `Write a call script for staff at [FIRM NAME] taking calls from prospective clients. Include: greeting, gathering basic information and names for a conflict check before hearing details, the matter types we handle [TYPES], how to book a consultation, what staff must not do (give legal advice, predict outcomes), and how to handle urgent situations like upcoming court dates. Add a polite script for matters we do not handle, with a referral option [BAR REFERRAL SERVICE].`,
      tip: "Train staff to collect names before details; hearing a conflicted party's story can create problems.",
    },

    // ── Client Communication & Updates ──
    {
      c: "Client Communication & Updates",
      t: "Email: Plain-English Case Status Update",
      u: "A client wants to know where their matter stands and what comes next.",
      p: `Act as a [PRACTICE AREA] attorney. Write a status update email to a client about their [MATTER TYPE]. What has happened since the last update: [EVENTS]. Where things stand now: [STATUS]. Next steps and expected timing: [NEXT STEPS]. What we need from them: [ASK]. Plain English, no legal jargon without explanation, under 250 words, and do not predict outcomes. ${CONF}`,
      tip: "Send updates on a schedule even when little has happened. Silence is the top cause of client complaints to bar associations.",
    },
    {
      c: "Client Communication & Updates",
      t: "Explainer: Explain a Legal Process to a Client",
      u: "A client is anxious about a process (deposition, mediation, closing, probate) and needs a clear explanation.",
      p: `Write a plain-language explainer for a client about [PROCESS] in [JURISDICTION]. Include: what it is and why it happens, the steps in order, how long it usually takes, what the client will need to do, what they should expect on the day, and 5 common questions with short answers. Under 500 words. Note that details vary by case and I will discuss theirs specifically.`,
      tip: "Clients who understand the process make better decisions and call less.",
    },
    {
      c: "Client Communication & Updates",
      t: "Prep: Client Deposition Preparation Guide",
      u: "Your client will be deposed and needs to prepare.",
      p: `Act as a litigation attorney. Write a deposition preparation guide for a client. Include: what a deposition is, who will be there, how to answer (listen, pause, answer only the question, 'I don't know' and 'I don't recall' are acceptable when true), handling documents, objections, breaks, what to wear, and a list of 12 common practice questions for their type of case [CASE TYPE]. Emphasise telling the truth throughout.`,
      tip: "Run a mock session with the practice questions. Clients perform far better after rehearsing out loud.",
    },
    {
      c: "Client Communication & Updates",
      t: "Email: Delivering Bad News About a Matter",
      u: "You have to tell a client about an adverse ruling or a setback.",
      p: `Write an email to a client explaining an unfavourable development: [DEVELOPMENT]. Include: what happened in plain terms, what it means for their matter, options now [OPTIONS WITH DEADLINES], my recommendation [IF ANY], and an offer to talk by phone [TIMES]. Honest and compassionate, no blaming, under 250 words. Flag any deadline in the first paragraph. ${CONF}`,
      tip: "Call first, then send the email as a written record. Bad news should not arrive only in writing.",
    },
    {
      c: "Client Communication & Updates",
      t: "Summary: Summarize a Long Document for a Client",
      u: "The client needs to understand a long contract, order or letter.",
      p: `Summarize this document for a non-lawyer client: [PASTE DOCUMENT OR KEY SECTIONS]. Structure: what this document is, the 5 most important points for them, deadlines and obligations (with dates), risks or things to watch, and questions they should ask me. Plain English, under 400 words. Do not give advice beyond summarizing; I will add my advice separately. ${CONF}`,
      tip: "Check that the tool you use keeps client documents confidential before pasting anything sensitive.",
    },
    {
      c: "Client Communication & Updates",
      t: "Email: Setting Expectations on Communication",
      u: "A client is calling or emailing many times a day and you need to reset expectations kindly.",
      p: `Write a respectful email to a client who contacts the firm very frequently. Acknowledge that their matter matters to them, explain how we will keep them updated [SCHEDULE], response times [TIMES], how urgent issues are handled [PROCESS], and that frequent contact increases their fees [IF HOURLY]. Warm, firm, under 200 words.`,
      tip: "Offer a scheduled weekly call. It usually reduces ad hoc contact more than asking them to stop.",
    },
    {
      c: "Client Communication & Updates",
      t: "Letter: End of Representation Closing Letter",
      u: "A matter has concluded and you want to close the file properly.",
      p: `Write a closing letter from [FIRM NAME] at the end of a [MATTER TYPE]. Include: a summary of the outcome [OUTCOME], any continuing obligations or deadlines for the client [OBLIGATIONS], documents returned or retained and for how long [FILE RETENTION POLICY], final bill status [STATUS], that the representation has ended, and thanks. Under 250 words, professional and warm.`,
      tip: "A clear closing letter ends ongoing duties and is a natural moment to ask for a review or referral.",
    },

    // ── Drafting Support ──
    {
      c: "Drafting Support",
      t: "Draft: First Draft of a Demand Letter",
      u: "You need a first draft of a demand letter to revise.",
      p: `Act as a [PRACTICE AREA] attorney. Draft a demand letter for attorney review. Facts: [FACTS]. Legal basis: [CLAIMS OR BREACH]. Damages or remedy sought: [AMOUNT OR ACTION]. Deadline for response: [DATE]. Consequence if no response: [NEXT STEP]. Firm, professional tone, no threats that would breach ethics rules, and mark statements that need evidence support as [CONFIRM]. ${CONF}`,
      tip: "Only threaten actions you are willing and entitled to take. Empty threats weaken negotiating position and may breach ethics rules.",
    },
    {
      c: "Drafting Support",
      t: "Draft: Contract Clause Options",
      u: "You need alternative wordings for a clause to negotiate.",
      p: `Act as a commercial attorney. For a [CONTRACT TYPE], draft three versions of a [CLAUSE TYPE, e.g. limitation of liability, termination for convenience] clause: one favouring [MY CLIENT'S SIDE], one balanced, and one we could accept as a fallback. Governing law: [JURISDICTION]. After each, explain in two lines what it does and the main risk. For attorney review; not final language.`,
      tip: "Three versions give you a negotiation ladder. Know your fallback before the call.",
    },
    {
      c: "Drafting Support",
      t: "Review: Issue-Spot a Contract",
      u: "You want a first pass on a contract before your detailed review.",
      p: `Act as a [PRACTICE AREA] attorney representing [PARTY ROLE]. Review this contract: [PASTE CONTRACT OR SECTIONS]. Produce a table: Clause, Issue for my client, Risk level (high, medium, low), Suggested change. Then list missing clauses a contract of this type usually has. Do not state conclusions of law; flag items for my review. ${CONF}`,
      tip: "Use the table to structure your own review; it catches what tired eyes miss, but you still read every clause.",
    },
    {
      c: "Drafting Support",
      t: "Draft: Motion or Brief Outline",
      u: "You want to structure a motion or brief before writing it.",
      p: `Act as a litigation attorney. Build an outline for a [MOTION OR BRIEF TYPE] in [COURT/JURISDICTION]. Facts: [KEY FACTS]. Arguments I intend to make: [ARGUMENTS]. Produce: a heading structure, the point each section must establish, evidence to cite from the record [EXHIBITS], likely counterarguments and responses, and the relief requested. Do not invent case citations; mark where authority is needed as [AUTHORITY NEEDED].`,
      tip: "AI tools have fabricated case citations that lawyers were sanctioned for filing. Verify every authority yourself.",
    },
    {
      c: "Drafting Support",
      t: "Draft: Plain-Language Version of a Legal Document",
      u: "You want a client-friendly version of a document without changing its effect.",
      p: `Rewrite this legal text in plain English for a [AUDIENCE, e.g. tenant, employee, consumer] while keeping its legal effect: [PASTE TEXT]. Use short sentences, active voice and defined terms only where needed. Then list any place where simplifying could change the meaning, so I can decide. For attorney review.`,
      tip: "Plain-language documents reduce disputes. Just check every flagged change against the original intent.",
    },
    {
      c: "Drafting Support",
      t: "Draft: Settlement Proposal Letter",
      u: "You want to put a settlement offer in writing.",
      p: `Draft a settlement proposal letter for attorney review in a [MATTER TYPE]. Our position in brief: [POSITION]. Offer terms: [AMOUNT, CONDITIONS, TIMING]. Deadline for acceptance: [DATE]. Include appropriate settlement communication labelling for [JURISDICTION] (for example 'For settlement purposes only'). Professional and firm, under 300 words. ${CONF}`,
      tip: "Check your jurisdiction's rule on settlement communications before relying on the label.",
    },
    {
      c: "Drafting Support",
      t: "Draft: Discovery Requests First Draft",
      u: "You need a first set of discovery requests to refine.",
      p: `Act as a litigation attorney in [JURISDICTION]. Draft a first set of [INTERROGATORIES / REQUESTS FOR PRODUCTION / REQUESTS FOR ADMISSION] for a [CASE TYPE] case. Key issues: [ISSUES]. Parties: [ROLES]. Keep each request specific and proportional, number them, and include standard definitions. Note the local limit on the number of requests [LIMIT IF KNOWN]. For attorney review.`,
      tip: "Tie every request to an issue you must prove; it keeps you under numerical limits and makes motions to compel stronger.",
    },

    // ── Research & Case Preparation ──
    {
      c: "Research & Case Preparation",
      t: "Timeline: Build a Chronology From Documents",
      u: "You have a pile of documents and need a clean timeline of events.",
      p: `Create a chronology from these document excerpts: [PASTE EXCERPTS WITH SOURCE LABELS]. Table columns: Date, Event, Source (document and page), Significance, Disputed? (yes/no). List undated events separately. Do not infer dates that are not stated; mark them [DATE UNKNOWN]. ${CONF}`,
      tip: "Keep the source column accurate; a chronology is only as useful as your ability to prove each line.",
    },
    {
      c: "Research & Case Preparation",
      t: "Research: Research Plan for a Legal Question",
      u: "You want a structured research plan before opening the databases.",
      p: `Act as a senior associate. Build a research plan for this question: [LEGAL QUESTION] in [JURISDICTION]. Include: the issues and sub-issues, the types of authority to look for (statutes, regulations, cases, secondary sources), search terms and synonyms for Westlaw or Lexis, and questions of fact that could change the answer. Do not provide case names or citations; I will find and verify them.`,
      tip: "A good research plan halves research time. The facts that could change the answer are where cases are won.",
    },
    {
      c: "Research & Case Preparation",
      t: "Prep: Witness Interview Outline",
      u: "You are interviewing a witness and want a structured outline.",
      p: `Create an interview outline for a witness in a [CASE TYPE] matter. What the witness likely knows: [KNOWLEDGE]. Key issues: [ISSUES]. Include: introduction and purpose, open background questions, chronological questions, questions on key documents [DOCUMENTS], credibility and bias questions, and closing questions ('Who else should I talk to?'). Open questions first, then narrower follow-ups.`,
      tip: "Always end with 'What else should I know?' Witnesses often volunteer the most important fact last.",
    },
    {
      c: "Research & Case Preparation",
      t: "Analysis: Strengths and Weaknesses Memo Outline",
      u: "You want an honest case assessment before advising the client.",
      p: `Act as a [PRACTICE AREA] attorney. From these facts: [FACTS], outline a case assessment memo: elements of each claim or defense [CLAIMS], evidence supporting and undermining each element, credibility issues, likely opposing arguments, open factual questions, and litigation risks. Do not give a probability of success; list the factors I should weigh. ${CONF}`,
      tip: "Write the other side's best argument before your own; it makes your advice to the client more realistic.",
    },
    {
      c: "Research & Case Preparation",
      t: "Prep: Mediation Preparation Brief",
      u: "You are going to mediation and want to prepare yourself and the client.",
      p: `Help me prepare for mediation in a [CASE TYPE] matter. Inputs: our position [POSITION], their likely position [THEIR POSITION], client's goals and interests [INTERESTS], range of acceptable outcomes [RANGE], and non-monetary terms that matter [TERMS]. Produce: an opening statement outline, a negotiation plan with opening, target and walk-away points, likely offers and responses, and client preparation talking points.`,
      tip: "Agree the walk-away point with the client before the day, in writing. Decisions made at 6pm in mediation are rarely the best.",
    },
    {
      c: "Research & Case Preparation",
      t: "Checklist: Trial Preparation Checklist",
      u: "Trial is approaching and you want a complete prep checklist.",
      p: `Create a trial preparation checklist for a [CASE TYPE] trial in [COURT] starting [DATE]. Sections with deadlines counted back from trial: pretrial filings, exhibit lists and exhibits, witness list, subpoenas, witness preparation, motions in limine, jury instructions [IF JURY], demonstratives and technology, logistics, and client preparation. Include owners [TEAM ROLES]. Mark court-specific deadlines as [CHECK LOCAL RULES].`,
      tip: "Test the courtroom technology in person before trial day. It fails at the worst possible moment.",
    },
    {
      c: "Research & Case Preparation",
      t: "Summary: Deposition Transcript Summary",
      u: "You need a usable summary of a long deposition transcript.",
      p: `Summarize this deposition transcript excerpt: [PASTE EXCERPT WITH PAGE:LINE REFERENCES]. Produce: a topic-by-topic summary with page:line cites, key admissions, inconsistencies with other evidence [OTHER EVIDENCE IF ANY], and follow-up questions. Quote exactly where wording matters; do not paraphrase admissions. ${CONF}`,
      tip: "Keep page:line cites on every point; summaries without cites have to be redone when you need them.",
    },

    // ── Marketing & Content ──
    {
      c: "Marketing & Content",
      t: "Website: Practice Area Page",
      u: "You need a practice area page that informs clients and follows advertising rules.",
      p: `Write a website page for [FIRM NAME]'s [PRACTICE AREA] practice in [CITY/STATE]. Include: who we help and common situations, how the process usually works, what to do first if they face this issue, why clients choose us (facts only: [EXPERIENCE, LANGUAGES, FEE OPTIONS]), and how to contact us. 600 to 800 words, plain language. No guarantees of results, no 'specialist' or 'expert' unless certified [CERTIFICATION IF ANY], and add the attorney advertising disclaimer required in [STATE].`,
      tip: "Answer the questions clients actually ask in consultations; those pages rank and convert best.",
    },
    {
      c: "Marketing & Content",
      t: "Article: Client Alert on a Legal Change",
      u: "A new law or ruling affects your clients and you want to tell them quickly.",
      p: `Write a client alert from [FIRM NAME] about [LEGAL CHANGE] effective [DATE]. Include: what changed in plain terms, who is affected, what they should do now (practical steps), and a contact for questions. Under 450 words. Add a line that the alert is general information, not legal advice, and does not create an attorney-client relationship. Do not invent details of the change; use only [SUMMARY OF THE CHANGE].`,
      tip: "Speed matters with client alerts; being first in a client's inbox builds more trust than being longest.",
    },
    {
      c: "Marketing & Content",
      t: "Social: LinkedIn Posts for an Attorney",
      u: "An attorney wants to post regularly on LinkedIn without it feeling like advertising.",
      p: `Write 4 LinkedIn posts for [ATTORNEY NAME], a [PRACTICE AREA] attorney. Mix: a practical tip, a common misconception explained, a lesson from experience (no client details), and a question to the audience. Each under 180 words, conversational and credible. No guarantees, no case results without the required disclaimer, and no client-identifying details.`,
      tip: "Posts that teach one practical thing outperform firm announcements by a wide margin.",
    },
    {
      c: "Marketing & Content",
      t: "FAQ: Frequently Asked Questions Page",
      u: "You want a FAQ page that answers real client questions and ranks in search.",
      p: `Write 12 FAQs for [FIRM NAME]'s [PRACTICE AREA] practice in [STATE]. Use the questions clients actually ask [LIST ANY YOU HEAR]. Answer each in 3 to 5 plain sentences, giving general information and a clear next step. Add a disclaimer that answers are general and not legal advice. Avoid predictions about outcomes.`,
      tip: "Add the FAQ schema markup to your site so the answers can appear directly in search results.",
    },
    {
      c: "Marketing & Content",
      t: "Profile: Attorney Bio",
      u: "An attorney needs a bio that is credible and approachable.",
      p: `Write a website bio for [ATTORNEY NAME]. Facts: bar admissions [STATES], education [SCHOOLS], practice focus [AREAS], experience [YEARS AND TYPES OF MATTERS], professional memberships [LIST], certifications [ONLY IF HELD], languages [LANGUAGES], and one personal detail they approved [DETAIL]. 200 words, third person. Use 'focuses on' rather than 'specializes in' unless certified.`,
      tip: "Clients hire people. One genuine personal line makes a bio memorable.",
    },
    {
      c: "Marketing & Content",
      t: "Email: Client Newsletter",
      u: "You want to stay in touch with past clients and referral sources.",
      p: `Write a quarterly newsletter for [FIRM NAME]. Sections: a legal update relevant to [AUDIENCE] [TOPIC], a practical tip, firm news [NEWS], and an invitation to reach out. Under 500 words, friendly and useful. Include unsubscribe and firm address lines, and the attorney advertising label if required in [STATE].`,
      tip: "Past clients are a large share of referrals for most small firms. A useful quarterly email keeps you top of mind.",
    },
    {
      c: "Marketing & Content",
      t: "Review: Responding to an Online Review",
      u: "Someone left a review and you want to respond without breaching confidentiality.",
      p: `Write a public response to this online review of [FIRM NAME]: [PASTE REVIEW]. Do not confirm or deny that the reviewer was a client and reveal no information about any matter. Thank them, state the firm's commitment in general terms, and invite them to contact [NAME/ROLE] directly. Under 80 words, professional.`,
      tip: "Several lawyers have been disciplined for revealing client information in review replies. Say less, not more.",
    },

    // ── Billing, Fees & Collections ──
    {
      c: "Billing, Fees & Collections",
      t: "Rewrite: Clear Time Entry Descriptions",
      u: "Your time entries are vague and clients question the bills.",
      p: `Rewrite these time entries so a client understands the value of each: [PASTE ENTRIES]. Each description should say what was done, why, and the outcome where relevant, in one line. Avoid block billing (separate tasks), and keep the times unchanged. ${CONF}`,
      tip: "Specific entries get paid faster and challenged less. 'Review' alone is the most disputed word on legal bills.",
    },
    {
      c: "Billing, Fees & Collections",
      t: "Email: Overdue Invoice Reminder Sequence",
      u: "A client has an unpaid invoice and you need to follow up professionally.",
      p: `Write three emails for an overdue invoice [INVOICE NUMBER, AMOUNT, DUE DATE]. 1) Friendly reminder at 7 days overdue. 2) Firmer note at 30 days, offering a payment plan [OPTIONS]. 3) Final notice at 60 days, stating next steps under the engagement letter [NEXT STEPS]. Each under 150 words, professional, and consistent with ethics rules on withdrawing and on client confidentiality.`,
      tip: "Offer a payment plan early. It recovers more than escalation and keeps the relationship.",
    },
    {
      c: "Billing, Fees & Collections",
      t: "Explainer: Fee Options for Clients",
      u: "You offer different fee arrangements and want to explain them simply.",
      p: `Write a client-facing explainer of fee options at [FIRM NAME]: [HOURLY RATE, FLAT FEE SERVICES, CONTINGENCY, LIMITED SCOPE]. For each: how it works, what it includes, what costs are extra, and when it tends to suit a matter. Plain language, under 400 words, and no guarantee of total cost.`,
      tip: "Flat fees for predictable matters win clients who fear open-ended bills.",
    },
    {
      c: "Billing, Fees & Collections",
      t: "Estimate: Budget for a Litigation Matter",
      u: "A client wants to know what their case might cost.",
      p: `Act as a litigation attorney. Build a phase-by-phase budget estimate for a [CASE TYPE] case: pleadings, written discovery, depositions [NUMBER], experts [IF ANY], motions, mediation, trial. For each phase give assumptions, hours range by timekeeper [RATES], and costs. Add a paragraph explaining what could make it higher or lower. Make clear it is an estimate, not a cap.`,
      tip: "Update the budget at each phase. Clients forgive overruns they were warned about; they do not forgive surprises.",
    },
    {
      c: "Billing, Fees & Collections",
      t: "Script: Discussing a Fee Dispute",
      u: "A client disputes a bill and you want to handle the conversation well.",
      p: `Write a guide for a call with a client disputing a bill of [AMOUNT] for [MATTER]. Include: how to open (listen first), questions to understand the concern, how to walk through the work done, options (explanation, adjustment, payment plan, fee arbitration program [IF AVAILABLE IN STATE]), and how to close with a written follow-up. Calm, non-defensive tone.`,
      tip: "Listen fully before explaining. Most fee disputes are really about communication during the matter.",
    },
    {
      c: "Billing, Fees & Collections",
      t: "Checklist: Trust Account Compliance",
      u: "You want to check your trust account practices against good practice.",
      p: `Create a trust (IOLTA) account compliance checklist for a small firm in [STATE]: what goes into trust, when funds can be withdrawn, three-way reconciliation monthly, client ledgers, record retention, handling disputed funds, and common mistakes. Mark state-specific requirements as [CHECK STATE BAR RULE].`,
      tip: "Monthly three-way reconciliation catches errors before they become bar complaints.",
    },
    {
      c: "Billing, Fees & Collections",
      t: "Analysis: Realization and Collection Rate Review",
      u: "You want to understand where revenue is being lost.",
      p: `Act as a law firm management consultant. From these figures: [HOURS WORKED, HOURS BILLED, AMOUNTS BILLED, AMOUNTS COLLECTED BY PRACTICE AREA OR ATTORNEY], calculate utilization, realization and collection rates, identify where revenue is lost, suggest likely causes, and recommend 5 actions. Show the calculations. Do not invent figures.`,
      tip: "Write-downs before billing are often the biggest leak, and the least visible one.",
    },

    // ── Business Development & Referrals ──
    {
      c: "Business Development & Referrals",
      t: "Email: Reconnect With a Referral Source",
      u: "You want to rebuild a relationship with an accountant, realtor or other referrer.",
      p: `Write a short email from [ATTORNEY NAME] to [REFERRAL SOURCE TYPE] [NAME PLACEHOLDER] to reconnect. Mention a relevant development [DEVELOPMENT] that may affect their clients, offer something useful [RESOURCE, CLE, LUNCH], and suggest a short call. Under 130 words, genuine, no hard sell. No referral fees or inducements.`,
      tip: "Lead with something useful to them. Referral relationships are built on giving first.",
    },
    {
      c: "Business Development & Referrals",
      t: "Plan: 90-Day Business Development Plan",
      u: "You want a practical plan to grow your book of business.",
      p: `Act as a legal business development coach. I am a [PRACTICE AREA] attorney with [YEARS] experience in [MARKET]. Ideal clients: [CLIENT TYPE]. Current referral sources: [SOURCES]. Time available: [HOURS PER WEEK]. Create a 90-day plan with weekly actions: referral relationships, content, events, past clients, and online presence. Include a simple tracking sheet and what to measure.`,
      tip: "Past clients and existing referral sources produce results fastest. Start there before new marketing.",
    },
    {
      c: "Business Development & Referrals",
      t: "Presentation: Seminar or CLE Outline",
      u: "You are giving a talk to potential clients or referrers.",
      p: `Create a 45-minute presentation outline on [TOPIC] for [AUDIENCE, e.g. small business owners, financial advisors]. Include: learning objectives, 4 sections with key points and one practical example each, an interactive moment, common mistakes, and a close with next steps. Add a one-page handout outline. General information only, no legal advice to individuals.`,
      tip: "Offer a checklist handout people can take home; it keeps your name on their desk.",
    },
    {
      c: "Business Development & Referrals",
      t: "Email: Asking a Satisfied Client for a Referral",
      u: "A matter ended well and you want to ask for referrals without awkwardness.",
      p: `Write a short email from [ATTORNEY NAME] to a client whose [MATTER TYPE] has concluded successfully. Thank them, mention you are glad to help people they know with similar matters [MATTER TYPES], and invite a review [LINK] if they are comfortable. Under 120 words, warm. No incentives for referrals or reviews.`,
      tip: "Ask when the client is happiest: right after the good outcome, not months later.",
    },
    {
      c: "Business Development & Referrals",
      t: "Pitch: Proposal for a Business Client",
      u: "A business is choosing outside counsel and wants a proposal.",
      p: `Write a proposal from [FIRM NAME] to [COMPANY TYPE] for [SCOPE OF WORK]. Sections: understanding of their needs [NEEDS], our approach, team and relevant experience [FACTS], communication and reporting, fee proposal [FEE STRUCTURE], and why us (facts). Under 900 words, specific to them, no guarantees of outcome.`,
      tip: "Show you understand their business in the first paragraph; most proposals start with the firm's history instead.",
    },
    {
      c: "Business Development & Referrals",
      t: "Networking: Follow-Up After an Event",
      u: "You met useful people at an event and want to follow up well.",
      p: `Write 3 short follow-up messages after [EVENT] to: 1) a potential client I spoke with about [TOPIC], 2) a potential referral partner [PROFESSION], 3) a fellow attorney. Each under 90 words, reference something specific from our conversation [DETAIL], and suggest one next step. No solicitation of a person known to need legal help for a specific matter unless permitted by [STATE] rules.`,
      tip: "Follow up within 48 hours and reference one specific thing you talked about.",
    },
    {
      c: "Business Development & Referrals",
      t: "Power Prompt: Build a Niche Positioning Strategy",
      u: "You want to stand out in a crowded market by focusing on a niche.",
      p: `Act as a legal marketing strategist. My firm: [PRACTICE AREAS, LOCATION, SIZE]. Clients I serve best: [CLIENTS]. Competitors: [COMPETITORS]. Identify 3 possible niches with reasoning, and for the strongest one produce: a positioning statement, target client profile, 5 content ideas, 3 referral partner types, website changes, and 90-day actions. Compliant with attorney advertising rules.`,
      tip: "Niching down feels risky and usually does the opposite: referrers remember the lawyer who does one thing.",
    },

    // ── Practice Operations ──
    {
      c: "Practice Operations",
      t: "SOP: Standard Operating Procedure for a Recurring Task",
      u: "A recurring task is done differently by everyone and you want one process.",
      p: `Write a standard operating procedure for [TASK, e.g. opening a new file, preparing a closing binder, calendaring court dates] at [FIRM NAME]. Include: purpose, who does it, trigger, step-by-step instructions, templates used [TEMPLATES], quality checks, and common mistakes. Numbered steps, clear enough for a new staff member.`,
      tip: "Have the person who does the task best write the first draft with this prompt, then refine it together.",
    },
    {
      c: "Practice Operations",
      t: "Policy: AI Use Policy for the Firm",
      u: "Staff are using AI tools and you need rules that protect clients.",
      p: `Draft an AI use policy for [FIRM NAME] covering: approved tools [TOOLS], what may and may not be entered (no confidential client information in tools without appropriate confidentiality terms), verifying all output and every citation, attorney supervision of staff use, disclosure to clients where appropriate, billing for AI-assisted work, and training. Reference ABA Formal Opinion 512 (2024) and state guidance [STATE GUIDANCE IF ANY]. Under 700 words.`,
      tip: "The two rules that matter most: protect confidentiality and verify everything before it leaves the firm.",
    },
    {
      c: "Practice Operations",
      t: "Checklist: Calendar and Deadline Control",
      u: "You want a system that makes missed deadlines very unlikely.",
      p: `Create a deadline control system for a [SIZE] firm practicing [AREAS]: sources of deadlines, how deadlines are calculated and double-checked [RULES], two-person calendaring, reminder intervals, what happens when someone is out, weekly deadline review meeting agenda, and audit steps. Practical and specific.`,
      tip: "A 10-minute weekly deadline review with the whole team is cheap insurance.",
    },
    {
      c: "Practice Operations",
      t: "Hiring: Job Post for a Paralegal",
      u: "You need to hire a paralegal and want a fair, clear job post.",
      p: `Write a job post for a [ROLE] at [FIRM NAME] in [CITY]. Include: what the firm does, duties [DUTIES], required skills and experience [REQUIREMENTS], software used [SOFTWARE], schedule and location [DETAILS], pay range [RANGE] and benefits [BENEFITS], and how to apply. Inclusive language, no age-coded or gendered wording, under 350 words.`,
      tip: "List the software you use; it attracts candidates who can start being useful in week one.",
    },
    {
      c: "Practice Operations",
      t: "Training: Onboarding Plan for a New Associate",
      u: "A new associate starts soon and you want them productive and supported.",
      p: `Create a 30-day onboarding plan for a new associate in a [PRACTICE AREA] firm. Include: week-by-week goals, systems and templates to learn, matters to shadow, first assignments with feedback loops, ethics and firm policies, business development basics, and weekly check-in questions. Add a 90-day success checklist.`,
      tip: "Give written feedback on the first three assignments. It shapes how they work for years.",
    },
    {
      c: "Practice Operations",
      t: "Meeting: Weekly Firm Meeting Agenda",
      u: "You want a short weekly meeting that keeps matters moving.",
      p: `Create a 30-minute weekly meeting agenda for a [SIZE] law firm: upcoming deadlines and hearings, matter status by attorney (1 minute each), new intakes and conflicts, billing and collections snapshot, workload and help needed, and one process improvement. Include a simple action log format.`,
      tip: "End every meeting by reading back the action log with owners and dates.",
    },
    {
      c: "Practice Operations",
      t: "Power Prompt: Map and Automate Your Intake Process",
      u: "Intake is slow and you lose prospective clients before they sign.",
      p: `Act as a law firm operations consultant. My current intake process: [DESCRIBE STEPS FROM FIRST CALL TO SIGNED ENGAGEMENT]. Tools I use: [TOOLS]. Map the process, find where prospects drop off, and recommend: response time targets, automation opportunities (forms, scheduling, e-signature, reminders), what must stay personal, conflict check timing, and 5 metrics to track. Give a 30-day implementation plan.`,
      tip: "Speed to first response is the biggest driver of signed clients for most small firms. Measure it first.",
    },
  ],
};
