import type { IndustryPack } from "./define";

// Medical practices. Nothing here needs identifiable patient information;
// prompts work from de-identified details, and patient-facing material tells
// people when to call the practice or emergency services.

const NOPHI = "Do not include any patient name, date of birth, record number or other identifying detail.";

export const MEDICAL: IndustryPack = {
  id: "medical",
  label: "Medical practice",
  prompts: [
    // ── Patient Communication ──
    {
      c: "Patient Communication",
      t: "Message: New Patient Welcome Email",
      u: "A new patient has booked and you want them to arrive prepared and reassured.",
      p: `Act as the patient experience lead at [PRACTICE NAME], a [SPECIALTY] practice. Write a welcome email for new patients. Include: what to bring (ID, insurance card, medication list, [OTHER]), how early to arrive [MINUTES], how to complete forms online [LINK OR PROCESS], parking and directions [DETAILS], what the first visit involves, cancellation policy [POLICY], and how to contact us [PHONE, PORTAL]. Warm, clear, under 250 words, 7th-grade reading level. Do not promise specific outcomes.`,
      tip: "Send it with the booking confirmation and again 2 days before the visit; first-visit no-shows drop when patients know what to expect.",
    },
    {
      c: "Patient Communication",
      t: "Message: Appointment Reminder Sequence",
      u: "You want reminders that reduce no-shows without annoying patients.",
      p: `Write an appointment reminder sequence for [PRACTICE NAME]: a text 3 days before, a text the day before, and a text 2 hours before. Each under 160 characters, with date and time placeholders [DATE] [TIME], the location or video link [LOCATION], and a simple way to confirm or reschedule [REPLY OR LINK]. Include how to reach us if they are running late. ${NOPHI} Do not mention the reason for the visit.`,
      tip: "Leaving the reason for the visit out of texts protects privacy if someone else sees the patient's phone.",
    },
    {
      c: "Patient Communication",
      t: "Script: Delivering a Delay Update in the Waiting Room",
      u: "The clinic is running late and you need to tell waiting patients kindly and honestly.",
      p: `Write a short script for front desk staff at [PRACTICE NAME] to update waiting patients when the clinic is running about [MINUTES] minutes late. Include: an apology, an honest estimate, options (wait, reschedule, step out and get a text), and what we are doing to keep them informed. Under 80 words, calm and respectful. Add a version for a text message to patients who have not arrived yet.`,
      tip: "Update patients before they ask. People tolerate delays far better when told early and honestly.",
    },
    {
      c: "Patient Communication",
      t: "Letter: Practice Policy Change Announcement",
      u: "A policy is changing (hours, fees, portal, insurance) and patients need to know.",
      p: `Write a patient letter from [PRACTICE NAME] announcing this change: [CHANGE]. Effective date: [DATE]. Why it is changing: [REASON]. What patients need to do: [ACTION]. Who is affected: [WHO]. Where to get help: [CONTACT]. Put the change and the date in the first two sentences, keep it under 220 words, plain language, and no jargon.`,
      tip: "Post the same message in the portal and at the front desk; mailed letters alone reach only part of your patients.",
    },
    {
      c: "Patient Communication",
      t: "Message: Portal Reply to a Common Non-Urgent Question",
      u: "You get the same non-urgent portal questions again and again and want consistent replies.",
      p: `Act as a nurse coordinator at a [SPECIALTY] practice. Write a template portal reply to this common non-urgent question: [QUESTION, e.g. how to request a refill, when test results come back]. Include the practice's process [PROCESS], expected timeframes [TIMEFRAME], and when to call instead [RED FLAGS]. Under 150 words, friendly, and end with: if symptoms are severe or you think it is an emergency, call 911 or go to the nearest emergency department.`,
      tip: "Have a clinician approve each template once. After that, staff can send consistent answers in seconds.",
    },
    {
      c: "Patient Communication",
      t: "Script: Discussing Costs and Payment Options",
      u: "Staff need to talk to patients about out-of-pocket costs without awkwardness.",
      p: `Write a script for billing staff at [PRACTICE NAME] to explain an estimated out-of-pocket cost of [AMOUNT] for [SERVICE] to a patient. Include: how the estimate was calculated in plain words, that the final bill may differ and why, payment options [PAYMENT PLANS, FINANCING], financial assistance [IF OFFERED], and how to ask questions. Respectful, under 150 words. Add 3 short answers to common pushback.`,
      tip: "Good-faith estimate rules may apply to uninsured or self-pay patients; check the No Surprises Act requirements for your practice.",
    },
    {
      c: "Patient Communication",
      t: "Message: Follow-Up After a Procedure",
      u: "You want every patient to get the same clear check-in after a procedure.",
      p: `Write a follow-up message for patients the day after [PROCEDURE] at [PRACTICE NAME]. Include: a warm check-in, what is normal to feel [NORMAL EFFECTS], warning signs that need a call to the practice [WARNING SIGNS], signs that need emergency care [EMERGENCY SIGNS], how to reach us after hours [AFTER-HOURS NUMBER], and the follow-up appointment [DETAILS]. Under 200 words, 6th to 7th-grade reading level. Have a clinician confirm the medical content before use.`,
      tip: "List warning signs as short bullets. Patients scan follow-up messages rather than read them.",
    },

    // ── Patient Education ──
    {
      c: "Patient Education",
      t: "Handout: Explain a Condition in Plain Language",
      u: "You need a patient handout about a common condition that patients will actually understand.",
      p: `Act as a patient education specialist working with a [SPECIALTY] physician. Write a one-page handout on [CONDITION]. Sections: What it is (2 to 3 sentences), Common symptoms, What causes it or raises the risk, How it is usually treated [PRACTICE'S USUAL APPROACH], What you can do at home, When to call us, When to seek emergency care. 6th-grade reading level, short sentences, no jargon (explain any medical term). Add a note that the handout does not replace advice from their own clinician.`,
      tip: "Always have a clinician review before use. Run the text through a readability checker; aim for grade 6 to 8.",
    },
    {
      c: "Patient Education",
      t: "Handout: Preparing for a Procedure",
      u: "Patients need clear preparation instructions so procedures are not cancelled.",
      p: `Write patient preparation instructions for [PROCEDURE] at [PRACTICE NAME]. Details: fasting rules [RULES], medications to stop or continue [INSTRUCTIONS FROM CLINICIAN], what to bring, arrival time, whether they need a driver [YES/NO], what to expect on the day, and recovery time. Use a numbered timeline (one week before, day before, morning of). 6th-grade reading level. Use only the clinical instructions I have given; mark any gap as [CONFIRM WITH CLINICIAN].`,
      tip: "Timeline format cuts cancellations for missed prep steps. Send it one week and one day before.",
    },
    {
      c: "Patient Education",
      t: "Explainer: How to Take a New Medication",
      u: "A patient is starting a common medication and needs simple instructions to take home.",
      p: `Write a plain-language explainer about [MEDICATION] prescribed for [PURPOSE]. Include: how and when to take it as prescribed [DOSE AND TIMING FROM THE PRESCRIBER], what to do if a dose is missed [INSTRUCTION], common side effects, side effects that need a call, things to avoid [FOOD, ALCOHOL, OTHER MEDS, IF ANY], and how long before it works. Use only the information I provide plus widely accepted general guidance; tell the patient to check with their pharmacist or clinician for anything specific to them.`,
      tip: "Pair the handout with the pharmacist's leaflet and point patients to it; it reinforces rather than replaces it.",
    },
    {
      c: "Patient Education",
      t: "Guide: Lifestyle Change Plan Patients Can Follow",
      u: "You want to give patients a realistic starting plan for a lifestyle change.",
      p: `Act as a health coach working with a [SPECIALTY] practice. Create a 4-week starter plan for a patient working on [GOAL, e.g. lowering blood pressure, more activity, better sleep]. Include one small change per week, how to track it simply, what to do on a bad day, and when to check in with the practice. Encouraging, realistic, non-judgemental, under 350 words. General guidance only; the patient's clinician sets their individual targets [TARGETS IF GIVEN].`,
      tip: "One change per week beats a full overhaul. Ask patients which week-one change feels easiest.",
    },
    {
      c: "Patient Education",
      t: "FAQ: Top 10 Questions About a Treatment",
      u: "Patients ask the same questions about a treatment and you want a single FAQ.",
      p: `Write a patient FAQ with the 10 most common questions about [TREATMENT OR SERVICE] at a [SPECIALTY] practice. Questions I hear most: [LIST ANY YOU KNOW]. Answer each in 2 to 4 plain-language sentences. Include cost and insurance questions with our process [PROCESS], and a final question about when to call the practice. Mark any answer that needs clinician confirmation as [CONFIRM]. Do not promise outcomes; where results vary, say so.`,
      tip: "Put the FAQ on your website too. Well-answered FAQs reduce phone calls and help search visibility.",
    },
    {
      c: "Patient Education",
      t: "Explainer: What Your Test Results Mean",
      u: "You want a general explainer for a common test so patients understand their result letter.",
      p: `Write a general patient explainer for [TEST, e.g. lipid panel, A1C]. Include: what the test measures, what the common ranges usually mean in plain words (say that normal ranges vary by lab), what can affect results, and what happens next if a result is outside the range. Under 300 words. Make clear their own clinician will explain what their specific result means for them. ${NOPHI}`,
      tip: "Link this explainer in result notifications so patients understand the basics before calling.",
    },
    {
      c: "Patient Education",
      t: "Translate: Patient Material for a Different Reading Level or Language",
      u: "You have patient material that is too complex, or need it for patients who speak another language.",
      p: `Rewrite this patient material: [PASTE TEXT] for [AUDIENCE, e.g. 5th-grade reading level, older adults, Spanish speakers]. Keep all medical facts exactly the same; simplify sentences and explain terms. If translating, produce the translation and a list of medical terms a qualified medical interpreter should check. Do not add new medical claims.`,
      tip: "Machine translation of medical content must be checked by a qualified medical interpreter before patients see it.",
    },

    // ── Scheduling & Front Desk ──
    {
      c: "Scheduling & Front Desk",
      t: "Script: Phone Greeting and Triage for Front Desk",
      u: "You want every call answered consistently and routed safely.",
      p: `Write a front desk phone script for [PRACTICE NAME]. Include: greeting, how to identify the reason for the call, routing rules for scheduling, refills, billing and clinical questions [WHO HANDLES EACH], the exact wording to use if the caller describes emergency symptoms (tell them to hang up and call 911), how to verify identity before discussing anything [PRACTICE'S VERIFICATION STEPS], and a polite close. Keep lines short and natural.`,
      tip: "Put the emergency wording on a card at every phone. Staff should never have to think about it.",
    },
    {
      c: "Scheduling & Front Desk",
      t: "Policy: No-Show and Late Cancellation Policy",
      u: "No-shows are costing the practice and you need a fair, clear policy.",
      p: `Draft a patient-facing no-show and late cancellation policy for [PRACTICE NAME]. Details: notice required [HOURS], fee if any [AMOUNT], how many no-shows before other steps [NUMBER AND STEPS], exceptions (emergencies, illness), and how patients are reminded. Firm but kind, under 200 words. Add a short script for staff to explain it at booking. Check it against any payer contract rules on no-show fees.`,
      tip: "Explaining the policy at booking cuts no-shows more than the fee does.",
    },
    {
      c: "Scheduling & Front Desk",
      t: "Template: Waitlist and Cancellation Fill Message",
      u: "A slot opened up and you want to offer it to waitlisted patients quickly.",
      p: `Write a short text to offer an opening at [PRACTICE NAME] on [DATE] at [TIME] with [CLINICIAN TYPE] to patients on the waitlist. First reply claims it. Include how to reply, a deadline to respond [MINUTES OR HOURS], and a note that others are being offered it too. Under 160 characters, plus a follow-up for when the slot is taken. ${NOPHI}`,
      tip: "Text the waitlist in small batches. Offering to everyone at once creates disappointment for most of them.",
    },
    {
      c: "Scheduling & Front Desk",
      t: "Checklist: Insurance Verification Before a Visit",
      u: "Claims are being denied for eligibility issues you could catch earlier.",
      p: `Create a pre-visit insurance verification checklist for front desk staff at a [SPECIALTY] practice. Include: when to verify (how many days before), eligibility and active coverage, copay and deductible, referral or prior authorization requirements [COMMON ONES FOR US], in-network status, what to tell the patient if there is a problem, and how to document. One page, checkbox format.`,
      tip: "Track denial reasons for a month. The checklist should target the top three, not every possible issue.",
    },
    {
      c: "Scheduling & Front Desk",
      t: "Script: Handling an Upset Patient at Check-In",
      u: "A patient is frustrated at the desk and staff need a calm approach.",
      p: `Write a short de-escalation guide for front desk staff when a patient is upset about [ISSUE, e.g. wait time, a bill, a referral]. Include 8 phrases that acknowledge, apologise where appropriate, and offer options; 5 phrases to avoid; when to involve a manager; and how to protect privacy when others can hear (lower voice, offer a private space). Respectful and practical.`,
      tip: "Offer a private space early. Many conflicts at the desk are about embarrassment as much as the issue itself.",
    },
    {
      c: "Scheduling & Front Desk",
      t: "Template: Prior Authorization Status Update to a Patient",
      u: "A patient is waiting on a prior authorization and keeps calling for updates.",
      p: `Write a patient message explaining that a prior authorization for [SERVICE OR MEDICATION] has been submitted to their insurer on [DATE]. Explain in plain language what prior authorization is, the usual timeframe [TIMEFRAME], what we will do next, what they can do (call their insurer with the reference number [IF APPLICABLE]), and how we will update them. Under 170 words. ${NOPHI}`,
      tip: "Proactive updates at set points (submitted, pending, decided) cut repeat calls sharply.",
    },
    {
      c: "Scheduling & Front Desk",
      t: "Guide: Scheduling Template to Reduce Wait Times",
      u: "Your schedule runs late every day and you want to redesign it.",
      p: `Act as a practice operations consultant. My practice schedule: [DESCRIBE SLOTS, VISIT TYPES AND LENGTHS, WHERE DELAYS HAPPEN]. Suggest a revised scheduling template: visit types and realistic lengths, buffer slots, where to place complex visits and same-day slots, and a daily huddle routine. Explain the reasoning and how to measure improvement over 4 weeks (average wait time, on-time start rate).`,
      tip: "Measure your real visit lengths for two weeks first; most schedules fail because slot lengths are guesses.",
    },

    // ── Practice Marketing & Reputation ──
    {
      c: "Practice Marketing & Reputation",
      t: "Website: Service Page for a Treatment",
      u: "You need a clear, compliant website page for a service your practice offers.",
      p: `Write a website service page for [SERVICE] at [PRACTICE NAME] in [CITY]. Sections: who it is for, what it involves, what to expect before, during and after, recovery or follow-up, insurance and cost information [DETAILS], why patients choose us (facts only: [CREDENTIALS, YEARS, FEATURES]), and how to book. Around 500 words, plain language. No guarantees, no 'best' or 'pain-free' claims, and add 'Individual results vary.' where results are discussed.`,
      tip: "Facts beat adjectives in healthcare marketing. 'Board-certified, 15 years, same-week appointments' persuades better than 'world-class care'.",
    },
    {
      c: "Practice Marketing & Reputation",
      t: "Review Reply: Responding to a Negative Online Review",
      u: "A patient left a negative public review and you want to respond without breaching privacy.",
      p: `Write a public reply to this online review of [PRACTICE NAME]: [PASTE REVIEW]. The reply must not confirm the person is a patient or mention any detail of their care. Thank them, acknowledge the concern in general terms, say what the practice does to improve [GENERAL ACTION], and invite them to call the practice manager directly [CONTACT]. Under 90 words, calm and professional.`,
      tip: "Even confirming someone was a patient can be a privacy breach. Keep public replies general and move the conversation offline.",
    },
    {
      c: "Practice Marketing & Reputation",
      t: "Request: Asking Patients for Reviews the Right Way",
      u: "You want more online reviews without breaking rules on incentives or privacy.",
      p: `Write a short post-visit message inviting patients of [PRACTICE NAME] to leave a review on [PLATFORM]. Rules: ask every patient (not just happy ones), offer no incentive, do not ask them to mention health details, and make it easy [LINK]. Under 100 words, warm. Add a one-line version for a printed card at checkout.`,
      tip: "Asking only happy patients (review gating) breaks platform rules and FTC guidance. Ask everyone.",
    },
    {
      c: "Practice Marketing & Reputation",
      t: "Social Posts: Monthly Health Awareness Calendar",
      u: "You want a month of social posts that educate without giving individual advice.",
      p: `Create a 4-week social media calendar for [PRACTICE NAME], a [SPECIALTY] practice, for [MONTH]. Tie posts to relevant awareness days [IF ANY]. 3 posts per week: one education tip, one practice update or team introduction, one myth vs fact. For each: caption under 80 words, an image idea, and a call to action. No patient photos or stories without written authorization, no individual medical advice, no guarantees.`,
      tip: "Team introduction posts consistently get the most engagement for local practices; patients like to know who they will see.",
    },
    {
      c: "Practice Marketing & Reputation",
      t: "Email: Patient Newsletter",
      u: "You want a monthly newsletter patients actually open.",
      p: `Write a monthly patient newsletter for [PRACTICE NAME]. Include: a seasonal health tip on [TOPIC], a practice update [UPDATE], a short FAQ answer [QUESTION], a reminder about [SCREENING OR SERVICE] with who it is recommended for in general terms, and how to book. Subject line options (3), under 400 words, friendly. Include an unsubscribe line and the practice address. No individual advice.`,
      tip: "Screening reminders tied to seasons (flu shots in autumn, skin checks before summer) get the best booking response.",
    },
    {
      c: "Practice Marketing & Reputation",
      t: "Profile: Physician Bio for the Website",
      u: "A clinician needs a bio that is professional and approachable.",
      p: `Write a website bio for [CLINICIAN NAME AND TITLE] at [PRACTICE NAME]. Facts: education and training [DETAILS], board certification [DETAILS], areas of focus [FOCUS], years in practice [YEARS], languages [LANGUAGES], and a personal line they approved [PERSONAL DETAIL]. 150 to 200 words, third person, warm and factual. Avoid 'best', 'leading' or 'expert' unless it is a verifiable credential.`,
      tip: "Patients choose clinicians they feel they can talk to. One genuine personal detail helps more than another credential.",
    },
    {
      c: "Practice Marketing & Reputation",
      t: "Ad: Local Search Ad for a New Service",
      u: "You are launching a service and want compliant local ads.",
      p: `Write 5 Google search ad variations for [SERVICE] at [PRACTICE NAME] in [CITY]. Each: 3 headlines under 30 characters and 2 descriptions under 90 characters. Focus on facts (location, availability, insurance accepted [PLANS], credentials [CREDENTIALS]). No guarantees, no before-and-after claims, no 'best' or 'cure'. Add 10 relevant keyword ideas.`,
      tip: "Healthcare ads face extra platform restrictions; check the ad platform's healthcare policy for your service before launching.",
    },

    // ── Referrals & Care Coordination ──
    {
      c: "Referrals & Care Coordination",
      t: "Letter: Referral Letter to a Specialist",
      u: "You need a clear, complete referral so the specialist has what they need.",
      p: `Draft a referral letter from [REFERRING CLINICIAN, PRACTICE] to [SPECIALIST TYPE]. Reason for referral: [REASON]. Relevant history and findings (de-identified draft; the final letter goes through our secure system): [SUMMARY]. Treatments tried: [TREATMENTS]. Specific question for the specialist: [QUESTION]. Urgency: [ROUTINE/URGENT]. Keep it concise and structured with headings. ${NOPHI} I will add identifiers in the EHR.`,
      tip: "A specific question ('Is this X or Y?') gets a far more useful reply than 'please evaluate and treat'.",
    },
    {
      c: "Referrals & Care Coordination",
      t: "Outreach: Building a Referral Relationship With Local Practices",
      u: "You want more referrals from primary care or other local clinicians.",
      p: `Write an introduction email from [CLINICIAN, PRACTICE] to local [REFERRING PRACTICE TYPE] clinicians. Include: what we treat [CONDITIONS], how quickly we see referrals [WAIT TIME], how referrals work [PROCESS, FAX, PORTAL], how we communicate back after the visit, and an offer of a short lunch-and-learn or call. Under 200 words, collegial and specific. No inducements for referrals.`,
      tip: "Closing the loop with a timely letter back to the referrer is the single biggest driver of repeat referrals.",
    },
    {
      c: "Referrals & Care Coordination",
      t: "Template: Care Transition Checklist",
      u: "Patients moving between hospital, home and your practice fall through the cracks.",
      p: `Create a care transition checklist for a [SPECIALTY] practice when a patient is discharged from hospital or another setting. Include: receiving the discharge summary, medication reconciliation, follow-up visit timing [TIMEFRAME], who calls the patient and when, education needs, equipment or home services, and red flags to review. One page with owner for each step.`,
      tip: "A call within 2 business days of discharge catches medication mix-ups before they cause harm.",
    },
    {
      c: "Referrals & Care Coordination",
      t: "Summary: Patient Handoff Note Between Clinicians",
      u: "A patient is moving to another clinician in the practice and you want a clean handoff.",
      p: `Write a structured handoff note using the SBAR format (Situation, Background, Assessment, Recommendation) from these de-identified notes: [PASTE NOTES]. Keep each section to 2 to 4 bullet points, include pending results and open actions with owners, and flag anything time-sensitive at the top. ${NOPHI}`,
      tip: "Put pending results in their own line. They are the most common thing lost in handoffs.",
    },
    {
      c: "Referrals & Care Coordination",
      t: "Message: Coordinating With a Caregiver",
      u: "A patient has asked you to involve a family caregiver in their care.",
      p: `Write a short message from [PRACTICE NAME] to a caregiver the patient has authorized in writing. Share only: [WHAT THE PATIENT AUTHORIZED]. Include: upcoming appointments [DATES], what the caregiver can help with [TASKS], how to reach the care team, and the patient's preferences they asked us to share [PREFERENCES]. Under 160 words, warm. Confirm authorization is on file before sending.`,
      tip: "Keep a copy of the authorization with the message in the record; caregivers change and authorizations expire.",
    },
    {
      c: "Referrals & Care Coordination",
      t: "Checklist: Closing the Loop on Referrals and Tests",
      u: "You want a system so no referral or test result gets lost.",
      p: `Design a simple tracking process for referrals and tests ordered at [PRACTICE NAME]. Include: what to log (type, date, destination), who checks for results and when [ROLE, FREQUENCY], what to do when nothing comes back after [DAYS], how to notify patients of results (normal and abnormal) [PRACTICE POLICY], and a weekly report. Include a sample tracking table.`,
      tip: "Missed abnormal results are a leading cause of malpractice claims. A weekly open-loop report is cheap protection.",
    },
    {
      c: "Referrals & Care Coordination",
      t: "Letter: Consult Note Summary Back to the Referring Clinician",
      u: "You saw a referred patient and want a clear note back to the referrer.",
      p: `Draft a brief consult summary back to a referring clinician from these de-identified notes: [NOTES]. Structure: thank you for the referral, key findings, impression, plan, what we need from them, and when we will see the patient again. Under 250 words, clinician-to-clinician tone. ${NOPHI} I will add identifiers in the EHR.`,
      tip: "Send it within a week. Referrers remember who writes back quickly.",
    },

    // ── Clinical Documentation Support ──
    {
      c: "Clinical Documentation Support",
      t: "Template: Visit Note Template for a Common Visit Type",
      u: "You want a consistent note template for a visit type you see every day.",
      p: `Act as a physician experienced in efficient documentation. Create a note template for a [VISIT TYPE] in a [SPECIALTY] practice with sections for chief complaint, HPI prompts, pertinent review of systems, focused exam elements, assessment and plan, patient education given, and follow-up. Use short prompts and dropdown-style options where useful. Do not include any patient information.`,
      tip: "Build templates around what you actually document, then trim anything you never fill in.",
    },
    {
      c: "Clinical Documentation Support",
      t: "Rewrite: Patient-Friendly After-Visit Summary",
      u: "You want the after-visit summary to be understandable for the patient.",
      p: `Rewrite this de-identified clinical plan: [PASTE PLAN] as a patient-friendly after-visit summary. Sections: What we talked about, Your plan (numbered steps), Medicines (as prescribed, no changes), Tests and appointments, When to call us, When to get emergency care. 6th-grade reading level. Keep every clinical instruction exactly as written; do not add advice. ${NOPHI}`,
      tip: "Patients forget most of what is said in a visit. A clear written plan is the best adherence tool you have.",
    },
    {
      c: "Clinical Documentation Support",
      t: "Checklist: Documentation for a Coding Level",
      u: "You want to make sure notes support the visit level billed.",
      p: `Act as a certified medical coder. Explain in plain language what documentation supports [E/M LEVEL OR SERVICE] under the current CMS guidelines for office visits based on medical decision making or time. Give a checklist a clinician can use before signing, common documentation gaps, and two examples of wording that is too vague versus specific enough. Note that coding rules change; confirm with your coding team.`,
      tip: "Documenting the reasoning behind decisions supports both good care and the level billed.",
    },
    {
      c: "Clinical Documentation Support",
      t: "Letter: Work or School Note Template",
      u: "You write the same kind of work or school notes repeatedly.",
      p: `Create a template for a [WORK/SCHOOL] note from [PRACTICE NAME]. Include: date seen [DATE], dates excused [DATES], activity restrictions if any [RESTRICTIONS], expected return date [DATE], and clinician signature line. State only what is needed; no diagnosis unless the patient requests it in writing. Short and formal.`,
      tip: "Leaving the diagnosis off by default protects patient privacy with employers and schools.",
    },
    {
      c: "Clinical Documentation Support",
      t: "Letter: Letter of Medical Necessity",
      u: "An insurer needs a letter of medical necessity for a treatment or equipment.",
      p: `Draft a letter of medical necessity for [TREATMENT, DEVICE OR MEDICATION] to [INSURER]. De-identified draft details: diagnosis [DIAGNOSIS], relevant history [HISTORY], treatments tried and outcomes [TRIED], why this is necessary now [REASON], expected benefit [BENEFIT], and consequences of not providing it [RISK]. Formal, concise, clinically specific. Leave placeholders for patient identifiers and policy numbers, which I will add securely.`,
      tip: "Listing prior treatments tried and why they failed is usually what gets an approval.",
    },
    {
      c: "Clinical Documentation Support",
      t: "Summary: Literature Summary for a Clinical Question",
      u: "You want a quick structured overview before looking at the primary sources.",
      p: `Act as a clinical researcher. Give me a structured overview of what is generally known about [CLINICAL QUESTION]. Sections: current mainstream guidance and which bodies issue it, key evidence themes, areas of uncertainty, and search terms for PubMed. Do not invent citations or statistics; if you are unsure, say so. I will verify against primary sources and current guidelines.`,
      tip: "Use this to structure your search, never as the evidence itself. AI summaries can be outdated or wrong.",
    },
    {
      c: "Clinical Documentation Support",
      t: "Template: Standing Order or Protocol Draft",
      u: "You want a draft protocol for a routine task staff can do under standing orders.",
      p: `Draft a standing order protocol for [ROUTINE TASK, e.g. flu vaccination, A1C point-of-care testing] at [PRACTICE NAME]. Include: purpose, eligible patients, exclusions, who may carry it out [ROLES], step-by-step procedure, documentation, what to do if a problem occurs, and review date. Mark any clinical threshold as [PHYSICIAN TO CONFIRM]. For physician review and signature.`,
      tip: "Standing orders free clinician time only if staff trust them. Walk the team through the protocol once before go-live.",
    },

    // ── Staff Training & Operations ──
    {
      c: "Staff Training & Operations",
      t: "Training: HIPAA Refresher for Front Office Staff",
      u: "You need a short, practical privacy refresher for non-clinical staff.",
      p: `Create a 15-minute HIPAA privacy refresher for front office staff at a [SPECIALTY] practice. Cover: what counts as protected health information, verifying identity on the phone, conversations in the waiting area, screens and printed documents, sharing with family members, email and texting rules [PRACTICE POLICY], and how to report a possible breach [PROCESS]. Include 5 realistic scenario questions with answers.`,
      tip: "Scenarios from your own front desk teach far better than definitions. Ask staff for recent near misses.",
    },
    {
      c: "Staff Training & Operations",
      t: "SOP: Opening and Closing Checklist",
      u: "You want the practice to open and close the same way every day.",
      p: `Write opening and closing checklists for [PRACTICE NAME]. Opening: systems, schedule review, supplies, temperature logs [IF APPLICABLE], front desk readiness, huddle. Closing: charts to complete, messages returned, secure records and screens, supplies, cleaning, alarms. Include the role responsible for each item [ROLES] and checkboxes.`,
      tip: "Laminate the checklist and review it in the monthly staff meeting; update it every time something is missed.",
    },
    {
      c: "Staff Training & Operations",
      t: "Guide: Morning Huddle Agenda",
      u: "You want a 10-minute daily huddle that prevents problems.",
      p: `Create a 10-minute morning huddle agenda for [PRACTICE NAME]. Include: schedule overview and bottlenecks, patients needing extra time or support (no identifiers aloud in shared spaces), staffing gaps, equipment or supply issues, yesterday's issues and fixes, and one shout-out. Add a simple board layout to track actions.`,
      tip: "Keep it standing and under 10 minutes. The value is in spotting today's problems, not discussing them at length.",
    },
    {
      c: "Staff Training & Operations",
      t: "Hiring: Job Post for a Medical Assistant",
      u: "You need to hire a medical assistant and want a clear, fair job post.",
      p: `Write a job posting for a [ROLE, e.g. medical assistant] at [PRACTICE NAME] in [CITY]. Include: what the practice does, daily duties [DUTIES], required qualifications and certifications [REQUIREMENTS], nice-to-haves, schedule [HOURS], pay range [RANGE] and benefits [BENEFITS], and how to apply. Inclusive language, no age or gender-coded wording, under 350 words.`,
      tip: "Include the pay range. Many states now require it, and it attracts more qualified applicants.",
    },
    {
      c: "Staff Training & Operations",
      t: "Onboarding: First Week Plan for a New Staff Member",
      u: "A new team member starts Monday and you want them productive and confident.",
      p: `Create a first-week onboarding plan for a new [ROLE] at [PRACTICE NAME]. Day by day: introductions, systems access and training [EHR, PHONE, SCHEDULING], shadowing, policies to read (HIPAA, safety, [OTHERS]), first tasks alone with support, and end-of-week check-in questions. Include a competency checklist to sign off by week 4.`,
      tip: "Assign a buddy who is not their manager. New staff ask buddies the questions they will not ask managers.",
    },
    {
      c: "Staff Training & Operations",
      t: "Incident: Patient Safety Incident Review Template",
      u: "Something went wrong or nearly did, and you want a blame-free review.",
      p: `Create a blame-free incident review template for [PRACTICE NAME]. Sections: what happened (facts, timeline), contributing factors (systems, communication, workload, equipment), what went well, what we will change, owner and date for each action, and how we will know it worked. Add 8 prompting questions for the review meeting. No patient identifiers in the review document.`,
      tip: "Review near misses too. They show you the weak point before anyone gets hurt.",
    },
    {
      c: "Staff Training & Operations",
      t: "Script: Handling a Patient Complaint Formally",
      u: "A patient has made a formal complaint and you need a consistent process.",
      p: `Write a complaint handling process for [PRACTICE NAME]: acknowledgement within [DAYS], investigation steps, who reviews, response letter template, timeline, and how learning is shared. Then write the acknowledgement letter template: thank them, confirm what the complaint is about in general terms, explain the next steps and timeline, and give a contact. Under 180 words for the letter.`,
      tip: "A fast, personal acknowledgement defuses many complaints before the investigation finishes.",
    },

    // ── Practice Management & Growth ──
    {
      c: "Practice Management & Growth",
      t: "Analysis: Why Patients Leave and How to Keep Them",
      u: "Patient retention is slipping and you want a structured look at why.",
      p: `Act as a healthcare practice consultant. My practice: [SPECIALTY, SIZE, LOCATION]. What I am seeing: [SIGNS, e.g. fewer follow-ups, lower review scores]. Build an analysis plan: likely reasons patients leave in practices like mine, data to check [WHAT I CAN ACCESS], a short patient survey (5 questions), and 5 retention actions ranked by effort and impact. Be specific and practical, no generic advice.`,
      tip: "Call five patients who did not return and ask why. It is uncomfortable and it is the best data you will get.",
    },
    {
      c: "Practice Management & Growth",
      t: "Plan: Launching a New Service Line",
      u: "You are adding a new service and need a launch plan.",
      p: `Create a 90-day launch plan for [NEW SERVICE] at [PRACTICE NAME]. Include: readiness (staff training, equipment, protocols, billing and coding [CODES IF KNOWN], payer coverage checks), internal launch (telling current patients who may benefit, in general terms), external marketing (website, referrers, local), metrics to track, and a review at day 90. Timeline with owners.`,
      tip: "Confirm payer coverage before marketing. Launching a service patients cannot get covered damages trust.",
    },
    {
      c: "Practice Management & Growth",
      t: "Report: Monthly Practice Performance Summary",
      u: "You want a clear monthly summary for the partners or owners.",
      p: `Write a monthly performance summary for [PRACTICE NAME] from these figures: [PASTE FIGURES, e.g. visits, new patients, no-show rate, collections, days in A/R, denials, patient satisfaction]. Structure: headline (3 sentences), what improved, what worsened and likely reasons, 3 recommended actions, and one number to watch next month. Plain language, under 400 words. Do not invent figures.`,
      tip: "Compare against the same month last year as well as last month; many practices have strong seasonality.",
    },
    {
      c: "Practice Management & Growth",
      t: "Negotiation: Preparing for a Payer Contract Negotiation",
      u: "Your payer contract is up for renewal and you want to prepare.",
      p: `Act as a practice revenue consultant. Help me prepare for a contract renegotiation with [PAYER]. My data: volume of their patients [NUMBER], top codes and current rates [CODES AND RATES], market factors [ACCESS, QUALITY, UNIQUE SERVICES]. Produce: a one-page value summary to send them, the key asks in priority order, likely payer objections with responses, and walk-away considerations.`,
      tip: "Quality and access data (same-week appointments, outcomes) strengthen your position more than cost arguments.",
    },
    {
      c: "Practice Management & Growth",
      t: "Survey: Patient Experience Survey",
      u: "You want patient feedback that is short enough to be completed and useful enough to act on.",
      p: `Design a patient experience survey for [PRACTICE NAME] with no more than 8 questions: ease of booking, wait time, front desk courtesy, clinician communication, understanding of the plan, likelihood to recommend, and one open question. Add a short intro and a thank-you. Suggest when and how to send it and how to report results monthly. No clinical questions.`,
      tip: "Share one improvement you made from feedback in your waiting room and newsletter. Response rates go up.",
    },
    {
      c: "Practice Management & Growth",
      t: "Policy: Social Media Policy for Staff",
      u: "Staff use social media and you need clear rules to protect patients and the practice.",
      p: `Draft a social media policy for staff at [PRACTICE NAME]. Cover: never posting patient information or photos (even without names), not interacting with patients as their clinician on personal accounts, speaking on behalf of the practice, workplace photos, reporting concerns, and consequences. Plain language, under 450 words. Add 5 examples of what is and is not OK.`,
      tip: "Examples make policies stick. A photo of a birthday cake in the break room with a chart visible behind it is a great one.",
    },
    {
      c: "Practice Management & Growth",
      t: "Power Prompt: Build a Complete Patient Journey Improvement Plan",
      u: "You want to review the whole patient experience, from first call to follow-up, in one go.",
      p: `Act as a healthcare operations consultant. My practice: [SPECIALTY, SIZE]. Known pain points: [PAIN POINTS]. Map the patient journey in 8 stages (finding us, booking, reminders, arrival, waiting, the visit, checkout and billing, follow-up). For each stage: what good looks like, common failures in practices like mine, one quick fix, one bigger fix, and a metric. Finish with a 90-day action plan choosing the 5 highest-impact fixes.`,
      tip: "Walk the journey yourself: call your own practice, book, and sit in the waiting room. You will find things no report shows.",
    },
  ],
};
