import type { IndustryPack } from "./define";

// Social work. Every prompt works with de-identified details (initials or
// "the client"); identifying information belongs in the agency's secure
// record system, not in an AI tool.

const DEID = "Use initials or 'the client' only. Do not include names, addresses, dates of birth or case numbers.";

export const SOCIAL_WORK: IndustryPack = {
  id: "social-work",
  label: "Social work",
  prompts: [
    // ── Case Notes & Documentation ──
    {
      c: "Case Notes & Documentation",
      t: "Case Note: Turn Rough Notes Into a Clear Progress Note",
      u: "You have messy notes from a visit or session and need a professional progress note for the record.",
      p: `Act as an experienced social worker writing a progress note for a case record. Here are my rough notes from a [VISIT TYPE, e.g. home visit, office session] with client [INITIALS]: [PASTE ROUGH NOTES]. Rewrite them as a progress note in this structure: Purpose of contact, Observations (facts only, what I saw and heard), Client's report (in their words where I noted them), Interventions, Plan and next steps. Use objective, person-first, non-judgemental language. Do not add anything that is not in my notes; where something important is missing, write [MISSING: what] so I can fill it in. ${DEID}`,
      tip: "Paste your notes the same day. Ask it to also flag any statement that reads as opinion rather than observation.",
    },
    {
      c: "Case Notes & Documentation",
      t: "Case Note: Convert Notes to DAP Format",
      u: "Your agency uses DAP (Data, Assessment, Plan) notes and you want your session notes in that format quickly.",
      p: `Act as a clinical social worker. Convert these session notes for client [INITIALS] into a DAP note. Notes: [PASTE NOTES]. Data: what the client said and what I observed, factually. Assessment: my professional interpretation, clearly marked as assessment, linked to the goals in the plan: [CURRENT GOALS]. Plan: specific next steps, who does what, and the next contact date [DATE IF KNOWN]. Keep it under 250 words, person-first and strengths-based. Do not invent diagnoses, symptoms or events. ${DEID}`,
      tip: "If your agency uses SOAP or BIRP instead, swap the format name and headings; the rest of the prompt works the same.",
    },
    {
      c: "Case Notes & Documentation",
      t: "Case Note: Rewrite Judgemental Language Into Objective Language",
      u: "You want to check a note or report for loaded or stigmatising wording before it goes in the record.",
      p: `Act as a social work supervisor reviewing documentation. Review this text: [PASTE TEXT]. Find every phrase that is a judgement, label or assumption rather than an observation (for example 'non-compliant', 'manipulative', 'in denial', 'addict'). For each, give the original phrase, why it could bias a reader, and an objective, person-first rewrite that describes the behaviour and context. Then give the full rewritten text. Do not change the facts. ${DEID}`,
      tip: "Run this on anything that may be read by the client, a court or another agency. Records are often read years later by people who never met the client.",
    },
    {
      c: "Case Notes & Documentation",
      t: "Case Note: Summarize a Long Case History for a New Worker",
      u: "A case is being transferred and the new worker needs a concise, accurate history.",
      p: `Act as a senior social worker preparing a transfer summary. From this case history: [PASTE DE-IDENTIFIED HISTORY], write a one-page summary for the incoming worker with these sections: Reason for involvement, Key events in date order (month and year only), Current goals and progress, Strengths and supports, Risks and safety considerations, Services involved and contacts (roles, not names), Open actions and deadlines. Use bullet points, neutral language, and mark anything uncertain as 'to confirm'. ${DEID}`,
      tip: "Ask for a second version written for the client, in plain language, if your agency shares transfer summaries with them.",
    },
    {
      c: "Case Notes & Documentation",
      t: "Case Note: Contact Log Entry From a Phone Call",
      u: "You need a quick, accurate log entry for a call with a client, family member or professional.",
      p: `Write a concise contact log entry from these call notes: [PASTE CALL NOTES]. Include: type of contact (phone), who the contact was with (role only, e.g. 'client's mother', 'school counselor'), purpose, key information exchanged, any concerns raised, agreed actions with owner and timeframe, and follow-up needed. Keep it under 120 words, factual and in past tense. ${DEID}`,
      tip: "Save this as a template so every log entry in your caseload has the same structure, which makes audits far easier.",
    },
    {
      c: "Case Notes & Documentation",
      t: "Case Note: Documentation Audit Checklist",
      u: "You want to check your own files before an audit or supervision review.",
      p: `Act as a quality assurance reviewer for a [AGENCY TYPE, e.g. child welfare, adult services, behavioral health] agency. Create a documentation self-audit checklist I can use on my case files. Cover: timeliness of notes, required forms and signatures [LIST YOUR AGENCY'S REQUIRED FORMS IF KNOWN], consent and releases, service plan currency, objective language, risk documentation, contact frequency requirements [REQUIREMENT, e.g. monthly visits], and closure documentation. Format as a table with columns: Item, What 'meets standard' looks like, Yes/No, Notes.`,
      tip: "Add your agency's own standards to the prompt and you get a checklist that matches exactly what your auditors look for.",
    },
    {
      c: "Case Notes & Documentation",
      t: "Case Note: Closing Summary",
      u: "A case is closing and you need a closing summary for the record.",
      p: `Act as a social worker writing a case closing summary. Details: reason for opening [REASON], services provided [SERVICES], goals and outcomes [GOALS AND WHAT WAS ACHIEVED], reason for closing [REASON, e.g. goals met, client moved, client declined], client's view of the work [IF KNOWN], referrals made at closing [REFERRALS], and how the client can re-engage [HOW]. Write it in under 300 words with headings, strengths-based and factual. ${DEID}`,
      tip: "Ask it to add a short plain-language closing letter to the client based on the same summary.",
    },

    // ── Client Communication ──
    {
      c: "Client Communication",
      t: "Letter: Plain-Language Appointment Letter",
      u: "You need to confirm an appointment in writing in a way that is easy to read for anyone.",
      p: `Write a short appointment letter to a client from a social worker at [AGENCY NAME]. Details: date and time [DATE AND TIME], place or format [LOCATION OR PHONE/VIDEO], what the meeting is for [PURPOSE], what to bring [DOCUMENTS], whether someone can come with them [YES/NO], and how to reschedule [CONTACT]. Write at a 6th-grade reading level, short sentences, warm and respectful, under 150 words. Offer help if they need an interpreter or accessibility support.`,
      tip: "Ask for the same letter in the client's preferred language, then have a qualified interpreter check it before sending.",
    },
    {
      c: "Client Communication",
      t: "Script: Explaining the Limits of Confidentiality",
      u: "You are meeting a new client and need to explain confidentiality honestly and clearly.",
      p: `Act as a social worker. Write a short script I can say at a first meeting to explain confidentiality in plain language. Cover: what stays private, when I have to share information (risk of serious harm to self or others, suspected abuse or neglect of a child or vulnerable adult, court orders), who else in the agency may see records [WHO], and how the client can ask questions. My setting: [SETTING, e.g. school, hospital, child welfare]. Keep it under 180 words, warm and honest, and end with a check for understanding question.`,
      tip: "Check the list of exceptions against your state law and agency policy; mandated reporting rules differ by state.",
    },
    {
      c: "Client Communication",
      t: "Message: Check-In Text After a Missed Appointment",
      u: "A client missed a meeting and you want to reach out without sounding punitive.",
      p: `Write two short, warm text messages (under 300 characters each) from a social worker to a client who missed an appointment on [DAY]. Message 1: a gentle check-in that shows concern, not blame, and offers two new times [TIMES]. Message 2: a follow-up for two days later if there is no reply, with another way to reach me [CONTACT METHOD]. No jargon, no mention of consequences unless I add them here: [ANY REQUIRED CONSEQUENCE].`,
      tip: "If there are real consequences, such as a court deadline, state them plainly and kindly in a separate message rather than hiding them.",
    },
    {
      c: "Client Communication",
      t: "Letter: Explaining a Decision the Client Disagrees With",
      u: "You have to communicate a decision (service change, denial, plan change) the client will not like.",
      p: `Act as an experienced social worker. Write a respectful letter to a client explaining this decision: [DECISION]. Reason for it: [REASON]. What it means for them in practice: [WHAT CHANGES]. Their options: [APPEAL OR REVIEW PROCESS AND DEADLINE]. Support available: [SUPPORT]. Be direct in the first two sentences, avoid jargon, acknowledge that it may be hard to hear, and keep it under 250 words. Do not blame the client.`,
      tip: "Always include the appeal deadline and how to use it. Clients often miss rights they did not know they had.",
    },
    {
      c: "Client Communication",
      t: "Explainer: What Happens Next in the Process",
      u: "A client is anxious about a process (assessment, court, benefits application) and wants to know what to expect.",
      p: `Write a plain-language explainer for a client about what happens next in [PROCESS]. Include the steps in order, roughly how long each takes [TIMELINE IF KNOWN], what they need to do at each step, what I will do, and who to call with questions [CONTACT]. Use short numbered steps and a reading level around 6th grade. Where timing is uncertain, say so honestly. Keep it to one page.`,
      tip: "Print it and go through it together. Written steps reduce anxiety and missed deadlines.",
    },
    {
      c: "Client Communication",
      t: "Message: Coordinating With a Family Member",
      u: "You need to share practical information with a family member the client has given consent to involve.",
      p: `Write a short, professional email from a social worker to a client's [RELATIONSHIP] who the client has given written consent to involve. Purpose: [PURPOSE, e.g. arrange a family meeting, share the next steps]. Share only this information: [WHAT THE CLIENT AGREED TO SHARE]. Ask for: [WHAT YOU NEED FROM THEM]. Keep it under 150 words, warm and respectful, and include how to reach me.`,
      tip: "Keep a note of exactly what the client consented to share, and only paste that into the prompt.",
    },
    {
      c: "Client Communication",
      t: "Script: Strengths-Based Conversation Opener",
      u: "You want to start a session in a way that builds trust and focuses on what the client is already doing well.",
      p: `Act as a social worker trained in strengths-based and motivational interviewing approaches. Give me 8 open questions I could use to start a session with a client who is [SITUATION, e.g. struggling with housing, a parent in a child welfare case]. Mix questions about what is going well, past successes, supports, and what they want. For each, add a one-line note on why it works and a follow-up reflection I could use.`,
      tip: "Pick two questions per session rather than working through the list; the follow-up reflection matters more than the question.",
    },

    // ── Assessment & Care Planning ──
    {
      c: "Assessment & Care Planning",
      t: "Plan: SMART Goals From a Client's Own Words",
      u: "You want goals for a service plan that the client actually recognises as theirs.",
      p: `Act as a social worker writing a service plan. The client said they want: [CLIENT'S WORDS ABOUT WHAT THEY WANT]. Their strengths and supports: [STRENGTHS]. Barriers: [BARRIERS]. Turn this into 3 SMART goals, each with 2 or 3 action steps, who is responsible (client, worker, other service), a target date [TIMEFRAME], and how we will know it is achieved. Keep the client's own language in the goal wording where possible. ${DEID}`,
      tip: "Read the goals back to the client and adjust the wording with them. Goals they helped write get worked on.",
    },
    {
      c: "Assessment & Care Planning",
      t: "Assessment: Organize Information Into a Biopsychosocial Summary",
      u: "You have gathered information and need to organize it into a structured assessment narrative.",
      p: `Act as a licensed social worker. Organize this de-identified information into a biopsychosocial assessment summary: [PASTE INFORMATION]. Sections: Presenting concern, Biological/health factors, Psychological factors, Social factors (family, housing, income, culture, community), Strengths and protective factors, Risk factors, Client's goals, Summary impression. Only use the information given; write [NOT ASSESSED] where a section has no information. Do not suggest diagnoses. ${DEID}`,
      tip: "The [NOT ASSESSED] markers double as your list of what to ask at the next contact.",
    },
    {
      c: "Assessment & Care Planning",
      t: "Map: Ecomap Description of Supports and Stressors",
      u: "You want to map a client's relationships and resources before care planning.",
      p: `Help me build an ecomap for a client. Here are the people, services and systems in their life, with notes on the relationship: [LIST, e.g. 'sister, supportive, weekly contact'; 'landlord, stressful, eviction notice']. Produce: a table with columns System, Type (family, friend, service, institution), Relationship (strong, tenuous, stressful), Direction of energy (gives, takes, both), Notes; then a short paragraph on the biggest sources of support and strain, and two ideas for strengthening supports. ${DEID}`,
      tip: "Draw the ecomap with the client using the table. It often surfaces a support nobody had mentioned.",
    },
    {
      c: "Assessment & Care Planning",
      t: "Plan: Update a Service Plan After a Review",
      u: "It is time to review and update a service plan based on progress.",
      p: `Act as a social worker updating a service plan. Current goals and steps: [PASTE CURRENT PLAN]. Progress since last review: [PROGRESS NOTES]. New issues or changes: [CHANGES]. Produce an updated plan: for each goal say Achieved, Continue, Revise or Close with a one-line reason; revise steps and dates where needed; add any new goal the notes support. Then write a 3-sentence summary of progress to share with the client. ${DEID}`,
      tip: "Celebrate achieved goals explicitly in the client summary; progress that goes unnoticed is easy to lose.",
    },
    {
      c: "Assessment & Care Planning",
      t: "Checklist: Questions for a Home Visit Assessment",
      u: "You are preparing for a first home visit and want a respectful, complete set of questions.",
      p: `Act as an experienced [SETTING, e.g. child welfare, adult protective, home care] social worker. Create a home visit guide with: what to observe (safety, basic needs, accessibility), conversational questions grouped by topic (daily routine, health, supports, finances, concerns), how to introduce the visit and its purpose, and how to close it with clear next steps. Keep questions open and respectful; avoid anything that sounds like an interrogation. Format as a one-page checklist.`,
      tip: "Add the specific assessment tool your agency requires so the guide lines up with the form you must complete.",
    },
    {
      c: "Assessment & Care Planning",
      t: "Plan: Discharge or Transition Plan",
      u: "A client is moving from one service or setting to another (hospital discharge, aging out, program exit).",
      p: `Act as a social worker writing a transition plan. Transition: from [CURRENT SETTING] to [NEXT SETTING] on around [DATE]. Needs: [HOUSING, HEALTH, INCOME, SUPPORT NEEDS]. Services arranged: [SERVICES]. Gaps: [GAPS]. Produce a plan with: needs and who will meet each, appointments and contacts (roles only), medications or supplies handover [IF RELEVANT], warning signs and what to do, and the first two weeks' actions day by day where possible. ${DEID}`,
      tip: "The first two weeks after a transition are where most plans fail. Put a check-in call in the plan on day 3.",
    },
    {
      c: "Assessment & Care Planning",
      t: "Summary: Cultural Considerations for Care Planning",
      u: "You want to make sure a plan respects the client's culture, faith and preferences.",
      p: `Act as a social worker committed to culturally responsive practice. Client background as they have described it: [CULTURE, LANGUAGE, FAITH, TRADITIONS, PREFERENCES]. Draft plan: [PASTE PLAN]. Review the plan and suggest: where it may clash with the client's values or practical realities, questions to ask the client to check (do not assume), culturally appropriate resources to explore [AREA], and adjustments to language or approach. Avoid stereotypes; frame everything as questions to confirm with the client.`,
      tip: "Use the output as a list of questions for the client, not as conclusions. The client is the expert on their culture.",
    },

    // ── Resources, Referrals & Benefits ──
    {
      c: "Resources, Referrals & Benefits",
      t: "Referral: Warm Referral Email to Another Service",
      u: "You are referring a client to another organization and want the referral to actually land.",
      p: `Write a referral email from a social worker at [AGENCY] to [RECEIVING SERVICE]. Client consent for this referral: [CONFIRM CONSENT GIVEN]. Reason for referral: [NEED]. Relevant background the client agreed to share: [INFORMATION]. What I am asking for: [SERVICE REQUESTED]. Urgency: [TIMEFRAME]. Best way to contact the client: [METHOD, CONTACT DETAILS ONLY IF CONSENTED]. Keep it under 200 words, specific, and ask them to confirm receipt and next steps.`,
      tip: "Call the service after sending. A referral with a phone call behind it is far more likely to result in an appointment.",
    },
    {
      c: "Resources, Referrals & Benefits",
      t: "Guide: Benefits Application Checklist",
      u: "A client is applying for a benefit and needs to know exactly what to gather.",
      p: `Create a plain-language checklist for a client applying for [BENEFIT PROGRAM] in [STATE/COUNTRY]. Include: documents usually needed, where to get each one if they do not have it, how to apply (online, phone, in person), what happens after applying, and how long decisions usually take. Mark anything that varies by location as 'check locally'. Keep it to one page, 6th-grade reading level. Note that eligibility is decided by the program, not by me.`,
      tip: "Always verify current rules on the program's official website; benefits rules change often and the AI may be out of date.",
    },
    {
      c: "Resources, Referrals & Benefits",
      t: "Resource List: Build a Local Resource Sheet",
      u: "You want a one-page list of resources for a common need in your area.",
      p: `Help me build a one-page resource sheet for clients who need [NEED, e.g. food, emergency housing, legal aid] in [CITY/COUNTY]. Here are the resources I know: [PASTE NAMES, WHAT THEY OFFER, HOURS, CONTACTS]. Organize them by type of help, add a one-line plain-language description of each, and include what to say when calling. Do not add organizations I have not listed; instead, list types of services I might be missing so I can research them.`,
      tip: "Date the sheet and review it quarterly. Out-of-date phone numbers are one of the fastest ways to lose a client's trust.",
    },
    {
      c: "Resources, Referrals & Benefits",
      t: "Letter: Supporting Letter for a Housing Application",
      u: "A client asked you for a letter supporting their housing application.",
      p: `Write a support letter from a social worker at [AGENCY] for a client applying for [HOUSING PROGRAM OR LANDLORD]. With the client's consent, include only: how long I have worked with them [DURATION], their engagement and progress [FACTS], relevant strengths (reliability, budgeting, support network) [FACTS], and supports in place that will help them keep a tenancy [SUPPORTS]. Professional tone, factual, under 250 words, no diagnoses or unnecessary personal detail. Include my role and contact details [DETAILS].`,
      tip: "Show the client the letter before sending. It is their story and they should be comfortable with it.",
    },
    {
      c: "Resources, Referrals & Benefits",
      t: "Advocacy: Email Challenging a Service Denial",
      u: "A client was denied a service and you are advocating for a review.",
      p: `Act as a social worker advocating for a client. Write a respectful, firm email to [ORGANIZATION] asking them to review a denial of [SERVICE]. Reason given for denial: [REASON]. Facts that support eligibility: [FACTS]. Relevant policy or criteria: [POLICY IF KNOWN]. What we are asking for: [REQUEST, e.g. reconsideration, a meeting, written reasons]. Deadline for appeal: [DATE]. Keep it under 250 words, factual, with a clear ask and a date for a response.`,
      tip: "Ask for the decision in writing if you do not have it; written reasons are what appeals are built on.",
    },
    {
      c: "Resources, Referrals & Benefits",
      t: "Guide: Budget Worksheet Conversation",
      u: "You are helping a client build a simple monthly budget.",
      p: `Create a simple monthly budget worksheet and a short guide for a social worker to use with a client. Worksheet: income sources, fixed costs, variable costs, debts, and the difference. Guide: 6 non-judgemental questions to walk through it, how to spot one realistic change, and where to refer for financial counseling [LOCAL OPTIONS IF KNOWN]. Plain language, respectful, and no assumptions about how the client should spend.`,
      tip: "Start with income and fixed costs only in the first session; a full budget in one sitting can feel overwhelming.",
    },
    {
      c: "Resources, Referrals & Benefits",
      t: "Follow-Up: Referral Tracking Message",
      u: "You made a referral a week ago and want to check it went through.",
      p: `Write two short follow-up messages. 1) To the receiving service: a polite check on referral [REFERRAL TYPE] sent on [DATE], asking whether contact has been made and what the next step is. 2) To the client: a warm check-in asking if they have heard from [SERVICE], offering help if not. Each under 100 words. ${DEID}`,
      tip: "Put referral follow-ups in your calendar the day you refer. Most referrals that fail do so silently.",
    },

    // ── Safety, Crisis & Risk ──
    {
      c: "Safety, Crisis & Risk",
      t: "Plan: Collaborative Safety Plan Draft",
      u: "You are working with a client on a safety plan and want a clear, client-owned document.",
      p: `Act as a trained social worker. Help me draft a safety plan to complete with the client, using this structure: warning signs they have identified [SIGNS], things they can do on their own to cope [STRATEGIES], people and places that help [SUPPORTS], people they can ask for help [PEOPLE, ROLES ONLY], professionals and crisis lines [INCLUDE 988 IN THE US OR YOUR LOCAL CRISIS LINE], and making the environment safer [STEPS]. Write it in the client's own words where given, plain language, one page. This is a draft for me to complete with the client under my agency's safety protocol. ${DEID}`,
      tip: "A safety plan works when the client writes it with you. Use this draft as a structure, not a finished plan.",
    },
    {
      c: "Safety, Crisis & Risk",
      t: "Checklist: After a Crisis Contact, What to Document",
      u: "You have just handled a crisis contact and need to make sure the documentation is complete.",
      p: `Act as a clinical supervisor. Give me a checklist of what to document after a crisis contact in a [SETTING] agency: time and nature of contact, risk factors and protective factors assessed, what the client said (quotes where relevant), actions taken and why, consultations (supervisor, emergency services), notifications made, safety plan status, and follow-up arranged. Add a short note on writing it objectively and promptly. Follow my agency's crisis protocol where it differs.`,
      tip: "Document the reasoning behind decisions, not just the decisions. 'Why' is what reviewers and courts look for.",
    },
    {
      c: "Safety, Crisis & Risk",
      t: "Script: Calm, Clear De-escalation Phrases",
      u: "You want to be prepared for a tense conversation that may escalate.",
      p: `Act as a trainer in de-escalation for social services staff. Give me 12 short phrases I can use when a client or family member is angry or distressed about [SITUATION]. Group them: acknowledging feelings, setting a calm limit, offering choices, and moving to next steps. For each, add what to avoid saying instead. Keep them natural, respectful and non-threatening.`,
      tip: "Practise the phrases out loud with a colleague. Under stress we use the words we have rehearsed.",
    },
    {
      c: "Safety, Crisis & Risk",
      t: "Guide: Worker Safety Plan for Home Visits",
      u: "You want to review your own safety practices before visits.",
      p: `Create a worker safety checklist for home visits in [SETTING]. Include: before the visit (information check, telling a colleague the plan, check-in times), arriving (scanning the environment, parking, exits), during the visit (positioning, when and how to end the visit), leaving and after (check-out, debrief, reporting incidents). Add a simple buddy check-in script. Align with my agency's lone worker policy: [POLICY POINTS IF KNOWN].`,
      tip: "Agree a code phrase with your office that means 'call me now' without alarming anyone in the room.",
    },
    {
      c: "Safety, Crisis & Risk",
      t: "Report: Structuring a Concern for a Mandated Report",
      u: "You need to organise the facts before making a mandated report.",
      p: `Act as an experienced social worker. Help me organise the facts for a report of suspected [TYPE, e.g. child abuse or neglect, elder abuse] before I call it in. Facts I have: [DE-IDENTIFIED FACTS]. Produce: a factual timeline, what I directly observed versus what I was told (and by whom, by role), any immediate safety concerns, and questions the hotline is likely to ask. Do not draw conclusions or add details. I will follow my state's reporting law and agency procedure for the report itself.`,
      tip: "Reporting duties and timeframes are set by state law. If in doubt, report and consult your supervisor; do not wait for certainty.",
    },
    {
      c: "Safety, Crisis & Risk",
      t: "Debrief: After a Difficult or Traumatic Contact",
      u: "You or your team need a structured debrief after a distressing situation.",
      p: `Create a 20-minute structured debrief guide for a social work team after a distressing incident involving [BRIEF, DE-IDENTIFIED DESCRIPTION]. Include: opening that sets a supportive tone, facts (what happened), thoughts and reactions, what went well, what we would do differently, support available (EAP, supervision), and actions. Add prompts for the facilitator and a note that participation is voluntary.`,
      tip: "Debrief within 72 hours, and follow up individually a week later. Reactions often show up after the first few days.",
    },
    {
      c: "Safety, Crisis & Risk",
      t: "Risk Summary: Protective and Risk Factors Table",
      u: "You want to summarise risk clearly for supervision or a case review.",
      p: `Organise this de-identified information into a risk summary table: [PASTE INFORMATION]. Columns: Factor, Type (risk or protective), Evidence (what was observed or reported, by whom by role), Current status, Action. Then write a 4-sentence summary for supervision covering the most significant risks, the strongest protective factors, and what would change the picture. Do not rate the overall risk; that is a professional judgement for me and my supervisor.`,
      tip: "Bring the table to supervision rather than a narrative; it makes gaps in information obvious.",
    },

    // ── Reports, Courts & Agencies ──
    {
      c: "Reports, Courts & Agencies",
      t: "Court Report: Structure a Court Report From Case Notes",
      u: "You have a court report due and need to turn case notes into a clear, organised report.",
      p: `Act as an experienced social worker preparing a report for [COURT TYPE, e.g. family court, dependency hearing]. From these de-identified notes: [PASTE NOTES], draft a report with: Purpose of report, Sources of information (by role), Background, Current situation, Progress against the court-ordered plan [PLAN ITEMS], Strengths, Concerns, and Recommendations (I will write the recommendations myself; leave a placeholder). Use facts and dates (month/year), separate observation from opinion, and avoid jargon.`,
      tip: "Courts value clear sourcing. Every significant statement should say who reported it or who observed it.",
    },
    {
      c: "Reports, Courts & Agencies",
      t: "Report: Quarterly Program Report to a Funder",
      u: "Your program owes a funder a quarterly report.",
      p: `Write a quarterly report for [FUNDER] about [PROGRAM]. Data: clients served [NUMBER], services delivered [LIST WITH NUMBERS], outcomes against targets [TARGETS AND ACTUALS], challenges [CHALLENGES], and one short anonymised client story (with consent) [STORY]. Structure: summary, outputs, outcomes, challenges and how we are responding, next quarter priorities. Keep it under 700 words and honest about shortfalls.`,
      tip: "Funders trust programs that report problems with a plan. Do not hide a missed target; explain it.",
    },
    {
      c: "Reports, Courts & Agencies",
      t: "Email: Professional Update to a Multi-Agency Team",
      u: "You need to update partners (school, health, housing) on a shared case.",
      p: `Write a concise update email for a multi-agency team working with client [INITIALS]. Share only what the client has consented to share: [INFORMATION]. Include: progress since last meeting, current concerns, actions for each agency by role [ACTIONS], and date of the next meeting [DATE]. Under 200 words, bullet points, neutral language.`,
      tip: "Use role titles consistently (for example 'school counselor') so the update still makes sense when staff change.",
    },
    {
      c: "Reports, Courts & Agencies",
      t: "Testimony Prep: Questions to Expect in Court",
      u: "You are giving evidence and want to prepare for questioning.",
      p: `Act as a social work supervisor preparing a worker to testify in [COURT TYPE]. Based on this summary of my involvement: [DE-IDENTIFIED SUMMARY], list 15 questions I am likely to be asked by each side, what each question is testing, and tips on answering (stick to facts, say 'I don't know' when true, refer to notes). Do not script answers; help me prepare to answer truthfully and clearly.`,
      tip: "Reread your own notes the night before. Most difficult questions are about what you wrote and when.",
    },
    {
      c: "Reports, Courts & Agencies",
      t: "Report: Incident Report",
      u: "Something happened that must be reported under agency policy.",
      p: `Write an incident report from these notes: [NOTES]. Sections: date, time and location (general), people involved (by role), what happened in order, immediate actions taken, injuries or harm (if any), notifications made (who and when), and follow-up required. Factual, past tense, no speculation or blame, under 300 words. ${DEID}`,
      tip: "Write it while memory is fresh. Add anything you were told as 'reported by [role]', not as fact.",
    },
    {
      c: "Reports, Courts & Agencies",
      t: "Letter: Response to a Records Request",
      u: "You need to respond to a request for records and want to check the steps.",
      p: `Act as a records coordinator for a social services agency. A request was received from [REQUESTER TYPE, e.g. client, attorney, another agency] for [RECORDS REQUESTED]. Give me: a checklist for handling it (verify identity and authority, check consent or court order, check what can be withheld under law and policy, redaction of third-party information, timelines), and a short template acknowledgement letter. Note that I will confirm the legal requirements with our privacy officer or counsel.`,
      tip: "Never release third-party information in a client's file without checking; redaction is where most privacy mistakes happen.",
    },
    {
      c: "Reports, Courts & Agencies",
      t: "Summary: Case Review Presentation",
      u: "You are presenting a case at a review meeting and have five minutes.",
      p: `Help me prepare a 5-minute case presentation for a [REVIEW TYPE, e.g. team case review, panel] from these de-identified notes: [NOTES]. Structure: one-sentence summary, key history (3 bullets), current situation, what is working, the dilemma or question I am bringing, and what I need from the group. Add 3 questions the group might ask so I can prepare.`,
      tip: "Lead with the question you need help with. Reviews go better when the group knows what it is solving.",
    },

    // ── Supervision, Teams & Self-Care ──
    {
      c: "Supervision, Teams & Self-Care",
      t: "Supervision: Agenda for Reflective Supervision",
      u: "You want to get more out of supervision.",
      p: `Create a reflective supervision agenda for a [ROLE] with a caseload of about [NUMBER]. Include: cases needing decisions (up to 3), a case I want to reflect on (what happened, my reaction, what I learned), workload and wellbeing check, professional development, and actions. Add 6 reflective questions a supervisor might ask. One page.`,
      tip: "Send the agenda to your supervisor a day ahead so the time goes to thinking, not catching up.",
    },
    {
      c: "Supervision, Teams & Self-Care",
      t: "Self-Care: Burnout Check and Weekly Plan",
      u: "You are feeling stretched and want a practical plan, not platitudes.",
      p: `Act as a coach experienced with helping professionals. I work as a [ROLE] with [CASELOAD OR HOURS]. Signs I am noticing: [SIGNS]. What drains me most: [DRAINS]. What restores me: [RESTORERS]. Create a realistic weekly plan with 3 boundaries I can hold at work, 3 small daily practices under 10 minutes, one conversation to have with my supervisor, and signs that mean I should seek more support (for example the EAP or a counselor).`,
      tip: "Pick one boundary and one practice for the first week. Plans that try to change everything rarely last.",
    },
    {
      c: "Supervision, Teams & Self-Care",
      t: "Team: Case Allocation Discussion Guide",
      u: "You manage a team and need to discuss caseload allocation fairly.",
      p: `Act as a social work team manager. Create a guide for a caseload allocation meeting: criteria to consider (case complexity, travel, worker experience and specialisms, current load, wellbeing), a simple weighting table I can fill in for [NUMBER] workers, and a script for discussing workload honestly with the team. Current pressures: [PRESSURES].`,
      tip: "Weight complexity, not just numbers. Ten simple cases and ten complex cases are not the same caseload.",
    },
    {
      c: "Supervision, Teams & Self-Care",
      t: "Training: New Worker Orientation Plan",
      u: "A new social worker is joining the team and you want a structured first month.",
      p: `Create a 4-week orientation plan for a new [ROLE] joining a [SETTING] team. Include: week-by-week goals, shadowing and supervised visits, key policies to read [LIST IF KNOWN], systems training, when they take their first cases, check-ins with their supervisor, and a checklist of competencies to sign off. Realistic for a busy team.`,
      tip: "Give new workers one 'easy' case early. Confidence built in the first month shapes whether people stay.",
    },
    {
      c: "Supervision, Teams & Self-Care",
      t: "Team: Peer Consultation Group Format",
      u: "You want to start a peer consultation group that people actually find useful.",
      p: `Design a 60-minute monthly peer consultation format for [NUMBER] social workers. Include: ground rules (confidentiality, respect, de-identified cases), a presenting structure (case summary, question, clarifying questions, group reflections, presenter response), time for each part, a rotating facilitator role, and how to capture learning. Add 5 good reflection prompts.`,
      tip: "The presenter should only listen during group reflections, then respond. It changes what they hear.",
    },
    {
      c: "Supervision, Teams & Self-Care",
      t: "Email: Asking for Support With Workload",
      u: "Your caseload is unsafe and you need to raise it in writing.",
      p: `Write a professional email to my supervisor raising concern about my workload. Facts: current caseload [NUMBER AND COMPLEXITY], tasks overdue [LIST], risks this creates [RISKS, e.g. visits not meeting required frequency], and what I have already tried [STEPS]. Ask for a meeting and suggest options [OPTIONS, e.g. reallocation, temporary support]. Calm, factual, under 200 words.`,
      tip: "Put workload concerns in writing. It protects clients and it protects you.",
    },
    {
      c: "Supervision, Teams & Self-Care",
      t: "Reflection: Ethical Dilemma Worksheet",
      u: "You are facing an ethical dilemma and want to think it through systematically.",
      p: `Act as an ethics consultant for social workers. Help me work through this dilemma: [DE-IDENTIFIED DESCRIPTION]. Structure: the competing values and duties involved, relevant standards in the NASW Code of Ethics (name the sections), options available, likely consequences of each for the client and others, who to consult, and how to document the decision. Do not decide for me; lay out the reasoning.`,
      tip: "Bring the worksheet to supervision. Documented ethical reasoning is part of good practice, not extra paperwork.",
    },

    // ── Community Outreach & Programs ──
    {
      c: "Community Outreach & Programs",
      t: "Flyer: Program Flyer in Plain Language",
      u: "You need a flyer that people will actually read and act on.",
      p: `Write a one-page flyer for [PROGRAM] run by [AGENCY]. Who it is for: [AUDIENCE]. What it offers: [SERVICES]. Cost: [COST OR FREE]. How to join: [HOW, WHERE, WHEN]. Language support: [LANGUAGES]. Headline under 8 words, three short benefit bullets, one clear call to action, 6th-grade reading level, warm and respectful. Avoid words like 'at-risk' or 'vulnerable' that people may not want to identify with.`,
      tip: "Test the flyer with two people from the audience before printing. They will tell you which words put them off.",
    },
    {
      c: "Community Outreach & Programs",
      t: "Program: Logic Model for a New Program",
      u: "You are designing a program or applying for funding and need a logic model.",
      p: `Act as a program evaluator. Build a logic model for [PROGRAM] that aims to [GOAL] for [POPULATION]. Include: inputs, activities, outputs (with realistic numbers I can adjust), short-term outcomes, medium-term outcomes, long-term impact, assumptions and external factors. Then suggest 2 measurable indicators per outcome and how to collect them without burdening clients.`,
      tip: "Keep outcomes to what you can realistically measure. Funders prefer three honest indicators to ten you cannot track.",
    },
    {
      c: "Community Outreach & Programs",
      t: "Outreach: Partnership Email to a Community Organization",
      u: "You want to partner with a church, school or community group to reach people.",
      p: `Write an email from [ROLE] at [AGENCY] to [ORGANIZATION] proposing a partnership. What we offer: [SERVICES]. Why it helps their community: [BENEFIT]. What we would ask of them: [ASK, e.g. host a session, share a flyer]. Time commitment: [TIME]. Suggest a short meeting. Under 180 words, respectful, no jargon.`,
      tip: "Offer something first, such as a free workshop for their members. Partnerships built on giving last longer.",
    },
    {
      c: "Community Outreach & Programs",
      t: "Workshop: Community Workshop Plan",
      u: "You are running a workshop for community members on a practical topic.",
      p: `Plan a [LENGTH, e.g. 60-minute] community workshop on [TOPIC, e.g. understanding tenant rights, managing stress] for [AUDIENCE]. Include: learning goals, a welcoming opening, 3 short sections with an activity each, a take-home handout outline, how to handle personal disclosures in a group, and where to signpost for individual help [LOCAL SERVICES]. Plain language and interactive.`,
      tip: "Have a private way for people to ask for individual help at the end; many will not ask in front of the group.",
    },
    {
      c: "Community Outreach & Programs",
      t: "Survey: Client Feedback Survey",
      u: "You want honest feedback on your service that you can act on.",
      p: `Design a short client feedback survey (under 10 questions) for [SERVICE]. Mix rating questions and open questions. Cover: access, respect, clarity of information, whether things improved for them, and suggestions. Use plain language, make it anonymous, and add a line explaining how feedback will be used. Also suggest how to collect it from people with low literacy or no internet.`,
      tip: "Share back 'You said, we did' with clients. Response rates rise when people see feedback used.",
    },
    {
      c: "Community Outreach & Programs",
      t: "Social Post: Awareness Post for a Service",
      u: "You want a social media post that raises awareness without stigma.",
      p: `Write 3 social media posts for [AGENCY] promoting [SERVICE] to [AUDIENCE]. Each under 60 words, hopeful, stigma-free, with a clear call to action [HOW TO ACCESS]. One post should include a question to encourage engagement. No client stories or photos unless consent is noted: [CONSENT STATUS]. Add alt text for a suggested image.`,
      tip: "Never use a real client's story or image without written consent, even if they are happy to share in person.",
    },
    {
      c: "Community Outreach & Programs",
      t: "Proposal: One-Page Program Pitch for Leadership",
      u: "You have an idea for a new service and need leadership approval.",
      p: `Write a one-page proposal for [NEW SERVICE OR CHANGE] to present to agency leadership. Include: the need (with any data I have [DATA]), the proposal, who benefits, resources needed [STAFF, BUDGET], risks and how to manage them, how we will measure success, and a pilot option. Persuasive but honest, under 450 words.`,
      tip: "Offer a small pilot. Leaders say yes to a 3-month test far more easily than to a permanent program.",
    },
  ],
};
