// Extracted from app/api/blog/auto-refresh/route.ts.
//
// That route was 3,258 lines, of which 2,546 were this content. The logic it
// actually performs is a few hundred lines and was impossible to review with
// a thousand lines of article prose sitting in the middle of it. Moving the
// data out changes nothing at runtime; it just makes the route readable.

export const CATEGORY_TOPIC_BANK: Record<string, string[]> = {
  "breaking": [
    "OpenAI Releases o3: What the New Reasoning Model Means for Business AI",
    "Google Gemini 2.0 Flash Reshapes What Fast AI Means for Businesses",
    "Anthropic Raises Series E: Why the Investment Signals AI's Next Chapter",
    "Meta Open-Sources Llama 4: How Free Frontier AI Changes the Cost of Building",
    "The EU AI Act Is Fully in Force: Your Business Compliance Checklist",
    "Microsoft Copilot Studio Gets Agentic Capabilities: What's Now Possible",
    "Apple Intelligence Expands to More Devices: Business Workflows That Benefit",
    "Nvidia's Blackwell Architecture Explained: Why It Matters for AI Pricing",
    "OpenAI Launches Projects and Memory: The Upgrade That Changes How You Use ChatGPT",
    "Sam Altman Predicts AGI Within 5 Years: What It Means If He's Right",
    "Google Announces AI-Powered Search Overhaul: The New Visibility Rules for Businesses",
    "DeepSeek R2 Arrives: Another Model That Outperforms at a Fraction of the Cost",
    "OpenAI's Operator Agent Browses the Web Autonomously: First Business Applications",
    "The US AI Executive Order: New Rules Every Business Deploying AI Must Know",
    "Perplexity AI Launches Business Tier: Is the Research Assistant Now Enterprise-Ready?",
    "AI Trading Algorithms Now Control 70% of Market Volume: What It Means for Investors",
    "Federal Reserve Uses AI for Economic Forecasting: The New Playbook for Rate Decisions",
    "S&P 500 AI Index Outperforms Benchmarks by 40%: The Sectors Leading the Rally",
    "Wall Street's AI Arms Race: How Goldman, JPMorgan, and BlackRock Are Restructuring Around AI",
    "AI-Driven Recession Predictions: What the Models Are Saying That Economists Are Missing",
  ],
  "ai-business": [
    "How to Build an AI-Powered Lead Qualification System Without a CRM Upgrade",
    "AI for Accounts Receivable: Cutting Payment Delays and Chasing Invoices Automatically",
    "Building an AI Employee Onboarding System That Works While You Sleep",
    "How AI Is Transforming Customer Retention for Subscription Businesses",
    "AI Competitive Intelligence: How Small Businesses Track Rivals Without a Research Team",
    "Using AI to Write Better Proposals and Win More Business",
    "AI-Powered Performance Reviews: Saving HR Time While Improving Consistency",
    "How AI Is Changing Pricing Strategy for Small and Mid-Sized Businesses",
    "Using AI to Manage and Triage Business Email at Scale",
    "How to Build a Revenue Intelligence System With AI and Your Existing CRM",
    "AI for Business Development: Finding and Qualifying Opportunities Faster",
    "The AI Customer Success Stack: Tools That Reduce Churn Without Adding Headcount",
    "How AI Is Eliminating the Weekly Status Meeting",
    "AI-Generated Business Reports: Getting Weekly Insights Without Weekly Labor",
    "Using AI to Systemize and Document Your Business Processes",
  ],
  "tips": [
    "The 5 Prompt Patterns That Produce Consistently Better Business AI Output",
    "How to Build a Personal AI Assistant Using Claude Projects",
    "The AI Workflow Stack Every Freelancer Should Have Running by Next Week",
    "How to Use Perplexity AI to Research Competitors in Under 10 Minutes",
    "Building a Daily AI Briefing That Keeps You Current Without the Noise",
    "How to Evaluate Any AI Tool in 30 Minutes Before Committing",
    "Writing System Prompts That Make Your AI Consistent and On-Brand",
    "How to Use AI to Produce a Month of Content in a Single Afternoon",
    "The Anti-Hallucination Checklist: Verifying AI Output Before You Use It",
    "How to Introduce AI Tools to a Skeptical Team Without Losing Buy-In",
    "Building a Prompt Library Your Whole Team Can Use and Trust",
    "How to Use AI to Speed Up Your Weekly Reporting by 80 Percent",
    "Getting Consistent AI Results: The Role Task Context Constraint Framework",
    "How to Automate Your Most Time-Consuming Business Task This Week",
    "AI Output Editing: The Fast Workflow That Makes AI Writing Sound Human",
  ],
  "tools": [
    "Notion AI vs. Coda AI: Which Document Intelligence Tool Wins for Small Teams?",
    "The Best AI Tools for Business Writing in 2026: An Honest Comparison",
    "AI Legal Research Tools That Help Non-Lawyers Navigate Contracts",
    "Descript vs. Otter.ai vs. Fireflies: Which Meeting AI Is Worth Paying For?",
    "The Best AI Image Generation Tools for Business Marketing in 2026",
    "HubSpot AI Features vs. Zoho Zia: Which CRM AI Actually Helps Sales?",
    "AI Bookkeeping Tools That Handle the Work Your Accountant Bills You For",
    "The Best Free AI Tools for Small Business Owners Right Now",
    "Canva AI vs. Adobe Firefly: Which Design AI Delivers More for Non-Designers?",
    "AI Social Media Tools That Actually Save Time and Maintain Brand Voice",
    "Make vs. Zapier in 2026: Which Automation Platform Has Pulled Ahead?",
    "The Best AI Writing Assistants for Email and Business Communication",
    "AI Proposal and Quoting Tools for Service Businesses",
    "Google NotebookLM for Business: Building a Queryable Knowledge Base for Free",
    "Voice AI for Business: Tools That Handle Calls and Meetings Intelligently",
  ],
  "case-studies": [
    "How a Physical Therapy Clinic Reduced No-Shows by 60 Percent With AI Scheduling",
    "How a Real Estate Agency Qualified 10x More Leads Using an AI Pre-Screener",
    "A Trucking Company Cut Fuel Costs 18 Percent Using AI Route Optimization",
    "How an E-Commerce Brand Doubled Email Revenue With AI Personalization",
    "A Construction Firm Reduced Bid Preparation Time by 70 Percent With AI",
    "How a Dental Practice Automated Patient Communications and Grew 40 Percent",
    "A Law Firm Automated Contract Review and Recovered 60 Attorney Hours Per Month",
    "How a Caribbean Logistics Business Handled 78 Percent of Inquiries With an AI Agent",
    "A Training Company Used AI Tutoring and Improved Student Pass Rates by 35 Percent",
    "How an HR Consulting Firm Automated Compliance Reporting and Won New Retainers",
    "A Gym Chain Reduced Member Churn by 22 Percent Using AI Engagement Predictions",
    "How a Caribbean Logistics Operator Scaled Throughput 40 Percent Without New Hires",
    "A Financial Advisory Firm Used AI to Prepare Reports 4x Faster With Higher Quality",
    "How a Boutique Hotel Increased Direct Bookings Using AI Personalized Offers",
    "A Tech Recruiting Firm Cut Time-to-Hire by 50 Percent With AI Resume Screening",
  ],
  "industry": [
    "The State of AI Adoption in Professional Services: 2026 Benchmarks",
    "How AI Is Reshaping the Future of Remote and Hybrid Work",
    "AI in Retail: From Inventory Optimization to Personalized Shopping Experiences",
    "The AI Skills Gap Is Growing: What Business Leaders Must Do in the Next 12 Months",
    "How AI Is Transforming the Healthcare Revenue Cycle",
    "AI and Cybersecurity: How Businesses Are Fighting AI-Powered Attacks With AI",
    "The Rise of Agentic AI: What's Actually Deployed vs. What's Still Hype",
    "AI in Financial Services: The Tools That Are Changing How Money Moves",
    "How AI Is Disrupting the Insurance Industry From Claims to Customer Experience",
    "The Creator Economy and AI: New Business Models Emerging From the Shift",
    "AI in Real Estate: How Agents Brokers and Developers Are Adapting",
    "How AI Is Changing Supply Chain Resilience for Mid-Market Businesses",
    "The Impact of AI on Customer Expectations: The New Service Standard",
    "AI and the Future of Professional Learning and Development",
    "How African Businesses Are Leapfrogging Legacy Systems With AI-First Operations",
    "How AI Is Reshaping Stock Market Analysis and Portfolio Management in 2026",
    "AI and the Global Economy: What Labor Market Data Is Telling Us About Automation",
    "The AI Wealth Gap: How Artificial Intelligence Is Concentrating Economic Power",
    "How AI Is Changing Inflation Forecasting and Monetary Policy for Central Banks",
    "AI and Trade: How Tariff Modeling and Supply Chain AI Are Reshaping Global Commerce",
  ],
};

export const CATEGORY_META: Record<string, { emoji: string; gradient: string }> = {
  "breaking":    { emoji: "⚡", gradient: "from-red-600 to-orange-500" },
  "ai-business": { emoji: "💼", gradient: "from-[#1B3A6B] to-[#2251A3]" },
  "tips":        { emoji: "💡", gradient: "from-purple-600 to-violet-500" },
  "tools":       { emoji: "🔧", gradient: "from-teal-600 to-emerald-500" },
  "case-studies":{ emoji: "📊", gradient: "from-[#F47C20] to-yellow-500" },
  "industry":    { emoji: "🌐", gradient: "from-slate-600 to-gray-500" },
};
