// Spot the Risk decks, in English, French and Swahili. Each card is something
// a person is about to do or share. Keep facts general and accurate, with no
// invented statistics. Names, numbers and codes in cards are made up.

import { l3, type L3 } from "../sorter/kit";

export type RiskType = "privacy" | "security" | "fact" | "bias" | "child" | "legal";
export const RISK_TYPES: RiskType[] = ["privacy", "security", "fact", "bias", "child", "legal"];
export const RISK_ICON: Record<RiskType, string> = {
  privacy: "🔒",
  security: "🛡️",
  fact: "🔎",
  bias: "⚖️",
  child: "🧸",
  legal: "📜",
};

/** What the card shows, for its little label. */
export type Kind = "paste" | "reply" | "code" | "claim" | "step" | "message";
export const KIND_ICON: Record<Kind, string> = {
  paste: "💬",
  reply: "🤖",
  code: "💻",
  claim: "📣",
  step: "🧭",
  message: "📩",
};

export interface RiskCard {
  id: string;
  kind: Kind;
  text: L3;
  /** Code shown as-is (not translated). */
  code?: string;
  safe: boolean;
  /** Accepted risk types when risky; the first is the main one. */
  types: RiskType[];
  why: L3;
}

export interface RiskDeck {
  id: string;
  icon: string;
  difficulty: 1 | 2 | 3;
  cards: RiskCard[];
}

type T = readonly [string, string, string];
const safe = (id: string, kind: Kind, text: T, why: T, code?: string): RiskCard => ({ id, kind, text: l3(text), code, safe: true, types: [], why: l3(why) });
const risky = (id: string, kind: Kind, types: RiskType[], text: T, why: T, code?: string): RiskCard => ({ id, kind, text: l3(text), code, safe: false, types, why: l3(why) });

export const RISK_DECKS: RiskDeck[] = [
  {
    id: "privacy",
    icon: "🔒",
    difficulty: 1,
    cards: [
      safe("p1", "paste",
        ["\"Rewrite this to sound friendlier: 'Hi team, the Friday meeting moves to 3 pm.'\"", "« Rends ce message plus chaleureux : \"Bonjour à tous, la réunion de vendredi passe à 15 h.\" »", "\"Andika upya ili isikike ya kirafiki: 'Habari timu, mkutano wa Ijumaa umehamia saa tisa alasiri.'\""],
        ["No personal or confidential data, and a low-stakes task.", "Aucune donnée personnelle ou confidentielle, et une tâche sans enjeu.", "Hakuna data binafsi wala za siri, na ni kazi isiyo na hatari."]),
      risky("p2", "paste", ["privacy"],
        ["\"Check my visa form: passport P4829173, born 12/03/1988, home address 14 Baobab Road.\"", "« Vérifie mon formulaire de visa : passeport P4829173, né le 12/03/1988, domicile 14 rue des Baobabs. »", "\"Kagua fomu yangu ya viza: pasipoti P4829173, nilizaliwa 12/03/1988, anwani 14 Barabara ya Mbuyu.\""],
        ["ID numbers, date of birth and address together help identity thieves. Replace them with placeholders like [PASSPORT] first.", "Numéro d'identité, date de naissance et adresse réunis aident les usurpateurs. Remplacez-les d'abord par des repères comme [PASSEPORT].", "Namba za utambulisho, tarehe ya kuzaliwa na anwani kwa pamoja huwasaidia wezi wa utambulisho. Zibadilishe kwanza kwa alama kama [PASIPOTI]."]),
      safe("p3", "paste",
        ["\"Summarise this public news article about healthy sleep habits.\"", "« Résume cet article de presse public sur les bonnes habitudes de sommeil. »", "\"Fupisha makala hii ya habari ya umma kuhusu tabia nzuri za kulala.\""],
        ["Public information, nothing private. Still skim the summary for mistakes.", "Information publique, rien de privé. Relisez quand même le résumé.", "Taarifa za umma, hakuna cha binafsi. Hata hivyo pitia muhtasari kuona makosa."]),
      risky("p4", "paste", ["security", "privacy"],
        ["\"My bank login is jdoe88 and my password is Sunflower!22. Why won't it let me in?\"", "« Mon identifiant bancaire est jdoe88 et mon mot de passe Tournesol!22. Pourquoi ça ne marche pas ? »", "\"Jina langu la benki ni jdoe88 na nenosiri ni Alizeti!22. Kwa nini haliingii?\""],
        ["Never share a password with any chatbot or person. Use the bank's official reset and change the password now.", "Ne partagez jamais un mot de passe avec un chatbot ou une personne. Utilisez la réinitialisation officielle de la banque et changez-le maintenant.", "Usishiriki nenosiri na chatbot wala mtu yeyote. Tumia njia rasmi ya benki kulibadilisha, na libadilishe sasa."]),
      safe("p5", "paste",
        ["\"Help me write a birthday message for my sister who loves hiking.\"", "« Aide-moi à écrire un message d'anniversaire pour ma sœur qui adore la randonnée. »", "\"Nisaidie kuandika ujumbe wa siku ya kuzaliwa kwa dada yangu anayependa kupanda milima.\""],
        ["A friendly, low-risk request with no sensitive details.", "Une demande sympathique, sans risque ni détail sensible.", "Ombi la kirafiki lisilo na hatari wala taarifa nyeti."]),
      risky("p6", "paste", ["privacy", "security"],
        ["\"Card 4000 1234 5678 9010, expiry 08/28, security code 123. Does it work abroad?\"", "« Carte 4000 1234 5678 9010, expiration 08/28, code 123. Est-ce qu'elle marche à l'étranger ? »", "\"Kadi 4000 1234 5678 9010, inaisha 08/28, namba ya usalama 123. Inafanya kazi nje ya nchi?\""],
        ["Full card details are all a fraudster needs. Ask the general question, or call your bank.", "Les données complètes d'une carte suffisent à un fraudeur. Posez la question en général ou appelez votre banque.", "Taarifa kamili za kadi ndizo mlaghai anahitaji. Uliza swali kwa ujumla, au piga simu benki yako."]),
      risky("p7", "paste", ["privacy"],
        ["\"My neighbour Grace Otieno at 22 Mango Street has depression. How can I help her?\"", "« Ma voisine Grace Otieno, au 22 rue des Manguiers, est dépressive. Comment l'aider ? »", "\"Jirani yangu Grace Otieno wa Mtaa wa Maembe namba 22 ana msongo wa mawazo. Nimsaidieje?\""],
        ["That is someone else's health information with her name and address. Ask the general question without identifying her.", "Ce sont des données de santé d'une autre personne, avec nom et adresse. Posez la question sans l'identifier.", "Hizo ni taarifa za afya za mtu mwingine pamoja na jina na anwani. Uliza swali la jumla bila kumtambulisha."]),
      safe("p8", "paste",
        ["\"Explain what a VPN does in simple words.\"", "« Explique simplement à quoi sert un VPN. »", "\"Eleza kwa maneno rahisi VPN inafanya nini.\""],
        ["A general knowledge question with no personal data.", "Une question de culture générale, sans donnée personnelle.", "Swali la maarifa ya jumla bila data binafsi."]),
      safe("p9", "paste",
        ["\"Proofread my CV. I replaced my phone, email and address with [PHONE], [EMAIL], [ADDRESS].\"", "« Relis mon CV. J'ai remplacé téléphone, e-mail et adresse par [TÉLÉPHONE], [E-MAIL], [ADRESSE]. »", "\"Sahihisha CV yangu. Nimebadilisha simu, email na anwani kwa [SIMU], [EMAIL], [ANWANI].\""],
        ["Placeholders keep contact details private while you still get help. Good habit.", "Les repères gardent les coordonnées privées tout en obtenant de l'aide. Bonne habitude.", "Alama hizi zinalinda mawasiliano yako huku ukipata msaada. Tabia nzuri."]),
      risky("p10", "paste", ["privacy"],
        ["\"Here are my blood test results with my full name and hospital ID. What do they mean?\"", "« Voici mes analyses de sang avec mon nom complet et mon numéro de patient. Qu'est-ce que ça veut dire ? »", "\"Haya ni majibu ya kipimo changu cha damu yenye jina kamili na namba ya hospitali. Yanamaanisha nini?\""],
        ["Health data is sensitive. Remove your name and ID, and ask a doctor to interpret results.", "Les données de santé sont sensibles. Retirez nom et numéro, et demandez à un médecin d'interpréter les résultats.", "Data za afya ni nyeti. Ondoa jina na namba, na umwombe daktari akueleze majibu."]),
      risky("p11", "step", ["security", "privacy"],
        ["A browser extension that summarises pages asks to \"read and change all your data on all websites\".", "Une extension de navigateur qui résume les pages demande à « lire et modifier toutes vos données sur tous les sites ».", "Kiendelezi cha kivinjari kinachofupisha kurasa kinaomba \"kusoma na kubadilisha data zako zote kwenye tovuti zote\"."],
        ["Broad permissions let an extension see everything you type, including passwords. Install only trusted extensions.", "Des droits aussi larges permettent de voir tout ce que vous tapez, y compris les mots de passe. N'installez que des extensions de confiance.", "Ruhusa pana hivyo zinaruhusu kuona kila unachoandika, hata nenosiri. Weka viendelezi vinavyoaminika tu."]),
      safe("p12", "paste",
        ["\"Plan a 3-day trip to Zanzibar for two adults on a mid-range budget.\"", "« Organise un séjour de 3 jours à Zanzibar pour deux adultes avec un budget moyen. »", "\"Panga safari ya siku 3 Zanzibar kwa watu wazima wawili kwa bajeti ya wastani.\""],
        ["Nothing private. Check prices and opening times yourself before booking.", "Rien de privé. Vérifiez vous-même les prix et horaires avant de réserver.", "Hakuna cha binafsi. Hakikisha bei na saa za kufungua kabla ya kulipia."]),
      risky("p13", "paste", ["security"],
        ["\"My bank just texted me a 6-digit code: 482 915. What is it for?\"", "« Ma banque vient de m'envoyer un code à 6 chiffres : 482 915. À quoi sert-il ? »", "\"Benki imenitumia namba ya tarakimu 6: 482 915. Ni ya nini?\""],
        ["One-time codes are keys to your account. Never share them; if you did not ask for it, contact your bank.", "Les codes à usage unique sont des clés de votre compte. Ne les partagez jamais ; si vous ne l'avez pas demandé, contactez votre banque.", "Namba za matumizi mara moja ni funguo za akaunti yako. Usizishiriki kamwe; kama hukuiomba, wasiliana na benki."]),
      safe("p14", "step",
        ["Before pasting a document, you check the tool's data settings and remove names.", "Avant de coller un document, vous vérifiez les réglages de données de l'outil et retirez les noms.", "Kabla ya kubandika hati, unakagua mipangilio ya data ya zana na kuondoa majina."],
        ["Exactly the right habit: know where data goes and share the minimum.", "Exactement le bon réflexe : savoir où vont les données et partager le minimum.", "Hiyo ndiyo tabia sahihi: jua data inaenda wapi na shiriki kiasi kidogo tu."]),
    ],
  },
  {
    id: "kids",
    icon: "🧸",
    difficulty: 1,
    cards: [
      safe("k1", "reply",
        ["Child: \"Why is the sky blue?\" AI: \"Sunlight has all the colours. Air scatters blue light more than the others, so blue reaches your eyes from all over the sky!\"", "Enfant : « Pourquoi le ciel est bleu ? » IA : « La lumière du soleil contient toutes les couleurs. L'air disperse plus le bleu que les autres, alors le bleu arrive de partout dans le ciel ! »", "Mtoto: \"Kwa nini anga ni la bluu?\" AI: \"Mwanga wa jua una rangi zote. Hewa inatawanya bluu kuliko rangi nyingine, hivyo bluu inafika machoni kutoka kila upande wa anga!\""],
        ["Accurate, simple and friendly. A good answer.", "Exact, simple et bienveillant. Une bonne réponse.", "Sahihi, rahisi na ya kirafiki. Jibu zuri."]),
      risky("k2", "reply", ["child"],
        ["Child: \"Mum is at work. Where should I meet my new online friend?\" AI: \"A park near your house is a great place to meet!\"", "Enfant : « Maman travaille. Où je peux retrouver mon nouvel ami d'Internet ? » IA : « Un parc près de chez toi, c'est parfait ! »", "Mtoto: \"Mama yuko kazini. Nikutane wapi na rafiki yangu mpya wa mtandaoni?\" AI: \"Bustani karibu na nyumbani ni mahali pazuri!\""],
        ["A safe reply says not to meet online contacts alone and to tell a trusted adult.", "Une réponse sûre dirait de ne pas rencontrer seul un contact d'Internet et d'en parler à un adulte de confiance.", "Jibu salama lingesema asikutane peke yake na mtu wa mtandaoni na amwambie mtu mzima anayemwamini."]),
      risky("k3", "reply", ["child", "privacy"],
        ["AI to a child: \"Tell me your full name, school and home address so I can make your story extra personal!\"", "IA à un enfant : « Dis-moi ton nom complet, ton école et ton adresse pour que ton histoire soit vraiment personnalisée ! »", "AI kwa mtoto: \"Niambie jina lako kamili, shule na anwani ya nyumbani ili hadithi yako iwe yako kabisa!\""],
        ["Children should never be asked for identifying details. A story needs none of them.", "On ne doit jamais demander à un enfant des informations qui l'identifient. Une histoire n'en a pas besoin.", "Watoto hawapaswi kuombwa taarifa za kuwatambulisha. Hadithi haihitaji hizo."]),
      safe("k4", "reply",
        ["Child: \"I feel sad and nobody likes me.\" AI: \"I'm sorry you feel sad. Your feelings matter. Can you tell a parent, teacher or another adult you trust today?\"", "Enfant : « Je suis triste et personne ne m'aime. » IA : « Je suis désolé que tu sois triste. Ce que tu ressens compte. Peux-tu en parler aujourd'hui à un parent, un enseignant ou un autre adulte de confiance ? »", "Mtoto: \"Nina huzuni na hakuna anayenipenda.\" AI: \"Pole kwa huzuni yako. Hisia zako ni muhimu. Unaweza kumwambia mzazi, mwalimu au mtu mzima mwingine unayemwamini leo?\""],
        ["Kind, and it points the child to a trusted adult. That is what we want.", "Bienveillant, et oriente l'enfant vers un adulte de confiance. C'est ce qu'on attend.", "Ni jibu la upole na linamwelekeza mtoto kwa mtu mzima anayemwamini. Ndivyo tunavyotaka."]),
      risky("k5", "message", ["child"],
        ["Stranger in a game chat: \"Let's keep our chats secret from your parents. I'll give you free coins.\"", "Un inconnu dans le chat d'un jeu : « Gardons nos discussions secrètes pour tes parents. Je te donnerai des pièces gratuites. »", "Mgeni kwenye soga ya mchezo: \"Tuweke mazungumzo yetu siri kwa wazazi wako. Nitakupa sarafu za bure.\""],
        ["Secrets plus gifts are classic warning signs of grooming. Tell a trusted adult, block and report.", "Secret et cadeaux sont des signaux d'alerte classiques de manipulation. Prévenir un adulte, bloquer et signaler.", "Siri pamoja na zawadi ni ishara za hatari za kumrubuni mtoto. Mwambie mtu mzima, zuia na ripoti."]),
      risky("k6", "reply", ["fact", "child"],
        ["Child: \"Can I eat the mushrooms in our garden?\" AI: \"Yes, most garden mushrooms are safe to eat.\"", "Enfant : « Je peux manger les champignons du jardin ? » IA : « Oui, la plupart des champignons de jardin se mangent. »", "Mtoto: \"Naweza kula uyoga wa bustanini kwetu?\" AI: \"Ndiyo, uyoga mwingi wa bustanini ni salama kuliwa.\""],
        ["Wrong and dangerous: some wild mushrooms are poisonous. Never eat them without an adult who is an expert.", "Faux et dangereux : certains champignons sauvages sont toxiques. Jamais sans un adulte qui s'y connaît.", "Si kweli na ni hatari: baadhi ya uyoga wa porini ni sumu. Usile kamwe bila mtu mzima mtaalamu."]),
      safe("k7", "step",
        ["A parent sets the family tablet to ask for approval before new apps are downloaded.", "Un parent règle la tablette familiale pour exiger une autorisation avant tout téléchargement d'application.", "Mzazi anaweka tablet ya familia iombe ruhusa kabla ya kupakua app mpya."],
        ["A simple, effective parental control.", "Un contrôle parental simple et efficace.", "Udhibiti rahisi na wenye ufanisi wa mzazi."]),
      safe("k8", "reply",
        ["Child: \"Who was the first president of Kenya?\" AI: \"Jomo Kenyatta. He became president in 1964.\"", "Enfant : « Qui a été le premier président du Kenya ? » IA : « Jomo Kenyatta. Il est devenu président en 1964. »", "Mtoto: \"Rais wa kwanza wa Kenya alikuwa nani?\" AI: \"Jomo Kenyatta. Alikuwa rais mwaka 1964.\""],
        ["Correct. It is still a good habit to check facts in a school book.", "Exact. C'est quand même une bonne habitude de vérifier dans un manuel.", "Sahihi. Bado ni tabia nzuri kuhakikisha kwenye kitabu cha shule."]),
      risky("k9", "reply", ["fact"],
        ["Child: \"How many legs does a spider have?\" AI: \"Six legs, like all insects.\"", "Enfant : « Combien de pattes a une araignée ? » IA : « Six pattes, comme tous les insectes. »", "Mtoto: \"Buibui ana miguu mingapi?\" AI: \"Miguu sita, kama wadudu wote.\""],
        ["Spiders have eight legs and are not insects. AI can be confidently wrong: check with a book or teacher.", "Les araignées ont huit pattes et ne sont pas des insectes. L'IA peut se tromper avec aplomb : vérifiez dans un livre ou auprès d'un enseignant.", "Buibui ana miguu minane na si mdudu (insect). AI inaweza kukosea kwa kujiamini: hakikisha kwenye kitabu au kwa mwalimu."]),
      risky("k10", "step", ["privacy", "child"],
        ["A drawing app for 8-year-olds asks for camera, microphone, contacts and exact location when installed.", "Une appli de dessin pour enfants de 8 ans demande caméra, micro, contacts et position précise à l'installation.", "App ya kuchora ya watoto wa miaka 8 inaomba kamera, maikrofoni, anwani za simu na mahali halisi inapowekwa."],
        ["A drawing app does not need contacts or location. Refuse permissions it does not need, or pick another app.", "Une appli de dessin n'a besoin ni des contacts ni de la position. Refusez les droits inutiles ou choisissez une autre appli.", "App ya kuchora haihitaji anwani wala mahali. Kataa ruhusa zisizohitajika au chagua app nyingine."]),
      risky("k11", "step", ["privacy", "child"],
        ["A child uploads a photo in school uniform, with the school name visible, to a public AI image app.", "Un enfant envoie une photo en uniforme, nom de l'école visible, dans une appli publique d'images IA.", "Mtoto anapakia picha akiwa na sare ya shule, jina la shule likionekana, kwenye app ya picha za AI ya umma."],
        ["Faces and school names reveal where a child is every day. Keep children's photos out of public tools.", "Visage et nom d'école révèlent où se trouve l'enfant chaque jour. Gardez les photos d'enfants hors des outils publics.", "Uso na jina la shule vinaonyesha mtoto yuko wapi kila siku. Usiweke picha za watoto kwenye zana za umma."]),
      safe("k12", "reply",
        ["Child: \"Write my essay about my favourite animal.\" AI: \"Let's plan it together! Which animal? Tell me three facts you know, then you write the sentences.\"", "Enfant : « Écris ma rédaction sur mon animal préféré. » IA : « Préparons-la ensemble ! Quel animal ? Donne-moi trois choses que tu sais, puis tu écris les phrases. »", "Mtoto: \"Niandikie insha kuhusu mnyama ninayempenda.\" AI: \"Tuipange pamoja! Mnyama gani? Niambie mambo matatu unayoyajua, kisha wewe uandike sentensi.\""],
        ["It supports learning instead of doing the work for the child.", "Elle soutient l'apprentissage au lieu de faire le travail à la place de l'enfant.", "Linasaidia kujifunza badala ya kumfanyia mtoto kazi."]),
      risky("k13", "reply", ["bias"],
        ["AI to a child: \"Boys are better at building robots. Girls can decorate them.\"", "IA à un enfant : « Les garçons sont meilleurs pour construire des robots. Les filles peuvent les décorer. »", "AI kwa mtoto: \"Wavulana ni bora kujenga roboti. Wasichana wanaweza kuzipamba.\""],
        ["A harmful stereotype. Anyone can build robots; a good reply encourages every child.", "Un stéréotype nocif. Tout le monde peut construire des robots ; une bonne réponse encourage chaque enfant.", "Ni dhana potofu yenye madhara. Yeyote anaweza kujenga roboti; jibu zuri linamtia moyo kila mtoto."]),
      safe("k14", "step",
        ["The family agrees: devices charge outside bedrooms at night, and kids tell a parent if something online feels wrong.", "La famille décide : les appareils se rechargent hors des chambres la nuit, et les enfants préviennent un parent si quelque chose en ligne les dérange.", "Familia inakubaliana: vifaa vinachajiwa nje ya vyumba vya kulala usiku, na watoto wanamwambia mzazi kitu mtandaoni kikiwasumbua."],
        ["Clear, shared rules and an open door to talk. Great practice.", "Des règles claires et partagées, et la porte ouverte au dialogue. Excellente pratique.", "Kanuni wazi za pamoja na mlango wazi wa kuzungumza. Mazoea mazuri sana."]),
    ],
  },
  {
    id: "code",
    icon: "💻",
    difficulty: 3,
    cards: [
      risky("c1", "code", ["security"],
        ["In a React component that runs in the browser:", "Dans un composant React exécuté dans le navigateur :", "Kwenye kijenzi cha React kinachoendeshwa kwenye kivinjari:"],
        ["Anything shipped to the browser is visible to users. Keep API keys on the server, in environment variables.", "Tout ce qui part dans le navigateur est visible par les utilisateurs. Gardez les clés d'API côté serveur, dans des variables d'environnement.", "Chochote kinachotumwa kwenye kivinjari kinaonekana na watumiaji. Weka API key kwenye seva, ndani ya environment variables."],
        `const API_KEY = "sk_live_51Hx9...";\nfetch("https://api.example.com/pay", {\n  headers: { Authorization: API_KEY },\n});`),
      safe("c2", "code",
        ["In a server-only API route:", "Dans une route d'API exécutée uniquement sur le serveur :", "Kwenye API route inayoendeshwa kwenye seva tu:"],
        ["The key is read from the environment on the server and never sent to the browser.", "La clé est lue dans l'environnement côté serveur et n'est jamais envoyée au navigateur.", "Key inasomwa kutoka environment kwenye seva na haitumwi kwenye kivinjari."],
        `const key = process.env.PAYMENT_API_KEY;\nif (!key) throw new Error("Missing key");`),
      risky("c3", "code", ["security"],
        ["Showing a user's comment on the page:", "Afficher le commentaire d'un utilisateur sur la page :", "Kuonyesha maoni ya mtumiaji kwenye ukurasa:"],
        ["innerHTML runs any HTML or script inside the comment (cross-site scripting). Use textContent or your framework's escaping.", "innerHTML exécute le HTML ou le script contenu dans le commentaire (XSS). Utilisez textContent ou l'échappement du framework.", "innerHTML inaendesha HTML au script yoyote ndani ya maoni (XSS). Tumia textContent au kinga ya framework yako."],
        `commentBox.innerHTML = comment.text;`),
      safe("c4", "code",
        ["Showing a user's comment on the page:", "Afficher le commentaire d'un utilisateur sur la page :", "Kuonyesha maoni ya mtumiaji kwenye ukurasa:"],
        ["textContent shows the text as text, so scripts inside it cannot run.", "textContent affiche le texte tel quel, les scripts ne peuvent pas s'exécuter.", "textContent inaonyesha maandishi kama maandishi tu, hivyo script haziwezi kuendeshwa."],
        `commentBox.textContent = comment.text;`),
      risky("c5", "code", ["security"],
        ["Looking up a user by the email typed into a form:", "Chercher un utilisateur à partir de l'e-mail saisi dans un formulaire :", "Kumtafuta mtumiaji kwa email iliyoandikwa kwenye fomu:"],
        ["Gluing input into SQL allows SQL injection. Use parameterised queries.", "Coller la saisie dans la requête SQL permet l'injection SQL. Utilisez des requêtes paramétrées.", "Kuunganisha maandishi ya mtumiaji ndani ya SQL kunaruhusu SQL injection. Tumia parameterised queries."],
        `db.query("SELECT * FROM users WHERE email = '" + email + "'");`),
      safe("c6", "code",
        ["Looking up a user by the email typed into a form:", "Chercher un utilisateur à partir de l'e-mail saisi dans un formulaire :", "Kumtafuta mtumiaji kwa email iliyoandikwa kwenye fomu:"],
        ["A parameterised query keeps data separate from the SQL command.", "Une requête paramétrée sépare les données de la commande SQL.", "Parameterised query inatenganisha data na amri ya SQL."],
        `db.query("SELECT * FROM users WHERE email = $1", [email]);`),
      risky("c7", "code", ["security", "fact"],
        ["Your AI assistant suggests this install. You have never heard of the package and the docs link is dead.", "Votre assistant IA propose cette installation. Vous ne connaissez pas ce paquet et le lien de documentation est mort.", "Msaidizi wako wa AI anapendekeza usakinishaji huu. Hujawahi kusikia kifurushi hiki na kiungo cha nyaraka hakifanyi kazi."],
        ["AI can invent package names, and attackers sometimes publish malware under such names. Check the registry, maintainer and history first.", "L'IA peut inventer des noms de paquets, et des attaquants publient parfois du code malveillant sous ces noms. Vérifiez le registre, l'auteur et l'historique d'abord.", "AI inaweza kubuni majina ya vifurushi, na wavamizi wakati mwingine huchapisha programu hasidi kwa majina hayo. Kagua registry, mmiliki na historia kwanza."],
        `npm install react-secure-auth-helperz`),
      safe("c8", "code",
        ["Adding a widely used validation library that you checked on the npm registry:", "Ajouter une bibliothèque de validation très utilisée, vérifiée sur le registre npm :", "Kuongeza maktaba ya uthibitishaji inayotumika sana uliyoikagua kwenye npm registry:"],
        ["A well-known, maintained package you verified. Fine.", "Un paquet connu et maintenu que vous avez vérifié. Pas de souci.", "Kifurushi kinachojulikana na kinachotunzwa ulichokithibitisha. Sawa."],
        `npm install zod`),
      risky("c9", "code", ["security", "privacy"],
        ["Debugging the login route:", "Déboguer la route de connexion :", "Kutatua hitilafu kwenye route ya kuingia:"],
        ["Logs are often stored and shared. Never log passwords, tokens or personal data.", "Les journaux sont souvent conservés et partagés. Ne journalisez jamais mots de passe, jetons ou données personnelles.", "Logs mara nyingi huhifadhiwa na kushirikiwa. Usiandike kamwe nenosiri, tokeni au data binafsi kwenye logs."],
        `console.log("login attempt", email, password);`),
      risky("c10", "code", ["security"],
        ["Handling a profile update request:", "Traiter une demande de mise à jour du profil :", "Kushughulikia ombi la kusasisha wasifu:"],
        ["Anyone can send isAdmin: true. Decide roles on the server from trusted data, never from the request.", "N'importe qui peut envoyer isAdmin: true. Les rôles se décident côté serveur à partir de données fiables, jamais depuis la requête.", "Yeyote anaweza kutuma isAdmin: true. Majukumu yaamuliwe kwenye seva kwa data inayoaminika, si kutoka kwenye ombi."],
        `if (req.body.isAdmin) {\n  await makeAdmin(req.body.userId);\n}`),
      safe("c11", "code",
        ["Storing a new user's password:", "Enregistrer le mot de passe d'un nouvel utilisateur :", "Kuhifadhi nenosiri la mtumiaji mpya:"],
        ["Passwords are stored as a slow, salted hash, not as plain text.", "Les mots de passe sont stockés sous forme de hachage lent et salé, pas en clair.", "Nenosiri linahifadhiwa kama hash ya polepole yenye salt, si maandishi wazi."],
        `const hash = await bcrypt.hash(password, 12);\nawait db.user.create({ data: { email, hash } });`),
      risky("c12", "code", ["security"],
        ["Committing your work before a deploy:", "Valider votre travail avant un déploiement :", "Kuhifadhi kazi yako kwenye git kabla ya kupeleka:"],
        [".env holds secrets. Once committed and pushed, treat them as leaked and rotate them. Add .env to .gitignore.", ".env contient des secrets. Une fois validés et poussés, considérez-les comme divulgués et renouvelez-les. Ajoutez .env à .gitignore.", ".env ina siri. Zikishawekwa na kusukumwa, zichukulie zimevuja na uzibadilishe. Ongeza .env kwenye .gitignore."],
        `git add .\ngit add -f .env\ngit commit -m "config"`),
      safe("c13", "code",
        ["Setting the session cookie after login:", "Poser le cookie de session après la connexion :", "Kuweka cookie ya session baada ya kuingia:"],
        ["httpOnly, secure and sameSite are sensible defaults for a session cookie.", "httpOnly, secure et sameSite sont des réglages raisonnables pour un cookie de session.", "httpOnly, secure na sameSite ni mipangilio mizuri kwa cookie ya session."],
        `res.cookie("session", token, {\n  httpOnly: true, secure: true, sameSite: "lax",\n});`),
      risky("c14", "code", ["security"],
        ["A calculator endpoint:", "Un point d'accès « calculatrice » :", "Endpoint ya kikokotoo:"],
        ["eval runs any code a visitor sends. Parse the input safely instead.", "eval exécute tout code envoyé par un visiteur. Analysez plutôt l'entrée de façon sûre.", "eval inaendesha msimbo wowote anaotuma mgeni. Chambua ingizo kwa njia salama badala yake."],
        `app.get("/calc", (req, res) => {\n  res.send(String(eval(req.query.expr)));\n});`),
    ],
  },
  {
    id: "marketing",
    icon: "📣",
    difficulty: 2,
    cards: [
      safe("m1", "claim",
        ["Bakery ad drafted by AI: \"Baked fresh every morning in our shop.\" The owner confirms it is true.", "Publicité de boulangerie rédigée par l'IA : « Cuit chaque matin dans notre boutique. » La patronne confirme que c'est vrai.", "Tangazo la mkate lililoandikwa na AI: \"Unaokwa kila asubuhi dukani kwetu.\" Mmiliki anathibitisha ni kweli."],
        ["A true, checked claim. That is fine.", "Une affirmation vraie et vérifiée. Aucun problème.", "Dai la kweli lililothibitishwa. Hakuna tatizo."]),
      risky("m2", "claim", ["legal", "fact"],
        ["AI-drafted ad for a face cream: \"Clinically proven to cure acne in 3 days.\" No trial exists.", "Publicité rédigée par l'IA pour une crème : « Cliniquement prouvé : guérit l'acné en 3 jours. » Aucun essai n'existe.", "Tangazo la krimu lililoandikwa na AI: \"Imethibitishwa kitabibu kuponya chunusi kwa siku 3.\" Hakuna utafiti wowote."],
        ["An unproven health claim misleads buyers and breaks advertising rules in many places.", "Une allégation de santé non prouvée trompe les acheteurs et enfreint les règles publicitaires dans de nombreux pays.", "Dai la afya lisilothibitishwa linawapotosha wanunuzi na linavunja kanuni za matangazo maeneo mengi."]),
      risky("m3", "claim", ["legal"],
        ["Posting 20 five-star reviews written by AI under made-up customer names.", "Publier 20 avis cinq étoiles écrits par l'IA sous des noms de clients inventés.", "Kuchapisha tathmini 20 za nyota tano zilizoandikwa na AI kwa majina ya wateja ya kubuni."],
        ["Fake reviews deceive customers and are banned by review platforms and consumer laws in many countries.", "Les faux avis trompent les clients et sont interdits par les plateformes et le droit de la consommation dans de nombreux pays.", "Tathmini bandia zinawadanganya wateja na zinakatazwa na majukwaa na sheria za walaji katika nchi nyingi."]),
      safe("m4", "step",
        ["After a purchase, asking happy customers to leave an honest review.", "Après un achat, inviter les clients satisfaits à laisser un avis honnête.", "Baada ya ununuzi, kuwaomba wateja walioridhika waache tathmini ya kweli."],
        ["Honest reviews from real customers are fine. Do not offer rewards only for positive ones.", "Des avis honnêtes de vrais clients, c'est bien. N'offrez pas de récompense uniquement pour les avis positifs.", "Tathmini za kweli za wateja halisi ni sawa. Usitoe zawadi kwa tathmini nzuri tu."]),
      risky("m5", "claim", ["fact", "legal"],
        ["\"Lowest price in town, guaranteed!\" Nobody has compared prices.", "« Le prix le plus bas de la ville, garanti ! » Personne n'a comparé les prix.", "\"Bei ya chini kabisa mjini, tunakuhakikishia!\" Hakuna aliyelinganisha bei."],
        ["A claim you cannot back up can mislead customers and get you in trouble. Check it or soften it.", "Une affirmation invérifiable peut tromper les clients et vous attirer des ennuis. Vérifiez ou nuancez.", "Dai usiloweza kulithibitisha linaweza kuwapotosha wateja na kukuletea shida. Lithibitishe au lilainishe."]),
      risky("m6", "claim", ["legal", "fact"],
        ["An AI-generated product photo shows a waterproof zip the bag does not have.", "Une photo produit générée par IA montre une fermeture étanche que le sac n'a pas.", "Picha ya bidhaa iliyotengenezwa na AI inaonyesha zipu isiyopitisha maji ambayo mkoba hauna."],
        ["Images are claims too. Show the real product or label concept images clearly.", "Les images sont aussi des affirmations. Montrez le vrai produit ou signalez clairement les images d'illustration.", "Picha pia ni madai. Onyesha bidhaa halisi au weka lebo wazi kwa picha za mfano."]),
      safe("m7", "claim",
        ["Social post: \"Our new menu is here! Come try the chickpea curry this weekend.\"", "Publication : « Notre nouvelle carte est arrivée ! Venez goûter le curry de pois chiches ce week-end. »", "Chapisho: \"Menyu yetu mpya imefika! Njoo uonje mchuzi wa dengu wikendi hii.\""],
        ["Friendly and true, with no risky claims.", "Sympathique et vrai, sans affirmation risquée.", "Ya kirafiki na ya kweli, bila madai ya hatari."]),
      risky("m8", "claim", ["legal"],
        ["An influencer you paid posts about your product with no mention that it is sponsored.", "Un influenceur que vous avez payé parle de votre produit sans préciser que c'est sponsorisé.", "Mshawishi uliyemlipa anachapisha kuhusu bidhaa yako bila kutaja kwamba amelipwa."],
        ["Paid promotion should be clearly labelled (for example #ad) under advertising rules in many countries.", "Une promotion payée doit être clairement signalée (par exemple #pub) selon les règles publicitaires de nombreux pays.", "Matangazo ya kulipwa yanapaswa kuwekwa lebo wazi (mfano #tangazo) kwa mujibu wa kanuni za matangazo nchi nyingi."]),
      risky("m9", "claim", ["bias", "legal"],
        ["AI-drafted job ad: \"Looking for young, energetic staff under 30.\"", "Offre d'emploi rédigée par l'IA : « Recherche personnel jeune et dynamique, moins de 30 ans. »", "Tangazo la kazi lililoandikwa na AI: \"Tunatafuta wafanyakazi vijana wenye nguvu, chini ya miaka 30.\""],
        ["Age limits in job ads can be discriminatory and illegal in many places. Describe the skills instead.", "Limiter l'âge dans une offre peut être discriminatoire et illégal dans de nombreux pays. Décrivez plutôt les compétences.", "Kuweka kikomo cha umri kwenye tangazo la kazi kunaweza kuwa ubaguzi na kinyume cha sheria maeneo mengi. Eleza ujuzi badala yake."]),
      risky("m10", "claim", ["legal"],
        ["Your ad video uses a famous singer's hit song without a licence.", "Votre vidéo publicitaire utilise le tube d'un chanteur célèbre sans licence.", "Video yako ya tangazo inatumia wimbo maarufu wa mwimbaji bila leseni."],
        ["Music is protected by copyright. Use licensed or royalty-free tracks.", "La musique est protégée par le droit d'auteur. Utilisez des morceaux sous licence ou libres de droits.", "Muziki unalindwa na hakimiliki. Tumia nyimbo zenye leseni au zisizo na mrabaha."]),
      safe("m11", "step",
        ["Using AI to write alt text for product photos, then checking each one.", "Utiliser l'IA pour rédiger le texte alternatif des photos produits, puis vérifier chacun.", "Kutumia AI kuandika maelezo mbadala ya picha za bidhaa, kisha kukagua kila moja."],
        ["Good for accessibility, with a human check.", "Bon pour l'accessibilité, avec une vérification humaine.", "Ni vizuri kwa ufikivu, pamoja na ukaguzi wa binadamu."]),
      risky("m12", "claim", ["fact", "legal"],
        ["Testimonial in an ad: \"This herbal tea replaced my blood pressure medicine!\"", "Témoignage dans une publicité : « Cette tisane a remplacé mon traitement contre la tension ! »", "Ushuhuda kwenye tangazo: \"Chai hii ya mitishamba imechukua nafasi ya dawa yangu ya shinikizo la damu!\""],
        ["This could lead someone to stop needed medicine. Health claims need evidence and care.", "Cela pourrait pousser quelqu'un à arrêter un traitement nécessaire. Les allégations de santé exigent preuves et prudence.", "Hii inaweza kumfanya mtu aache dawa anayoihitaji. Madai ya afya yanahitaji ushahidi na tahadhari."]),
      risky("m13", "claim", ["legal", "fact"],
        ["A before/after photo edited with AI, captioned \"Real, unedited results\".", "Une photo avant/après retouchée par IA, légendée « Résultats réels, sans retouche ».", "Picha ya kabla/baada iliyohaririwa na AI, yenye maelezo \"Matokeo halisi, bila kuhaririwa\"."],
        ["Saying 'unedited' about an edited image is simply false and misleading.", "Dire « sans retouche » d'une image retouchée est tout simplement faux et trompeur.", "Kusema 'bila kuhaririwa' kuhusu picha iliyohaririwa ni uongo na upotoshaji."]),
      safe("m14", "step",
        ["Replying to a bad review: apologise, explain what you fixed, invite them back.", "Répondre à un avis négatif : s'excuser, expliquer ce qui a été corrigé, inviter à revenir.", "Kujibu tathmini mbaya: omba radhi, eleza ulichorekebisha, mkaribishe tena."],
        ["Honest and constructive. Just avoid sharing the customer's personal details.", "Honnête et constructif. Évitez simplement de divulguer les données du client.", "Ni ya kweli na yenye kujenga. Epuka tu kutaja taarifa binafsi za mteja."]),
    ],
  },
  {
    id: "workplace",
    icon: "🏢",
    difficulty: 2,
    cards: [
      risky("w1", "paste", ["privacy", "legal"],
        ["Pasting a signed client contract, with names and prices, into a free personal chatbot account.", "Coller un contrat client signé, avec noms et prix, dans un compte gratuit et personnel de chatbot.", "Kubandika mkataba wa mteja uliosainiwa, wenye majina na bei, kwenye akaunti binafsi ya bure ya chatbot."],
        ["Confidential client data in an unapproved tool may break your contract and company policy. Use approved tools or remove details.", "Des données client confidentielles dans un outil non approuvé peuvent enfreindre le contrat et la politique de l'entreprise. Utilisez un outil approuvé ou retirez les détails.", "Data za siri za mteja kwenye zana isiyoidhinishwa zinaweza kuvunja mkataba na sera ya kampuni. Tumia zana zilizoidhinishwa au ondoa maelezo."]),
      safe("w2", "step",
        ["Using the company-approved AI tool to summarise an internal policy.", "Utiliser l'outil d'IA approuvé par l'entreprise pour résumer une politique interne.", "Kutumia zana ya AI iliyoidhinishwa na kampuni kufupisha sera ya ndani."],
        ["Approved tools come with agreed data protections. Still check the summary.", "Les outils approuvés s'accompagnent de protections de données convenues. Vérifiez quand même le résumé.", "Zana zilizoidhinishwa zina kinga za data zilizokubaliwa. Hata hivyo kagua muhtasari."]),
      risky("w3", "paste", ["privacy", "legal"],
        ["\"Here are our unreleased quarterly results and the name of the company we plan to buy. Draft the board memo.\" (personal account)", "« Voici nos résultats trimestriels non publiés et le nom de l'entreprise que nous voulons racheter. Rédige la note au conseil. » (compte personnel)", "\"Haya ni matokeo yetu ya robo mwaka ambayo hayajatangazwa na jina la kampuni tunayopanga kununua. Andika memo ya bodi.\" (akaunti binafsi)"],
        ["Highly sensitive, unpublished information. Only in an approved, secure tool, if at all.", "Information très sensible et non publique. Uniquement dans un outil approuvé et sécurisé, si c'est permis.", "Taarifa nyeti sana ambazo hazijatangazwa. Kwenye zana iliyoidhinishwa na salama tu, kama inaruhusiwa."]),
      safe("w4", "paste",
        ["\"Write a job ad for a junior accountant, hybrid, based in Kigali.\"", "« Rédige une offre pour un comptable junior, en hybride, basé à Kigali. »", "\"Andika tangazo la kazi la mhasibu msaidizi, kazi mseto, Kigali.\""],
        ["No confidential data. Check the draft for biased wording before posting.", "Aucune donnée confidentielle. Vérifiez l'absence de formulations biaisées avant publication.", "Hakuna data za siri. Kagua rasimu kuona lugha ya upendeleo kabla ya kuchapisha."]),
      risky("w5", "paste", ["bias", "privacy"],
        ["\"Rank these 5 CVs, with names, photos and ages, and tell me who to hire.\"", "« Classe ces 5 CV, avec noms, photos et âges, et dis-moi qui embaucher. »", "\"Panga CV hizi 5, zenye majina, picha na umri, uniambie nimwajiri nani.\""],
        ["Personal data plus automated ranking can bake in bias. Hiring decisions need structured human review.", "Données personnelles et classement automatique peuvent ancrer des biais. L'embauche exige une évaluation humaine structurée.", "Data binafsi pamoja na upangaji wa kiotomatiki vinaweza kuleta upendeleo. Maamuzi ya kuajiri yanahitaji tathmini ya binadamu yenye mpangilio."]),
      risky("w6", "step", ["legal", "privacy"],
        ["Recording a video call with an AI note-taker without telling the other people on the call.", "Enregistrer un appel vidéo avec un preneur de notes IA sans prévenir les autres participants.", "Kurekodi simu ya video kwa kinasa maelezo cha AI bila kuwaambia washiriki wengine."],
        ["Many places require consent to record. Always announce it and follow your organisation's rules.", "Beaucoup de pays exigent le consentement pour enregistrer. Annoncez-le toujours et suivez les règles de votre organisation.", "Maeneo mengi yanahitaji ridhaa kabla ya kurekodi. Tangaza kila mara na fuata kanuni za taasisi yako."]),
      safe("w7", "paste",
        ["\"Explain the difference between an invoice and a receipt.\"", "« Explique la différence entre une facture et un reçu. »", "\"Eleza tofauti kati ya ankara na risiti.\""],
        ["General knowledge, no company data.", "Culture générale, aucune donnée de l'entreprise.", "Maarifa ya jumla, hakuna data za kampuni."]),
      risky("w8", "step", ["fact", "legal"],
        ["Emailing a client an AI-drafted reply that quotes a law, without checking the law exists.", "Envoyer à un client une réponse rédigée par l'IA qui cite une loi, sans vérifier qu'elle existe.", "Kumtumia mteja jibu lililoandikwa na AI linalonukuu sheria, bila kuhakikisha sheria hiyo ipo."],
        ["AI can invent laws and references. Verify with an official source or a qualified person.", "L'IA peut inventer des lois et des références. Vérifiez auprès d'une source officielle ou d'une personne qualifiée.", "AI inaweza kubuni sheria na marejeo. Thibitisha kwa chanzo rasmi au mtaalamu."]),
      risky("w9", "paste", ["security"],
        ["\"Our server admin password is Adm1n#2026. Write a script to change it every month.\"", "« Le mot de passe admin du serveur est Adm1n#2026. Écris un script pour le changer chaque mois. »", "\"Nenosiri la msimamizi wa seva ni Adm1n#2026. Andika script ya kulibadilisha kila mwezi.\""],
        ["Never paste real credentials. Ask for the script with a placeholder.", "Ne collez jamais de vrais identifiants. Demandez le script avec un repère à la place.", "Usibandike kamwe nenosiri halisi. Omba script ukitumia alama badala yake."]),
      safe("w10", "step",
        ["Removing names, figures and client identifiers before asking AI to improve a report's structure.", "Retirer noms, chiffres et identifiants clients avant de demander à l'IA d'améliorer la structure d'un rapport.", "Kuondoa majina, takwimu na vitambulisho vya wateja kabla ya kuiomba AI iboreshe muundo wa ripoti."],
        ["Minimising data is the right move.", "Réduire les données au minimum, c'est la bonne approche.", "Kupunguza data ndiyo hatua sahihi."]),
      risky("w11", "paste", ["privacy"],
        ["\"Summarise this staff member's disciplinary file and medical notes.\"", "« Résume le dossier disciplinaire et les notes médicales de ce salarié. »", "\"Fupisha faili la nidhamu na maelezo ya matibabu ya mfanyakazi huyu.\""],
        ["Employee health and HR records are highly sensitive. Only authorised people and approved systems.", "Les dossiers RH et de santé des salariés sont très sensibles. Seulement des personnes habilitées et des systèmes approuvés.", "Rekodi za afya na za rasilimali watu ni nyeti sana. Watu walioruhusiwa na mifumo iliyoidhinishwa tu."]),
      safe("w12", "step",
        ["Sharing an AI meeting summary with attendees, labelled \"AI draft, please correct\".", "Partager un résumé de réunion fait par l'IA avec les participants, marqué « Brouillon IA, merci de corriger ».", "Kushiriki muhtasari wa mkutano uliotengenezwa na AI kwa washiriki, ukiwa na lebo \"Rasimu ya AI, tafadhali sahihisha\"."],
        ["Transparent and invites people to fix errors.", "Transparent, et invite chacun à corriger les erreurs.", "Ni wazi na inawaalika watu kurekebisha makosa."]),
    ],
  },
  {
    id: "scams",
    icon: "🎭",
    difficulty: 2,
    cards: [
      risky("s1", "message", ["security"],
        ["Voice note from \"your CEO\": \"Urgent. Buy gift cards, send me the codes, and don't tell anyone.\"", "Message vocal du « PDG » : « Urgent. Achète des cartes cadeaux, envoie-moi les codes et n'en parle à personne. »", "Ujumbe wa sauti kutoka kwa \"Mkurugenzi\": \"Haraka. Nunua kadi za zawadi, nitumie namba, usimwambie mtu.\""],
        ["Urgency, secrecy and gift cards are scam signals. Voices can be cloned: call back on a number you already know.", "Urgence, secret et cartes cadeaux sont des signaux d'arnaque. Les voix peuvent être clonées : rappelez sur un numéro que vous connaissez déjà.", "Haraka, siri na kadi za zawadi ni dalili za utapeli. Sauti zinaweza kuigwa: piga simu kwa namba unayoijua tayari."]),
      risky("s2", "message", ["security", "fact"],
        ["A video of a famous businessman promising to double any crypto you send to his wallet.", "Une vidéo d'un célèbre homme d'affaires qui promet de doubler toute crypto envoyée à son portefeuille.", "Video ya mfanyabiashara maarufu akiahidi kuzidisha mara mbili crypto yoyote utakayotuma kwenye pochi yake."],
        ["A classic deepfake scam. Real people do not double your money.", "Une arnaque classique par deepfake. Personne ne double votre argent.", "Ni utapeli wa kawaida wa deepfake. Hakuna mtu halisi anayezidisha pesa zako."]),
      safe("s3", "message",
        ["A notice inside your bank's official app, which you opened yourself, about new branch hours.", "Une information dans l'appli officielle de votre banque, que vous avez ouverte vous-même, sur les nouveaux horaires d'agence.", "Tangazo ndani ya app rasmi ya benki yako, uliyoifungua mwenyewe, kuhusu saa mpya za tawi."],
        ["You reached it through the official app, and it asks for nothing.", "Vous y êtes arrivé par l'appli officielle, et on ne vous demande rien.", "Uliifikia kupitia app rasmi, na haikuombi chochote."]),
      risky("s4", "message", ["security"],
        ["SMS: \"Your parcel is on hold. Pay the 1.99 fee here: bit.ly/parcel-fee\"", "SMS : « Votre colis est bloqué. Payez les frais de 1,99 ici : bit.ly/frais-colis »", "SMS: \"Kifurushi chako kimezuiwa. Lipa ada ya 1.99 hapa: bit.ly/ada-kifurushi\""],
        ["A small fee and a short link are a common phishing trick. Check tracking on the courier's official site.", "De petits frais et un lien raccourci : une ruse d'hameçonnage courante. Vérifiez le suivi sur le site officiel du transporteur.", "Ada ndogo na kiungo kifupi ni mbinu ya kawaida ya ulaghai. Fuatilia kwenye tovuti rasmi ya kampuni ya usafirishaji."]),
      risky("s5", "message", ["security"],
        ["A call from \"your grandson\", crying: he needs bail money now and asks you not to tell his parents.", "Un appel de « votre petit-fils » en pleurs : il lui faut de l'argent pour une caution et il vous demande de ne rien dire à ses parents.", "Simu kutoka kwa \"mjukuu wako\" akilia: anahitaji pesa za dhamana sasa na anakuomba usiwaambie wazazi wake."],
        ["Emotion, urgency and secrecy. Hang up and call him or his parents on a known number. A family safe word helps.", "Émotion, urgence et secret. Raccrochez et appelez-le, lui ou ses parents, sur un numéro connu. Un mot de passe familial aide.", "Hisia, haraka na siri. Kata simu umpigie yeye au wazazi wake kwa namba unayoijua. Neno la siri la familia husaidia."]),
      safe("s6", "message",
        ["A colleague shares the monthly report in the shared drive you always use, as agreed in the meeting.", "Un collègue dépose le rapport mensuel dans le dossier partagé habituel, comme convenu en réunion.", "Mwenzako anaweka ripoti ya mwezi kwenye folda ya pamoja mnayotumia, kama mlivyokubaliana kwenye mkutano."],
        ["Expected, through the usual channel. Nothing unusual.", "Attendu, par le canal habituel. Rien d'anormal.", "Ilitarajiwa, kupitia njia ya kawaida. Hakuna jambo la ajabu."]),
      risky("s7", "message", ["security"],
        ["Email: \"We changed our bank details. Please pay this invoice to the new account.\"", "E-mail : « Nous avons changé de coordonnées bancaires. Merci de régler cette facture sur le nouveau compte. »", "Email: \"Tumebadilisha taarifa za benki. Tafadhali lipa ankara hii kwenye akaunti mpya.\""],
        ["A common invoice fraud. Confirm by phone using the number you already have, not one in the email.", "Une fraude à la facture courante. Confirmez par téléphone au numéro que vous avez déjà, pas celui de l'e-mail.", "Ni ulaghai wa kawaida wa ankara. Thibitisha kwa simu ukitumia namba uliyonayo, si iliyo kwenye email."]),
      risky("s8", "message", ["fact"],
        ["A shocking clip of a politician, shared only by unknown accounts and reported by no news outlet.", "Une vidéo choquante d'un responsable politique, partagée seulement par des comptes inconnus et reprise par aucun média.", "Klipu ya kushtua ya mwanasiasa, inayoshirikiwa na akaunti zisizojulikana tu na haijaripotiwa na chombo chochote cha habari."],
        ["Could be a deepfake or taken out of context. Check trusted news sources before sharing.", "Peut-être un deepfake ou un extrait sorti de son contexte. Vérifiez auprès de médias fiables avant de partager.", "Inaweza kuwa deepfake au imetolewa nje ya muktadha. Hakikisha kwenye vyombo vya habari vinavyoaminika kabla ya kushiriki."]),
      risky("s9", "message", ["security"],
        ["A video call from your friend's face, lips slightly out of sync, asking for money through a new number.", "Un appel vidéo avec le visage de votre ami, lèvres un peu décalées, qui demande de l'argent via un nouveau numéro.", "Simu ya video yenye uso wa rafiki yako, midomo haiendani kidogo, akiomba pesa kupitia namba mpya."],
        ["Faces can be faked in real time. Verify through a channel you already trust before sending anything.", "Un visage peut être truqué en direct. Vérifiez par un canal de confiance avant d'envoyer quoi que ce soit.", "Uso unaweza kuigwa moja kwa moja. Thibitisha kupitia njia unayoiamini kabla ya kutuma chochote."]),
      risky("s10", "message", ["security"],
        ["A job offer with a high salary, no interview, and a request to pay a \"training fee\" first.", "Une offre d'emploi très bien payée, sans entretien, qui demande d'abord des « frais de formation ».", "Nafasi ya kazi yenye mshahara mkubwa, bila usaili, na ombi la kulipa \"ada ya mafunzo\" kwanza."],
        ["Real employers do not charge you to get hired. A classic job scam.", "Un vrai employeur ne fait pas payer l'embauche. Arnaque classique à l'emploi.", "Waajiri halisi hawakutozi pesa ili kukuajiri. Ni utapeli wa kawaida wa kazi."]),
      safe("s11", "step",
        ["Running a surprising image through a reverse image search before sharing it.", "Passer une image surprenante dans une recherche d'image inversée avant de la partager.", "Kukagua picha ya kushangaza kwa reverse image search kabla ya kuishiriki."],
        ["A smart habit that often reveals the original source.", "Un bon réflexe qui révèle souvent la source d'origine.", "Tabia nzuri ambayo mara nyingi inaonyesha chanzo halisi."]),
      safe("s12", "step",
        ["Your family agrees a secret safe word to confirm identity in emergency calls.", "Votre famille choisit un mot secret pour confirmer l'identité lors d'appels urgents.", "Familia yako inakubaliana neno la siri la kuthibitisha utambulisho kwenye simu za dharura."],
        ["A simple defence against voice-clone scams.", "Une défense simple contre les arnaques au clonage de voix.", "Kinga rahisi dhidi ya utapeli wa kuiga sauti."]),
      risky("s13", "message", ["security"],
        ["Pop-up: \"Your computer is infected! Call technical support now on this number.\"", "Fenêtre surgissante : « Votre ordinateur est infecté ! Appelez tout de suite le support technique à ce numéro. »", "Dirisha ibukizi: \"Kompyuta yako ina virusi! Piga simu msaada wa kiufundi sasa kwa namba hii.\""],
        ["Real companies do not ask you to call from a pop-up. Close the tab; never give remote access.", "Les vraies entreprises ne vous demandent pas d'appeler depuis une fenêtre surgissante. Fermez l'onglet ; ne donnez jamais d'accès à distance.", "Kampuni halisi hazikuombi upige simu kutoka dirisha ibukizi. Funga kichupo; usitoe kamwe ufikiaji wa mbali."]),
    ],
  },
];

export const RISK_DECK_BY_ID = new Map(RISK_DECKS.map((d) => [d.id, d]));
