export const metadata = {
  title: "Terms of Service | TIBLOGICS",
  description: "Terms and conditions governing use of TIBLOGICS services.",
};

export default function TermsPage() {
  return (
    <div className="pt-24 pb-20 min-h-screen bg-[#F4F7FB]">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">

        {/* Header */}
        <div className="mb-10">
          <div className="flex items-center gap-2 mb-4">
            <img src="/logo.svg" alt="TIBLOGICS" className="h-8 w-auto" />
            <span className="font-syne text-xl font-extrabold tracking-tight">
              <span className="text-[#1B3A6B]">TIB</span><span className="text-[#F47C20]">LOGICS</span>
            </span>
          </div>
          <span className="section-tag">Legal</span>
          <h1 className="font-syne font-extrabold text-4xl text-[#0D1B2A] mt-3">Terms of Service</h1>
          <p className="font-dm text-[#7A8FA6] text-sm mt-2">
            Effective Date: April 20, 2026 &nbsp;·&nbsp; Last Updated: April 20, 2026
          </p>
        </div>

        <div className="bg-white border border-[#D2DCE8] rounded-2xl p-8 md:p-10 space-y-10 font-dm text-[#3A4A5C] leading-relaxed">

          {/* Intro */}
          <section>
            <p>
              These Terms of Service ("<strong>Terms</strong>") constitute a legally binding agreement
              between you ("<strong>Client</strong>", "<strong>you</strong>", or "<strong>your</strong>")
              and <strong>TIBLOGICS LLC</strong> ("<strong>TIBLOGICS</strong>", "<strong>we</strong>",
              "<strong>us</strong>", or "<strong>our</strong>"), governing your access to and use of the
              TIBLOGICS website at <strong>tiblogics.com</strong> (the "<strong>Site</strong>") and all
              related services, products, tools, consultations, and deliverables (collectively, the
              "<strong>Services</strong>").
            </p>
            <p className="mt-4">
              <strong>By accessing the Site, submitting an inquiry, booking a consultation, making a
              payment, or engaging TIBLOGICS for any service, you acknowledge that you have read,
              understood, and agree to be bound by these Terms.</strong> If you do not agree, do not
              use our Site or Services.
            </p>
            <p className="mt-4">
              These Terms apply to all visitors, prospects, clients, and users of our Site and Services.
              Additional project-specific terms may apply and will be set out in a separate Statement of
              Work (SOW) or Service Agreement executed between the parties.
            </p>
          </section>

          {/* 1 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">1. Services</h2>

            <h3 className="font-semibold text-[#0D1B2A] mb-2">1.1 Scope of Services</h3>
            <p>
              TIBLOGICS provides AI implementation, workflow automation, software development, digital
              strategy, consulting, training, and related technology services. The specific scope,
              timeline, deliverables, and fees for any engagement are defined in a mutually executed
              Statement of Work, proposal, or service agreement ("<strong>SOW</strong>").
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-6 mb-2">1.2 Consultations and Bookings</h3>
            <p>
              Free discovery calls and paid consultations may be booked through our Site. Bookings are
              subject to availability and confirmation by TIBLOGICS. We reserve the right to decline any
              booking at our sole discretion.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-6 mb-2">1.3 Modifications to Services</h3>
            <p>
              TIBLOGICS reserves the right to modify, suspend, or discontinue any feature of the Site or
              Services at any time with or without notice. We will not be liable to you or any third party
              for any such modification, suspension, or discontinuation.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-6 mb-2">1.4 AI-Powered Features</h3>
            <p>
              Our Site includes AI-powered tools and assistants. These features are provided for
              informational and convenience purposes only. Outputs generated by AI are not guaranteed to
              be accurate, complete, or suitable for any particular purpose. You should independently
              verify any AI-generated content before relying on it for business or legal decisions.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">2. Client Responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-2">
              <li>Provide accurate, complete, and timely information necessary for the delivery of Services</li>
              <li>Make timely payments as agreed in the applicable SOW or payment schedule</li>
              <li>Promptly review and provide feedback on deliverables within agreed timeframes</li>
              <li>Ensure you have all necessary rights, licences, and permissions for any materials, data, or content you provide to TIBLOGICS</li>
              <li>Comply with all applicable laws and regulations in connection with your use of the Services</li>
              <li>Not use the Services for any unlawful, fraudulent, harmful, or abusive purpose</li>
              <li>Not attempt to reverse-engineer, copy, or misappropriate any TIBLOGICS proprietary methods, tools, or systems</li>
            </ul>
            <p className="mt-4">
              Failure to meet these responsibilities may result in project delays, additional fees, or
              termination of Services. TIBLOGICS will not be liable for delays or failures caused by your
              failure to fulfil these obligations.
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">3. Fees, Payments, and Refunds</h2>

            <h3 className="font-semibold text-[#0D1B2A] mb-2">3.1 Fees</h3>
            <p>
              Fees for Services are set out in the applicable SOW, proposal, or booking confirmation.
              All fees are stated in US Dollars (USD) unless otherwise specified. TIBLOGICS reserves the
              right to adjust pricing with reasonable notice for new or renewed engagements.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">3.2 Payment Terms</h3>
            <p>
              Unless otherwise agreed in writing, payment terms are as follows:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Consultations and one-time services: payment in full at the time of booking</li>
              <li>Project-based engagements: 50% deposit upon agreement, remainder due upon project completion or as specified in the SOW</li>
              <li>Retainer engagements: payment due on the first of each billing cycle</li>
            </ul>
            <p className="mt-3">
              Invoices not paid within 14 days of the due date are subject to a late fee of 1.5% per
              month (or the maximum permitted by law, whichever is lower) on the outstanding balance.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">3.3 Refund Policy</h3>
            <p>
              <strong>Consultations:</strong> Cancellations made at least 24 hours before a scheduled
              consultation will receive a full refund. Cancellations made with less than 24 hours notice
              are non-refundable. No-shows forfeit the full consultation fee.
            </p>
            <p className="mt-3">
              <strong>Project-based work:</strong> The initial deposit is non-refundable once work has
              commenced. If TIBLOGICS fails to deliver agreed-upon milestones through no fault of the
              client, TIBLOGICS will provide a pro-rated refund for work not completed.
            </p>
            <p className="mt-3">
              <strong>Retainers:</strong> Retainer fees are non-refundable for the current billing period.
              Either party may cancel with 30 days written notice.
            </p>
            <p className="mt-3">
              <strong>Digital products and courses:</strong> All sales of digital products, courses, and
              downloadable materials are final and non-refundable unless the product is materially
              defective or misrepresented.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">3.4 Taxes</h3>
            <p>
              You are responsible for all applicable taxes, duties, and levies arising from your purchase
              of Services, except for taxes on TIBLOGICS's net income. If required by law, TIBLOGICS may
              collect and remit applicable sales tax.
            </p>
          </section>

          {/* 4 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">4. Intellectual Property</h2>

            <h3 className="font-semibold text-[#0D1B2A] mb-2">4.1 TIBLOGICS IP</h3>
            <p>
              All content on this Site — including text, graphics, logos, images, code, tools, blog
              posts, training materials, and the overall design — is the exclusive intellectual property
              of TIBLOGICS LLC or its licensors and is protected by applicable copyright, trademark,
              and trade secret laws. Nothing in these Terms grants you any right to use TIBLOGICS's
              name, logo, trademarks, or proprietary materials without our prior written consent.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">4.2 Deliverables Ownership</h3>
            <p>
              Unless expressly stated otherwise in a written SOW, upon receipt of full payment,
              TIBLOGICS assigns to the Client all rights, title, and interest in the final deliverables
              created specifically for that Client under the engagement.
            </p>
            <p className="mt-3">
              TIBLOGICS retains ownership of: (a) all pre-existing TIBLOGICS tools, frameworks, libraries,
              and methodologies incorporated into deliverables; (b) general-purpose code and components
              not developed specifically for Client; and (c) any deliverables for which full payment has
              not been received. TIBLOGICS is granted a perpetual, non-exclusive licence to use
              deliverables for portfolio, case study, and promotional purposes unless the Client requests
              confidentiality in writing prior to project commencement.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">4.3 Client Content</h3>
            <p>
              You retain ownership of all content, data, and materials you provide to TIBLOGICS. You
              grant TIBLOGICS a limited, non-exclusive licence to use your content solely for the purpose
              of delivering the agreed Services.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">4.4 Feedback</h3>
            <p>
              Any feedback, suggestions, or ideas you provide about our Services may be used by
              TIBLOGICS without restriction or compensation to you.
            </p>
          </section>

          {/* 5 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">5. Confidentiality</h2>
            <p>
              Each party agrees to keep confidential any non-public, proprietary, or sensitive information
              of the other party that is disclosed in connection with the Services
              ("<strong>Confidential Information</strong>") and not to disclose such information to third
              parties without prior written consent, except as required by law.
            </p>
            <p className="mt-4">
              This obligation does not apply to information that: (a) is or becomes publicly available
              through no breach of these Terms; (b) was already known to the receiving party prior to
              disclosure; (c) is independently developed by the receiving party without use of the
              Confidential Information; or (d) is required to be disclosed by law or court order, provided
              reasonable prior notice is given.
            </p>
            <p className="mt-4">
              Confidentiality obligations survive termination of any engagement for a period of three (3)
              years unless a separate Non-Disclosure Agreement provides otherwise.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">6. Disclaimer of Warranties</h2>
            <p className="uppercase text-sm font-semibold text-[#0D1B2A] mb-3">Important — Please Read Carefully</p>
            <p>
              THE SITE AND SERVICES ARE PROVIDED "<strong>AS IS</strong>" AND "<strong>AS AVAILABLE</strong>"
              WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
              WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT,
              OR THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER
              HARMFUL COMPONENTS.
            </p>
            <p className="mt-4">
              TIBLOGICS DOES NOT WARRANT THAT: (A) THE SERVICES WILL MEET YOUR SPECIFIC REQUIREMENTS;
              (B) RESULTS OBTAINED FROM USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE; (C) ANY
              ERRORS OR DEFECTS WILL BE CORRECTED; OR (D) AI-GENERATED CONTENT WILL BE ACCURATE,
              COMPLETE, OR APPROPRIATE FOR YOUR USE.
            </p>
            <p className="mt-4">
              Any advice, recommendations, or information provided through our Services or Site is for
              general informational purposes only and does not constitute legal, financial, medical, or
              other professional advice.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">7. Limitation of Liability</h2>
            <p className="uppercase text-sm font-semibold text-[#0D1B2A] mb-3">Important — Please Read Carefully</p>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL TIBLOGICS LLC, ITS
              OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, AGENTS, AFFILIATES, OR LICENSORS BE LIABLE
              FOR ANY:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1 uppercase text-sm">
              <li>Indirect, incidental, special, consequential, or punitive damages</li>
              <li>Loss of profits, revenue, data, business, or goodwill</li>
              <li>Business interruption or loss of anticipated savings</li>
              <li>Damages arising from unauthorised access to or alteration of your data</li>
              <li>Damages arising from reliance on AI-generated content</li>
            </ul>
            <p className="mt-4">
              WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR
              ANY OTHER LEGAL THEORY, EVEN IF TIBLOGICS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
              DAMAGES.
            </p>
            <p className="mt-4">
              IN ALL CASES, TIBLOGICS'S TOTAL CUMULATIVE LIABILITY TO YOU FOR ANY CLAIMS ARISING OUT OF
              OR RELATED TO THESE TERMS OR THE SERVICES WILL NOT EXCEED THE GREATER OF: (A) THE TOTAL
              AMOUNT YOU PAID TO TIBLOGICS IN THE THREE (3) MONTHS PRECEDING THE CLAIM; OR (B) ONE
              HUNDRED US DOLLARS ($100).
            </p>
            <p className="mt-4 text-sm">
              Some jurisdictions do not allow limitation of liability for certain types of damages.
              In such jurisdictions, our liability will be limited to the maximum extent permitted by law.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">8. Indemnification</h2>
            <p>
              You agree to defend, indemnify, and hold harmless TIBLOGICS LLC and its officers, directors,
              employees, contractors, agents, affiliates, and licensors from and against any claims,
              liabilities, damages, judgments, awards, losses, costs, expenses, and fees (including
              reasonable attorneys' fees) arising out of or relating to:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Your use of the Site or Services in violation of these Terms</li>
              <li>Your violation of any applicable law, regulation, or third-party right</li>
              <li>Any content, data, or materials you provide to TIBLOGICS</li>
              <li>Your fraud, wilful misconduct, or negligence</li>
              <li>Any dispute between you and a third party arising from your use of the Services</li>
            </ul>
          </section>

          {/* 9 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">9. Acceptable Use</h2>
            <p>You agree not to use the Site or Services to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Violate any applicable local, national, or international law or regulation</li>
              <li>Transmit unsolicited communications (spam) or engage in phishing</li>
              <li>Upload or transmit malicious code, viruses, or harmful software</li>
              <li>Attempt to gain unauthorised access to our systems or those of other users</li>
              <li>Scrape, crawl, or extract data from our Site without written permission</li>
              <li>Impersonate TIBLOGICS, our employees, or any other person or entity</li>
              <li>Engage in any activity that disrupts, degrades, or interferes with the Site</li>
              <li>Use our AI tools to generate harmful, illegal, or misleading content</li>
              <li>Circumvent or attempt to circumvent any security measures on the Site</li>
            </ul>
            <p className="mt-4">
              Violation of this section may result in immediate suspension or termination of access to
              the Site and Services, and may be referred to appropriate law enforcement authorities.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">10. Termination</h2>
            <p>
              Either party may terminate a service engagement upon written notice as specified in the
              applicable SOW. TIBLOGICS may terminate or suspend your access to the Site or Services
              immediately and without notice if you violate these Terms, fail to make required payments,
              or engage in conduct that TIBLOGICS reasonably determines is harmful to TIBLOGICS, other
              clients, or third parties.
            </p>
            <p className="mt-4">
              Upon termination: (a) all licences granted to you under these Terms cease immediately;
              (b) you remain obligated to pay all fees owed for Services rendered prior to termination;
              (c) TIBLOGICS will retain your data as required by law and our Privacy Policy, then
              securely delete it; and (d) provisions of these Terms that by their nature should survive
              will survive, including Sections 4, 5, 6, 7, 8, 12, and 13.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">11. Third-Party Services</h2>
            <p>
              Our Services may integrate with or depend upon third-party platforms (including but not
              limited to Stripe, Google, Zoom, Anthropic, Resend, and others). These third-party services
              have their own terms of service and privacy policies, and your use of them is governed by
              those terms. TIBLOGICS is not responsible for the availability, accuracy, or practices of
              any third-party service.
            </p>
          </section>

          {/* 12 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">12. Governing Law and Dispute Resolution</h2>

            <h3 className="font-semibold text-[#0D1B2A] mb-2">12.1 Governing Law</h3>
            <p>
              These Terms are governed by and construed in accordance with the laws of the State of
              Maryland, USA, without regard to its conflict of law principles. The United Nations
              Convention on Contracts for the International Sale of Goods does not apply.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">12.2 Informal Resolution</h3>
            <p>
              Before filing any formal claim, you agree to first contact TIBLOGICS at{" "}
              <a href="mailto:info@tiblogics.com" className="text-[#2251A3] hover:underline">info@tiblogics.com</a>{" "}
              and attempt to resolve the dispute informally. We will respond within 14 business days.
              If the dispute is not resolved within 30 days of your notice, either party may proceed
              to formal dispute resolution.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">12.3 Binding Arbitration</h3>
            <p>
              Any dispute, claim, or controversy arising out of or relating to these Terms or the Services
              that cannot be resolved informally shall be resolved by binding arbitration administered by
              the American Arbitration Association (AAA) under its Commercial Arbitration Rules, with
              proceedings conducted in Montgomery County, Maryland, USA. The arbitrator's decision will
              be final and binding and may be entered as a judgment in any court of competent jurisdiction.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">12.4 Class Action Waiver</h3>
            <p>
              <strong>YOU WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE
              ARBITRATION AGAINST TIBLOGICS.</strong> All claims must be brought in an individual
              capacity only.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">12.5 Exceptions</h3>
            <p>
              Notwithstanding the above, either party may seek emergency injunctive or equitable relief
              in any court of competent jurisdiction to prevent irreparable harm, including to protect
              intellectual property rights or Confidential Information.
            </p>
          </section>

          {/* 13 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">13. General Provisions</h2>

            <h3 className="font-semibold text-[#0D1B2A] mb-2">13.1 Entire Agreement</h3>
            <p>
              These Terms, together with any applicable SOW, service agreement, or addendum, constitute
              the entire agreement between you and TIBLOGICS regarding the subject matter hereof and
              supersede all prior negotiations, representations, or agreements.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">13.2 Severability</h3>
            <p>
              If any provision of these Terms is found to be invalid, illegal, or unenforceable, that
              provision will be modified to the minimum extent necessary to make it enforceable, and the
              remaining provisions will continue in full force and effect.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">13.3 Waiver</h3>
            <p>
              Our failure to enforce any provision of these Terms does not constitute a waiver of our
              right to enforce that provision in the future.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">13.4 Assignment</h3>
            <p>
              You may not assign or transfer your rights or obligations under these Terms without our
              prior written consent. TIBLOGICS may assign these Terms freely, including in connection
              with a merger, acquisition, or sale of assets.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">13.5 Force Majeure</h3>
            <p>
              TIBLOGICS will not be liable for any delay or failure to perform its obligations resulting
              from causes beyond its reasonable control, including acts of God, natural disasters, war,
              terrorism, civil unrest, government action, labour disputes, or failure of third-party
              infrastructure or services.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">13.6 Updates to These Terms</h3>
            <p>
              We reserve the right to modify these Terms at any time. Material changes will be communicated
              via the Site or email. Continued use of the Services after the effective date of any changes
              constitutes your acceptance of the revised Terms. We encourage you to review these Terms
              periodically.
            </p>

            <h3 className="font-semibold text-[#0D1B2A] mt-5 mb-2">13.7 Electronic Communications</h3>
            <p>
              By using our Services, you consent to receive electronic communications from TIBLOGICS.
              You agree that electronic communications satisfy any legal requirement that communications
              be in writing.
            </p>
          </section>

          {/* 14 */}
          <section>
            <h2 className="font-syne font-bold text-xl text-[#0D1B2A] mb-4">14. Contact</h2>
            <p>Questions about these Terms? Contact us:</p>
            <div className="mt-4 bg-[#F4F7FB] rounded-xl p-5 border border-[#E8EFF8]">
              <p><strong>TIBLOGICS LLC</strong></p>
              <p>Wheaton, Maryland, USA</p>
              <p className="mt-2">
                Email:{" "}
                <a href="mailto:info@tiblogics.com" className="text-[#2251A3] hover:underline">info@tiblogics.com</a>
              </p>
              <p>
                Website:{" "}
                <a href="https://tiblogics.com" className="text-[#2251A3] hover:underline">tiblogics.com</a>
              </p>
            </div>
          </section>

        </div>
      </div>
    </div>
  );
}
