// Task Sorter decks: real work tasks for six roles, in English, French and
// Swahili. Each card has a recommended bucket, why, what goes wrong if it is
// misplaced, and an illustrative "hours per week" used only for the playful
// week summary (not a measurement).

import { l3, type L3 } from "./l3";

export type Bucket = "automate" | "augment" | "human";
export const BUCKETS: Bucket[] = ["automate", "augment", "human"];

export interface SortCard {
  id: string;
  bucket: Bucket;
  /** A defensible second choice: half credit. */
  alt?: Bucket;
  hrs: number;
  task: L3;
  why: L3;
  risk: L3;
}

export interface Deck {
  id: string;
  icon: string;
  difficulty: 1 | 2 | 3;
  cards: SortCard[];
}

type T = readonly [string, string, string];
const c = (id: string, bucket: Bucket, hrs: number, task: T, why: T, risk: T, alt?: Bucket): SortCard => ({
  id,
  bucket,
  alt,
  hrs,
  task: l3(task),
  why: l3(why),
  risk: l3(risk),
});

/** Illustrative share of a task's time freed up per bucket. */
export const SAVE_FACTOR: Record<Bucket, number> = { automate: 0.7, augment: 0.35, human: 0 };

export const DECKS: Deck[] = [
  {
    id: "office",
    icon: "🗃️",
    difficulty: 1,
    cards: [
      c("o1", "automate", 2,
        ["Sort incoming email into folders by sender and subject", "Trier les e-mails entrants dans des dossiers selon l'expéditeur et l'objet", "Kupanga email zinazoingia kwenye folda kwa mtumaji na mada"],
        ["Clear rules, repeated every day, and a wrong folder is easy to spot and fix.", "Des règles claires, répétées chaque jour, et une erreur de dossier se voit et se corrige facilement.", "Kanuni ziko wazi, kazi inajirudia kila siku, na kosa la folda linaonekana na kurekebishwa kwa urahisi."],
        ["Kept by hand, it quietly eats hours every week.", "Fait à la main, cela grignote des heures chaque semaine.", "Ukifanya kwa mkono, inakula saa nyingi kila wiki bila kuonekana."]),
      c("o2", "augment", 3,
        ["Draft replies to routine enquiries", "Rédiger des réponses aux demandes courantes", "Kuandaa rasimu za majibu kwa maswali ya kawaida"],
        ["AI writes a solid first draft; you check the tone and the facts before sending.", "L'IA écrit un bon premier jet ; vous vérifiez le ton et les faits avant d'envoyer.", "AI inaandika rasimu nzuri ya kwanza; wewe unakagua sauti na ukweli kabla ya kutuma."],
        ["Fully automatic replies can promise things you cannot deliver.", "Des réponses entièrement automatiques peuvent promettre ce que vous ne pouvez pas tenir.", "Majibu ya kiotomatiki kabisa yanaweza kuahidi mambo usiyoweza kutimiza."]),
      c("o3", "automate", 2,
        ["Find a meeting time that works across five calendars", "Trouver un créneau de réunion commun à cinq agendas", "Kutafuta muda wa mkutano unaofaa kalenda tano"],
        ["Scheduling tools compare calendars instantly and follow simple rules.", "Les outils de planification comparent les agendas instantanément selon des règles simples.", "Zana za kupanga ratiba hulinganisha kalenda papo hapo kwa kanuni rahisi."],
        ["Doing it by hand means long email chains and double bookings.", "À la main, ce sont de longs échanges d'e-mails et des doubles réservations.", "Kwa mkono, ni mlolongo mrefu wa email na kupanga mara mbili."]),
      c("o4", "augment", 2,
        ["Turn long meeting notes into action items", "Transformer de longues notes de réunion en actions à mener", "Kugeuza maelezo marefu ya mkutano kuwa hatua za kuchukua"],
        ["AI summarises fast but can miss or invent an action; you confirm owners and dates.", "L'IA résume vite mais peut oublier ou inventer une action ; vous confirmez les responsables et les dates.", "AI inafupisha haraka lakini inaweza kusahau au kubuni hatua; wewe unathibitisha wahusika na tarehe."],
        ["Unchecked summaries can give tasks to the wrong person.", "Un résumé non vérifié peut confier une tâche à la mauvaise personne.", "Muhtasari usiokaguliwa unaweza kumpa mtu asiyehusika kazi."]),
      c("o5", "human", 1,
        ["Handle a complaint from an upset long-time client", "Gérer la réclamation d'un client fidèle et mécontent", "Kushughulikia lalamiko la mteja wa muda mrefu aliyekasirika"],
        ["It needs empathy, judgment and the authority to make things right.", "Il faut de l'empathie, du jugement et l'autorité pour réparer la situation.", "Inahitaji huruma, busara na mamlaka ya kurekebisha mambo."],
        ["A bot reply can make a loyal client feel ignored and leave.", "Une réponse de robot peut donner au client le sentiment d'être ignoré et le faire partir.", "Jibu la roboti linaweza kumfanya mteja mwaminifu ahisi amepuuzwa na aondoke."],
        "augment"),
      c("o6", "automate", 1.5,
        ["Rename and file scanned invoices", "Renommer et classer les factures numérisées", "Kubadilisha majina na kupanga ankara zilizoskaniwa"],
        ["A pattern-based task that software does reliably and you can spot-check.", "Une tâche répétitive que le logiciel fait de façon fiable, avec des contrôles ponctuels.", "Ni kazi ya mfumo unaojirudia ambayo programu inaifanya vizuri na unaweza kukagua kwa sampuli."],
        ["By hand it is slow and files end up in the wrong place.", "À la main c'est lent et des fichiers finissent au mauvais endroit.", "Kwa mkono ni polepole na faili huishia mahali pasipo sahihi."]),
      c("o7", "augment", 2,
        ["Write the monthly team report", "Rédiger le rapport mensuel de l'équipe", "Kuandika ripoti ya kila mwezi ya timu"],
        ["AI can pull figures into a draft; you add context and check every number.", "L'IA peut rassembler les chiffres dans un brouillon ; vous ajoutez le contexte et vérifiez chaque nombre.", "AI inaweza kukusanya takwimu kwenye rasimu; wewe unaongeza muktadha na kukagua kila namba."],
        ["A report sent without review can spread wrong numbers to leaders.", "Un rapport envoyé sans relecture peut diffuser de faux chiffres à la direction.", "Ripoti inayotumwa bila kukaguliwa inaweza kusambaza namba potofu kwa viongozi."]),
      c("o8", "human", 1,
        ["Decide which supplier wins the contract", "Décider quel fournisseur remporte le contrat", "Kuamua msambazaji gani apate mkataba"],
        ["AI can compare quotes, but the decision and the accountability stay with people.", "L'IA peut comparer les devis, mais la décision et la responsabilité restent humaines.", "AI inaweza kulinganisha bei, lakini uamuzi na uwajibikaji vinabaki kwa watu."],
        ["Letting a tool decide hides who is responsible if it goes wrong.", "Laisser un outil décider masque qui est responsable en cas d'erreur.", "Kuacha zana iamue kunaficha nani anawajibika mambo yakienda vibaya."],
        "augment"),
      c("o9", "automate", 1,
        ["Send reminders for overdue timesheets", "Envoyer des relances pour les feuilles de temps en retard", "Kutuma vikumbusho vya fomu za saa zilizochelewa"],
        ["Same message, clear trigger, low stakes: ideal for automation.", "Même message, déclencheur clair, faible enjeu : idéal pour l'automatisation.", "Ujumbe ule ule, kichocheo wazi, hatari ndogo: inafaa kabisa kwa otomatiki."],
        ["Chasing people by hand wastes time and feels personal.", "Relancer chacun à la main fait perdre du temps et paraît personnel.", "Kufuatilia kila mtu kwa mkono kunapoteza muda na kunaonekana binafsi."]),
      c("o10", "augment", 0.5,
        ["Translate a short internal notice into another language", "Traduire une courte note interne dans une autre langue", "Kutafsiri tangazo fupi la ndani kwa lugha nyingine"],
        ["AI translation is good, but a fluent reader should check it.", "La traduction par IA est bonne, mais un lecteur qui maîtrise la langue doit la vérifier.", "Tafsiri ya AI ni nzuri, lakini mtu anayeijua lugha vizuri aikague."],
        ["An unchecked translation can say something you never meant.", "Une traduction non vérifiée peut dire tout autre chose que prévu.", "Tafsiri isiyokaguliwa inaweza kusema jambo ambalo hukukusudia."]),
      c("o11", "human", 1,
        ["Welcome a new colleague on their first day", "Accueillir un nouveau collègue le premier jour", "Kumkaribisha mfanyakazi mpya siku yake ya kwanza"],
        ["Belonging and trust are built person to person.", "Le sentiment d'appartenance et la confiance se construisent de personne à personne.", "Hisia ya kuwa sehemu ya timu na uaminifu hujengwa kati ya mtu na mtu."],
        ["An automated welcome can make someone feel like a number.", "Un accueil automatisé peut donner l'impression d'être un simple numéro.", "Makaribisho ya kiotomatiki yanaweza kumfanya mtu ajihisi kama namba tu."]),
    ],
  },
  {
    id: "healthcare",
    icon: "🏥",
    difficulty: 2,
    cards: [
      c("h1", "automate", 2,
        ["Send appointment reminders by SMS", "Envoyer des rappels de rendez-vous par SMS", "Kutuma vikumbusho vya miadi kwa SMS"],
        ["A fixed message triggered by the booking system; fewer missed appointments.", "Un message fixe déclenché par le système de rendez-vous ; moins de rendez-vous manqués.", "Ujumbe maalum unaotumwa na mfumo wa miadi; miadi michache inakosekana."],
        ["Calling everyone by hand takes hours and some get forgotten.", "Appeler chacun à la main prend des heures et certains sont oubliés.", "Kumpigia kila mtu simu kunachukua saa nyingi na wengine husahaulika."]),
      c("h2", "augment", 3,
        ["Turn a doctor's dictated letter into a typed draft", "Transformer une lettre dictée par un médecin en brouillon tapé", "Kugeuza barua iliyosomwa na daktari kuwa rasimu iliyochapwa"],
        ["Speech-to-text saves time, and the clinician must check every medical detail.", "La dictée vocale fait gagner du temps, et le médecin doit vérifier chaque détail médical.", "Kubadili sauti kuwa maandishi kunaokoa muda, na daktari lazima akague kila taarifa ya kitabibu."],
        ["An unchecked error in a medical letter can harm a patient.", "Une erreur non vérifiée dans une lettre médicale peut nuire à un patient.", "Kosa lisilokaguliwa kwenye barua ya kitabibu linaweza kumdhuru mgonjwa."]),
      c("h3", "human", 1,
        ["Tell a patient their test result is abnormal", "Annoncer à un patient que son résultat d'analyse est anormal", "Kumjulisha mgonjwa kwamba kipimo chake si cha kawaida"],
        ["Sensitive news and clinical responsibility belong to a clinician.", "Une nouvelle sensible et la responsabilité clinique relèvent d'un soignant.", "Habari nyeti na wajibu wa kitabibu ni wa mhudumu wa afya."],
        ["Automated bad news causes fear, confusion and loss of trust.", "Une mauvaise nouvelle automatisée provoque peur, confusion et perte de confiance.", "Habari mbaya ya kiotomatiki husababisha hofu, mkanganyiko na kupoteza imani."]),
      c("h4", "augment", 3,
        ["Assign billing codes to routine visits", "Attribuer les codes de facturation aux consultations courantes", "Kuweka misimbo ya malipo kwa ziara za kawaida"],
        ["AI can suggest codes; trained staff confirm them.", "L'IA peut proposer des codes ; un personnel formé les valide.", "AI inaweza kupendekeza misimbo; wafanyakazi waliofunzwa wanaithibitisha."],
        ["Wrong codes lead to rejected claims or compliance problems.", "De mauvais codes entraînent des refus de remboursement ou des problèmes de conformité.", "Misimbo isiyo sahihi husababisha madai kukataliwa au matatizo ya kufuata sheria."]),
      c("h5", "automate", 2,
        ["Check a patient's insurance eligibility online", "Vérifier en ligne la couverture d'assurance d'un patient", "Kukagua mtandaoni kama bima ya mgonjwa inamhudumia"],
        ["A standard lookup against the insurer's system with a clear yes or no.", "Une consultation standard du système de l'assureur, avec un oui ou un non clair.", "Ni ukaguzi wa kawaida kwenye mfumo wa bima wenye jibu la ndiyo au hapana."],
        ["Manual checks slow down the front desk and create queues.", "Les vérifications manuelles ralentissent l'accueil et créent des files d'attente.", "Ukaguzi wa mkono unachelewesha mapokezi na kusababisha foleni."]),
      c("h6", "human", 1.5,
        ["Decide whether a caller needs urgent care", "Décider si un appelant a besoin de soins urgents", "Kuamua kama mpigaji simu anahitaji huduma ya dharura"],
        ["Urgency decisions need trained staff following clear protocols.", "Juger l'urgence exige un personnel formé qui suit des protocoles clairs.", "Maamuzi ya dharura yanahitaji wafanyakazi waliofunzwa wanaofuata taratibu wazi."],
        ["An automated triage could miss an emergency.", "Un tri automatisé pourrait passer à côté d'une urgence.", "Uchujaji wa kiotomatiki unaweza kukosa dharura."]),
      c("h7", "automate", 2,
        ["Answer questions about opening hours and parking", "Répondre aux questions sur les horaires et le parking", "Kujibu maswali kuhusu saa za kufungua na maegesho"],
        ["Fixed answers and low risk: a simple FAQ bot or auto-reply works well.", "Réponses fixes et faible risque : une FAQ ou une réponse automatique suffit.", "Majibu yasiyobadilika na hatari ndogo: bot rahisi ya maswali inatosha."],
        ["Staff answering the same question all day lose time for patients.", "Le personnel qui répond toute la journée à la même question perd du temps pour les patients.", "Wafanyakazi wakijibu swali lile lile siku nzima wanapoteza muda wa wagonjwa."]),
      c("h8", "augment", 1,
        ["Write a patient-friendly leaflet about a procedure", "Rédiger une brochure claire pour les patients sur une intervention", "Kuandika kijarida rahisi kwa wagonjwa kuhusu utaratibu fulani"],
        ["AI drafts plain language quickly; a clinician approves the content.", "L'IA rédige vite en langage simple ; un soignant valide le contenu.", "AI inaandika kwa lugha rahisi haraka; mhudumu wa afya anaidhinisha maudhui."],
        ["Health information with errors can lead to unsafe choices.", "Une information de santé erronée peut mener à des choix dangereux.", "Taarifa za afya zenye makosa zinaweza kusababisha maamuzi hatari."]),
      c("h9", "automate", 1.5,
        ["Match daily payments against the booking system", "Rapprocher les paiements du jour avec le système de rendez-vous", "Kulinganisha malipo ya kila siku na mfumo wa miadi"],
        ["Numbers against numbers: software flags the mismatches for a person to review.", "Des chiffres face à des chiffres : le logiciel signale les écarts pour qu'une personne les examine.", "Namba dhidi ya namba: programu inaonyesha tofauti ili mtu azikague."],
        ["By hand, small errors slip through and pile up.", "À la main, de petites erreurs passent et s'accumulent.", "Kwa mkono, makosa madogo hupita na kulimbikizana."],
        "augment"),
      c("h10", "human", 1,
        ["Comfort a worried family member in the waiting room", "Rassurer un proche inquiet en salle d'attente", "Kumtuliza mwanafamilia mwenye wasiwasi kwenye chumba cha kusubiri"],
        ["Presence and care cannot be automated.", "La présence et l'attention ne s'automatisent pas.", "Uwepo na kujali haviwezi kufanywa kiotomatiki."],
        ["A screen instead of a person feels cold at a hard moment.", "Un écran à la place d'une personne paraît froid dans un moment difficile.", "Skrini badala ya mtu inahisi baridi wakati mgumu."]),
      c("h11", "augment", 1.5,
        ["Build next month's staff rota from requests", "Construire le planning du mois prochain à partir des demandes", "Kuandaa ratiba ya zamu ya mwezi ujao kutokana na maombi"],
        ["AI can propose a rota; a manager checks fairness and safe cover.", "L'IA peut proposer un planning ; un responsable vérifie l'équité et la couverture.", "AI inaweza kupendekeza ratiba; msimamizi anakagua haki na idadi salama ya wafanyakazi."],
        ["An unchecked rota can be unfair or leave a shift short-staffed.", "Un planning non vérifié peut être injuste ou laisser une garde en sous-effectif.", "Ratiba isiyokaguliwa inaweza kuwa si ya haki au kuacha zamu na watu wachache."]),
    ],
  },
  {
    id: "teacher",
    icon: "🍎",
    difficulty: 1,
    cards: [
      c("t1", "automate", 2,
        ["Mark multiple-choice quizzes", "Corriger des QCM", "Kusahihisha majaribio ya kuchagua jibu"],
        ["One right answer per question: a quiz tool marks it instantly.", "Une seule bonne réponse par question : un outil de quiz corrige instantanément.", "Kuna jibu moja sahihi kwa kila swali: zana ya majaribio inasahihisha papo hapo."],
        ["Marking by hand takes evenings you could spend on feedback.", "Corriger à la main prend des soirées que vous pourriez consacrer aux retours.", "Kusahihisha kwa mkono kunachukua jioni ambazo ungetumia kutoa maoni."]),
      c("t2", "augment", 4,
        ["Write feedback on student essays", "Rédiger des commentaires sur les rédactions des élèves", "Kuandika maoni kwenye insha za wanafunzi"],
        ["AI can suggest comments; you know the student and decide the grade.", "L'IA peut suggérer des commentaires ; vous connaissez l'élève et décidez de la note.", "AI inaweza kupendekeza maoni; wewe unamjua mwanafunzi na unaamua alama."],
        ["Generic or wrong feedback demotivates; grades must be yours.", "Des commentaires génériques ou faux démotivent ; la note doit rester la vôtre.", "Maoni ya jumla au yasiyo sahihi yanakatisha tamaa; alama lazima ziwe zako."]),
      c("t3", "human", 1,
        ["Talk with a parent about a child's wellbeing", "Parler avec un parent du bien-être de son enfant", "Kuzungumza na mzazi kuhusu ustawi wa mtoto"],
        ["Trust, tact and professional judgment are needed.", "Il faut de la confiance, du tact et un jugement professionnel.", "Inahitaji uaminifu, busara na uamuzi wa kitaaluma."],
        ["A templated message can damage the relationship with the family.", "Un message type peut abîmer la relation avec la famille.", "Ujumbe wa kiolezo unaweza kuharibu uhusiano na familia."]),
      c("t4", "augment", 2,
        ["Create practice questions at three levels", "Créer des exercices à trois niveaux de difficulté", "Kutunga maswali ya mazoezi kwa viwango vitatu"],
        ["AI generates quickly; you check accuracy and level.", "L'IA génère vite ; vous vérifiez l'exactitude et le niveau.", "AI inatunga haraka; wewe unakagua usahihi na kiwango."],
        ["Errors in questions confuse learners.", "Des erreurs dans les questions embrouillent les élèves.", "Makosa kwenye maswali yanawachanganya wanafunzi."]),
      c("t5", "automate", 1,
        ["Collect permission slips and flag the missing ones", "Collecter les autorisations parentales et signaler celles qui manquent", "Kukusanya fomu za ruhusa na kuonyesha zilizokosekana"],
        ["A form and a list: the tool tracks who replied and reminds the rest.", "Un formulaire et une liste : l'outil suit les réponses et relance les autres.", "Fomu na orodha: zana inafuatilia waliojibu na kuwakumbusha wengine."],
        ["Paper chasing eats class time and slips get lost.", "Courir après les papiers prend du temps de classe et des feuilles se perdent.", "Kufuatilia karatasi kunakula muda wa darasa na fomu hupotea."]),
      c("t6", "augment", 1,
        ["Adapt a text for a student who reads below grade level", "Adapter un texte pour un élève en difficulté de lecture", "Kurahisisha maandishi kwa mwanafunzi anayesoma chini ya kiwango"],
        ["AI simplifies text well; you check the meaning is kept.", "L'IA simplifie bien un texte ; vous vérifiez que le sens est conservé.", "AI inarahisisha maandishi vizuri; wewe unakagua maana haijabadilika."],
        ["An unchecked version may drop key ideas.", "Une version non vérifiée peut perdre des idées essentielles.", "Toleo lisilokaguliwa linaweza kuacha mawazo muhimu."]),
      c("t7", "human", 1,
        ["Decide how to handle a bullying incident", "Décider comment traiter un cas de harcèlement", "Kuamua jinsi ya kushughulikia tukio la uonevu"],
        ["Safeguarding and fairness need a professional who knows the students.", "La protection et l'équité exigent un professionnel qui connaît les élèves.", "Ulinzi na haki vinahitaji mtaalamu anayewafahamu wanafunzi."],
        ["An automated decision could miss context and leave a child unsafe.", "Une décision automatisée pourrait manquer le contexte et laisser un enfant en danger.", "Uamuzi wa kiotomatiki unaweza kukosa muktadha na kumwacha mtoto hatarini."]),
      c("t8", "augment", 0.5,
        ["Translate the class newsletter for families", "Traduire la lettre d'information de la classe pour les familles", "Kutafsiri jarida la darasa kwa ajili ya familia"],
        ["AI translates quickly; a fluent colleague or parent checks it.", "L'IA traduit vite ; un collègue ou un parent qui maîtrise la langue relit.", "AI inatafsiri haraka; mwenzako au mzazi anayeijua lugha anakagua."],
        ["A mistranslated date or instruction confuses families.", "Une date ou une consigne mal traduite embrouille les familles.", "Tarehe au maelekezo yaliyotafsiriwa vibaya yanachanganya familia."]),
      c("t9", "augment", 3,
        ["Plan a lesson and how to engage your class", "Préparer une leçon et la manière d'impliquer la classe", "Kupanga somo na jinsi ya kuwashirikisha wanafunzi"],
        ["AI can brainstorm activities; you design for the students in front of you.", "L'IA peut proposer des activités ; vous concevez pour les élèves que vous avez devant vous.", "AI inaweza kutoa mawazo ya shughuli; wewe unapanga kwa ajili ya wanafunzi walio mbele yako."],
        ["A generic plan ignores what your class actually needs.", "Un plan générique ignore les besoins réels de votre classe.", "Mpango wa jumla unapuuza mahitaji halisi ya darasa lako."],
        "human"),
      c("t10", "human", 1,
        ["Mentor a new teacher", "Accompagner un nouvel enseignant", "Kumlea mwalimu mpya kitaaluma"],
        ["Mentoring is a relationship built on experience and trust.", "Le mentorat est une relation fondée sur l'expérience et la confiance.", "Ushauri ni uhusiano unaojengwa juu ya uzoefu na uaminifu."],
        ["Tips from a tool cannot replace a colleague who listens.", "Des conseils d'un outil ne remplacent pas un collègue qui écoute.", "Vidokezo vya zana haviwezi kuchukua nafasi ya mwenzako anayesikiliza."]),
      c("t11", "automate", 1,
        ["Record attendance and send absence notices", "Enregistrer les présences et envoyer les avis d'absence", "Kurekodi mahudhurio na kutuma taarifa za kutokuwepo"],
        ["A register plus a standard message: the school system can send it.", "Un registre et un message type : le système de l'école peut l'envoyer.", "Daftari na ujumbe wa kawaida: mfumo wa shule unaweza kuutuma."],
        ["Manual notices are late or forgotten.", "Les avis manuels arrivent en retard ou sont oubliés.", "Taarifa za mkono huchelewa au husahaulika."]),
    ],
  },
  {
    id: "shop",
    icon: "🛍️",
    difficulty: 1,
    cards: [
      c("s1", "automate", 2,
        ["Update stock counts after each sale", "Mettre à jour le stock après chaque vente", "Kusasisha idadi ya bidhaa baada ya kila mauzo"],
        ["A point-of-sale system does this at every sale, with no extra work.", "Un logiciel de caisse le fait à chaque vente, sans effort supplémentaire.", "Mfumo wa mauzo unafanya hivi kila mauzo bila kazi ya ziada."],
        ["By hand, counts drift and you run out without warning.", "À la main, les chiffres dérivent et la rupture arrive sans prévenir.", "Kwa mkono, hesabu zinapotoka na bidhaa zinaisha bila tahadhari."]),
      c("s2", "augment", 2,
        ["Write product descriptions for the online shop", "Rédiger les fiches produits de la boutique en ligne", "Kuandika maelezo ya bidhaa kwa duka la mtandaoni"],
        ["AI drafts fast; you make sure every feature and size is true.", "L'IA rédige vite ; vous vérifiez que chaque caractéristique et taille est exacte.", "AI inaandika haraka; wewe unahakikisha kila sifa na kipimo ni kweli."],
        ["Invented features mean returns, complaints and lost trust.", "Des caractéristiques inventées entraînent retours, plaintes et perte de confiance.", "Sifa za kubuni zinaleta marejesho, malalamiko na kupoteza imani."]),
      c("s3", "augment", 0.5,
        ["Reply to a negative online review", "Répondre à un avis négatif en ligne", "Kujibu tathmini mbaya mtandaoni"],
        ["AI can suggest a calm draft; you make it personal and honest.", "L'IA peut proposer un brouillon posé ; vous le rendez personnel et honnête.", "AI inaweza kupendekeza rasimu tulivu; wewe unaifanya ya kibinafsi na ya kweli."],
        ["An automatic public reply can sound robotic or defensive.", "Une réponse publique automatique peut sembler robotique ou sur la défensive.", "Jibu la umma la kiotomatiki linaweza kusikika kama roboti au la kujitetea."],
        "human"),
      c("s4", "human", 1,
        ["Negotiate prices with a supplier", "Négocier les prix avec un fournisseur", "Kujadiliana bei na msambazaji"],
        ["Relationships and trade-offs are your call.", "La relation et les compromis vous appartiennent.", "Mahusiano na maelewano ni uamuzi wako."],
        ["An automated negotiation can damage a long relationship.", "Une négociation automatisée peut abîmer une relation de longue date.", "Majadiliano ya kiotomatiki yanaweza kuharibu uhusiano wa muda mrefu."]),
      c("s5", "automate", 1,
        ["Send 'your order has shipped' messages", "Envoyer les messages « votre commande est expédiée »", "Kutuma ujumbe wa 'oda yako imetumwa'"],
        ["Triggered by the shipping status; the same message every time.", "Déclenché par le statut d'expédition ; le même message à chaque fois.", "Unatumwa na hali ya usafirishaji; ujumbe ule ule kila mara."],
        ["Forgotten updates lead to worried customers calling you.", "Des mises à jour oubliées poussent les clients inquiets à vous appeler.", "Taarifa zilizosahaulika zinafanya wateja wenye wasiwasi wakupigie."]),
      c("s6", "augment", 2,
        ["Draft social media posts for the week", "Préparer les publications de la semaine sur les réseaux sociaux", "Kuandaa machapisho ya mitandao ya kijamii ya wiki"],
        ["AI gives ideas and drafts; you keep your voice and check claims.", "L'IA donne des idées et des brouillons ; vous gardez votre ton et vérifiez les affirmations.", "AI inatoa mawazo na rasimu; wewe unadumisha sauti yako na kukagua madai."],
        ["Posts that sound generic or make false claims hurt your brand.", "Des publications génériques ou trompeuses nuisent à votre marque.", "Machapisho ya jumla au yenye madai ya uongo yanadhuru chapa yako."]),
      c("s7", "human", 1,
        ["Decide whether to hire a new staff member", "Décider d'embaucher un nouvel employé", "Kuamua kama uajiri mfanyakazi mpya"],
        ["A people decision with legal and personal consequences.", "Une décision humaine avec des conséquences juridiques et personnelles.", "Ni uamuzi kuhusu watu wenye matokeo ya kisheria na ya kibinafsi."],
        ["Handing it to a tool can bring in unfair bias.", "Le confier à un outil peut introduire des biais injustes.", "Kuikabidhi zana kunaweza kuleta upendeleo usio wa haki."],
        "augment"),
      c("s8", "automate", 2,
        ["Match the bank statement with sales records", "Rapprocher le relevé bancaire et les ventes", "Kulinganisha taarifa ya benki na rekodi za mauzo"],
        ["Accounting software matches most lines; you look only at the exceptions.", "Le logiciel comptable rapproche la plupart des lignes ; vous ne regardez que les exceptions.", "Programu ya uhasibu inalinganisha mistari mingi; wewe unaangalia tofauti tu."],
        ["Manual matching is slow and errors hide in the totals.", "Le rapprochement manuel est lent et les erreurs se cachent dans les totaux.", "Kulinganisha kwa mkono ni polepole na makosa hujificha kwenye jumla."],
        "augment"),
      c("s9", "automate", 1,
        ["Answer 'are you open on Sunday?' messages", "Répondre aux messages « êtes-vous ouverts dimanche ? »", "Kujibu ujumbe wa 'mko wazi Jumapili?'"],
        ["A saved auto-reply with your hours answers it instantly.", "Une réponse automatique avec vos horaires répond instantanément.", "Jibu la kiotomatiki lenye saa zako linajibu papo hapo."],
        ["Answering by hand interrupts serving customers in the shop.", "Répondre à la main interrompt le service en boutique.", "Kujibu kwa mkono kunakatiza kuwahudumia wateja dukani."]),
      c("s10", "augment", 1,
        ["Find which products sell best each season", "Trouver quels produits se vendent le mieux selon la saison", "Kubaini bidhaa zinazouzwa zaidi kila msimu"],
        ["AI spots patterns in sales data; you add local context like holidays and weather.", "L'IA repère les tendances dans les ventes ; vous ajoutez le contexte local comme les fêtes et la météo.", "AI inaona mwenendo kwenye data ya mauzo; wewe unaongeza muktadha wa eneo kama sikukuu na hali ya hewa."],
        ["Trusting the pattern blindly can mean over-ordering.", "Suivre la tendance à l'aveugle peut mener au surstock.", "Kuamini mwenendo bila kufikiri kunaweza kusababisha kuagiza kupita kiasi."]),
      c("s11", "human", 0.5,
        ["Handle a refund request outside your policy", "Traiter une demande de remboursement hors politique", "Kushughulikia ombi la kurejesha pesa nje ya sera"],
        ["An exception needs judgment about the customer and the situation.", "Une exception demande du jugement sur le client et la situation.", "Jambo la kipekee linahitaji busara kuhusu mteja na hali."],
        ["A rigid automatic 'no' can lose a good customer.", "Un « non » automatique et rigide peut faire perdre un bon client.", "'Hapana' ya kiotomatiki isiyobadilika inaweza kukupotezea mteja mzuri."]),
    ],
  },
  {
    id: "social",
    icon: "🤝",
    difficulty: 3,
    cards: [
      c("w1", "human", 3,
        ["Assess whether a child is safe at home", "Évaluer si un enfant est en sécurité chez lui", "Kutathmini kama mtoto yuko salama nyumbani"],
        ["Safeguarding decisions need professional judgment, visits and accountability.", "La protection de l'enfance exige un jugement professionnel, des visites et une responsabilité claire.", "Maamuzi ya ulinzi wa mtoto yanahitaji uamuzi wa kitaaluma, kutembelea na uwajibikaji."],
        ["Automating it could leave a child in danger.", "L'automatiser pourrait laisser un enfant en danger.", "Kuifanya kiotomatiki kunaweza kumwacha mtoto hatarini."]),
      c("w2", "augment", 4,
        ["Turn your case notes into a formal report draft", "Transformer vos notes de suivi en brouillon de rapport officiel", "Kugeuza maelezo yako ya kesi kuwa rasimu ya ripoti rasmi"],
        ["Saves writing time if you use an approved, secure tool and check every fact.", "Fait gagner du temps si vous utilisez un outil approuvé et sécurisé et vérifiez chaque fait.", "Inaokoa muda ukitumia zana iliyoidhinishwa na salama na kukagua kila ukweli."],
        ["An error in a report can affect decisions about a family; unapproved tools can leak confidential data.", "Une erreur dans un rapport peut peser sur les décisions concernant une famille ; un outil non approuvé peut divulguer des données confidentielles.", "Kosa kwenye ripoti linaweza kuathiri maamuzi kuhusu familia; zana zisizoidhinishwa zinaweza kuvujisha siri."]),
      c("w3", "automate", 1,
        ["Send appointment reminders to clients", "Envoyer des rappels de rendez-vous aux usagers", "Kutuma vikumbusho vya miadi kwa wateja"],
        ["A simple scheduled message with no sensitive detail in it.", "Un simple message programmé, sans détail sensible.", "Ujumbe rahisi uliopangwa bila taarifa nyeti."],
        ["Missed visits delay support for families.", "Des rendez-vous manqués retardent l'aide aux familles.", "Miadi iliyokosekana inachelewesha msaada kwa familia."]),
      c("w4", "augment", 1,
        ["Find local services such as food banks and housing help", "Trouver des services locaux comme les banques alimentaires et l'aide au logement", "Kutafuta huduma za eneo kama benki za chakula na msaada wa makazi"],
        ["AI can list options, but details go out of date; you verify before sharing.", "L'IA peut lister des options, mais les informations vieillissent ; vous vérifiez avant de partager.", "AI inaweza kuorodhesha chaguo, lakini taarifa hupitwa na wakati; wewe unathibitisha kabla ya kushiriki."],
        ["Sending a family to a closed service wastes their time and trust.", "Envoyer une famille vers un service fermé lui fait perdre du temps et de la confiance.", "Kuipeleka familia kwenye huduma iliyofungwa kunapoteza muda na imani yao."]),
      c("w5", "human", 2,
        ["Build trust with a teenager who does not want to talk", "Gagner la confiance d'un adolescent qui ne veut pas parler", "Kujenga uaminifu na kijana asiyetaka kuzungumza"],
        ["Only a patient, consistent person can build that relationship.", "Seule une personne patiente et constante peut construire cette relation.", "Ni mtu mvumilivu na thabiti pekee anayeweza kujenga uhusiano huo."],
        ["A tool here would feel like surveillance, not care.", "Un outil ici ressemblerait à de la surveillance, pas à de l'attention.", "Zana hapa ingehisiwa kama upelelezi, si kujali."]),
      c("w6", "automate", 1,
        ["Fill in mileage and expense claims", "Remplir les notes de frais et de kilométrage", "Kujaza madai ya safari na matumizi"],
        ["Structured data from your calendar and receipts: ideal for a tool.", "Des données structurées issues de l'agenda et des reçus : idéal pour un outil.", "Data iliyopangwa kutoka kalenda na risiti: inafaa kwa zana."],
        ["Paperwork steals time from families.", "La paperasse vole du temps aux familles.", "Makaratasi yanaiba muda wa familia."]),
      c("w7", "augment", 1,
        ["Translate a short note for a family who speaks another language", "Traduire un court message pour une famille qui parle une autre langue", "Kutafsiri ujumbe mfupi kwa familia inayozungumza lugha nyingine"],
        ["AI helps with simple notes; for legal or safeguarding matters use a qualified interpreter.", "L'IA aide pour les messages simples ; pour les questions juridiques ou de protection, faites appel à un interprète qualifié.", "AI inasaidia kwa ujumbe rahisi; kwa masuala ya kisheria au ulinzi tumia mkalimani aliyehitimu."],
        ["A misunderstood message can cause fear or a missed meeting.", "Un message mal compris peut provoquer de la peur ou un rendez-vous manqué.", "Ujumbe usioeleweka unaweza kusababisha hofu au kukosa mkutano."],
        "human"),
      c("w8", "human", 1,
        ["Decide whether to take a case to court", "Décider de porter un dossier devant le tribunal", "Kuamua kama kesi ipelekwe mahakamani"],
        ["A serious legal decision made by accountable professionals.", "Une décision juridique grave prise par des professionnels responsables.", "Ni uamuzi mzito wa kisheria unaofanywa na wataalamu wanaowajibika."],
        ["No tool should carry this responsibility.", "Aucun outil ne doit porter cette responsabilité.", "Hakuna zana inayopaswa kubeba jukumu hili."]),
      c("w9", "augment", 0.5,
        ["Prepare a checklist for a home visit", "Préparer une liste de contrôle pour une visite à domicile", "Kuandaa orodha ya ukaguzi kwa ziara ya nyumbani"],
        ["AI drafts a useful list; you adapt it to the family and your agency's rules.", "L'IA rédige une liste utile ; vous l'adaptez à la famille et aux règles de votre service.", "AI inaandaa orodha muhimu; wewe unairekebisha kwa familia na kanuni za taasisi yako."],
        ["A generic checklist can miss what matters for this family.", "Une liste générique peut oublier l'essentiel pour cette famille.", "Orodha ya jumla inaweza kukosa kilicho muhimu kwa familia hii."]),
      c("w10", "automate", 1,
        ["Log the date and time of each contact", "Enregistrer la date et l'heure de chaque contact", "Kurekodi tarehe na saa ya kila mawasiliano"],
        ["The case system can record it automatically from calls and meetings.", "Le système de suivi peut l'enregistrer automatiquement à partir des appels et rendez-vous.", "Mfumo wa kesi unaweza kurekodi moja kwa moja kutoka simu na mikutano."],
        ["Missing records weaken the case file.", "Des traces manquantes affaiblissent le dossier.", "Rekodi zinazokosekana zinadhoofisha faili la kesi."]),
      c("w11", "human", 1,
        ["Explain a difficult decision to a parent", "Expliquer une décision difficile à un parent", "Kumweleza mzazi uamuzi mgumu"],
        ["Hard conversations need honesty, care and a real person.", "Les conversations difficiles demandent honnêteté, attention et une vraie personne.", "Mazungumzo magumu yanahitaji ukweli, kujali na mtu halisi."],
        ["An automated message can feel cruel and break trust for good.", "Un message automatisé peut sembler cruel et briser la confiance pour de bon.", "Ujumbe wa kiotomatiki unaweza kuonekana wa kikatili na kuvunja imani milele."]),
    ],
  },
  {
    id: "sales",
    icon: "📈",
    difficulty: 2,
    cards: [
      c("a1", "automate", 3,
        ["Log calls and emails into the CRM", "Enregistrer appels et e-mails dans le CRM", "Kuingiza simu na email kwenye CRM"],
        ["Integrations capture activity automatically.", "Les intégrations enregistrent l'activité automatiquement.", "Viunganishi vinarekodi shughuli moja kwa moja."],
        ["Manual logging is skipped, so the pipeline data is wrong.", "La saisie manuelle est oubliée, donc les données du pipeline sont fausses.", "Kuingiza kwa mkono husahaulika, hivyo data ya mauzo inakuwa si sahihi."]),
      c("a2", "augment", 2,
        ["Research a prospect's company before a call", "Se renseigner sur l'entreprise d'un prospect avant un appel", "Kutafiti kampuni ya mteja mtarajiwa kabla ya simu"],
        ["AI summarises public information fast; verify it, as it can be outdated or wrong.", "L'IA résume vite l'information publique ; vérifiez-la, elle peut être dépassée ou fausse.", "AI inafupisha taarifa za umma haraka; zithibitishe, zinaweza kuwa za zamani au si sahihi."],
        ["Quoting a wrong fact on the call damages your credibility.", "Citer un fait faux pendant l'appel nuit à votre crédibilité.", "Kutaja ukweli usio sahihi kwenye simu kunaharibu uaminifu wako."]),
      c("a3", "augment", 2,
        ["Write a personalised follow-up email", "Rédiger un e-mail de relance personnalisé", "Kuandika email ya ufuatiliaji iliyobinafsishwa"],
        ["AI drafts; you add what you actually heard on the call.", "L'IA rédige ; vous ajoutez ce que vous avez réellement entendu pendant l'appel.", "AI inaandika rasimu; wewe unaongeza ulichosikia kwenye simu."],
        ["An automatic 'personalised' email that gets details wrong feels fake.", "Un e-mail « personnalisé » automatique qui se trompe de détails sonne faux.", "Email ya 'kibinafsi' ya kiotomatiki yenye makosa inaonekana ya uongo."]),
      c("a4", "human", 2,
        ["Negotiate the final terms of a big deal", "Négocier les conditions finales d'un gros contrat", "Kujadili masharti ya mwisho ya mkataba mkubwa"],
        ["Reading the room, trade-offs and commitments are human work.", "Sentir l'ambiance, arbitrer et s'engager : c'est un travail humain.", "Kusoma hali, maelewano na ahadi ni kazi ya binadamu."],
        ["Automated terms can give away margin or promise too much.", "Des conditions automatisées peuvent brader la marge ou trop promettre.", "Masharti ya kiotomatiki yanaweza kupoteza faida au kuahidi kupita kiasi."]),
      c("a5", "automate", 1,
        ["Remind a prospect when a quote is unopened after 3 days", "Relancer un prospect quand un devis n'est pas ouvert après 3 jours", "Kumkumbusha mteja mtarajiwa ikiwa nukuu haijafunguliwa baada ya siku 3"],
        ["Clear trigger, polite standard message.", "Déclencheur clair, message type poli.", "Kichocheo wazi, ujumbe wa kawaida wa heshima."],
        ["Forgetting follow-ups loses deals quietly.", "Oublier les relances fait perdre des affaires sans bruit.", "Kusahau ufuatiliaji kunapoteza mikataba kimya kimya."]),
      c("a6", "automate", 1,
        ["Score new leads by fit using clear rules", "Noter les nouveaux contacts selon des règles claires", "Kupima wateja wapya kwa kanuni wazi"],
        ["Agreed rules (size, sector, region) can be applied automatically and reviewed.", "Des règles convenues (taille, secteur, région) s'appliquent automatiquement et se vérifient.", "Kanuni zilizokubaliwa (ukubwa, sekta, eneo) zinaweza kutumika moja kwa moja na kukaguliwa."],
        ["Scoring by gut feeling is inconsistent across the team.", "Noter au feeling donne des résultats incohérents dans l'équipe.", "Kupima kwa hisia kunaleta matokeo yasiyolingana kwenye timu."],
        "augment"),
      c("a7", "human", 0.5,
        ["Offer a special discount to close a deal", "Accorder une remise spéciale pour conclure", "Kutoa punguzo maalum ili kufunga mkataba"],
        ["Commitments that affect margins need someone with authority.", "Les engagements qui touchent la marge exigent une personne habilitée.", "Ahadi zinazoathiri faida zinahitaji mtu mwenye mamlaka."],
        ["A tool that promises discounts can cost you money.", "Un outil qui promet des remises peut vous coûter cher.", "Zana inayoahidi punguzo inaweza kukugharimu pesa."]),
      c("a8", "augment", 2,
        ["Prepare a proposal draft from a template", "Préparer un brouillon de proposition à partir d'un modèle", "Kuandaa rasimu ya pendekezo kutoka kiolezo"],
        ["AI fills the template fast; you check scope, prices and promises.", "L'IA remplit le modèle rapidement ; vous vérifiez le périmètre, les prix et les engagements.", "AI inajaza kiolezo haraka; wewe unakagua wigo, bei na ahadi."],
        ["An unchecked proposal can commit you to the wrong price.", "Une proposition non vérifiée peut vous engager sur un mauvais prix.", "Pendekezo lisilokaguliwa linaweza kukufunga kwa bei isiyo sahihi."]),
      c("a9", "augment", 1,
        ["Update the weekly sales forecast", "Mettre à jour la prévision de ventes hebdomadaire", "Kusasisha makadirio ya mauzo ya wiki"],
        ["AI crunches pipeline data; you judge which deals are real.", "L'IA traite les données du pipeline ; vous jugez quelles affaires sont réelles.", "AI inachambua data ya mauzo; wewe unaamua mikataba ipi ni halisi."],
        ["A purely automatic forecast can be confidently wrong.", "Une prévision purement automatique peut se tromper avec aplomb.", "Makadirio ya kiotomatiki tu yanaweza kukosea kwa kujiamini."]),
      c("a10", "human", 1,
        ["Visit a key client to rebuild trust after a problem", "Rendre visite à un client clé pour rétablir la confiance après un problème", "Kumtembelea mteja muhimu kurejesha imani baada ya tatizo"],
        ["Showing up in person is the message.", "Se déplacer en personne, c'est déjà le message.", "Kufika ana kwa ana ndio ujumbe wenyewe."],
        ["An automated apology can make things worse.", "Des excuses automatisées peuvent aggraver la situation.", "Msamaha wa kiotomatiki unaweza kuzidisha tatizo."]),
      c("a11", "augment", 1,
        ["Turn your call notes into next steps in the CRM", "Transformer vos notes d'appel en prochaines étapes dans le CRM", "Kugeuza maelezo ya simu kuwa hatua zinazofuata kwenye CRM"],
        ["AI structures notes quickly; you confirm dates and promises.", "L'IA structure vite les notes ; vous confirmez les dates et les engagements.", "AI inapanga maelezo haraka; wewe unathibitisha tarehe na ahadi."],
        ["A wrong next step means a missed promise to the client.", "Une mauvaise étape suivante, c'est une promesse non tenue au client.", "Hatua isiyo sahihi inamaanisha ahadi kwa mteja haitimizwi."]),
    ],
  },
];

export const DECK_BY_ID = new Map(DECKS.map((d) => [d.id, d]));
